### ISSUE TITLE
Game was removed from Success Story probably after reaching 100% unlocked achievements

### ISSUE THREAD

**Issue by darklinkpower** [Lacro59/playnite-successstory-plugin#10]
One game and it's respective json file was removed. I'm not sure about the cause but it probably was after reaching 100% unlocked achievements.

![imagen](https://user-images.githubusercontent.com/1389286/83268201-dfc4d900-a18a-11ea-8847-01ca47c6262b.png)

edit: another game was removed after getting an achievement and opening success story.
![imagen](https://user-images.githubusercontent.com/1389286/83270791-95ddf200-a18e-11ea-8ce7-728e251aa8bf.png)

**Comment by Lacro59** [comment]
With the different versions, your problem is still present?

**Comment by Lacro59** [comment]
no response

**Comment by darklinkpower** [comment]
Sorry! I totally forgot about replying when I saw this! I have not had the same issues happening so it's safe to say they are gone.
