### ISSUE TITLE
crashes on startup when loading xbox achievements

### ISSUE THREAD

**Issue by git-rnbt** [Lacro59/playnite-successstory-plugin#104]
at least that seems to be what's happening. playnite seemed to be fine before i got some new achievements on an xbox game and then it started refusing to work. removing success story solves the crash.

[playnite.log](https://github.com/Lacro59/playnite-successstory-plugin/files/5967955/playnite.log)

**Comment by Lacro59** [comment]
Have you tried with the latest versions?
