### ISSUE TITLE
RetroAchievements not found

### ISSUE THREAD

**Issue by Lacro59** [Lacro59/playnite-successstory-plugin#106]
from Monthmore Kaede#4683 on Discord

how SuccesStory find Retroarchievements? I have archievements in Streets of Rage 2 and King of Fighters '98 and SuccesStory can't find these archievements.

```
25-02 21:09:49.351|DEBUG|BaseCollectionView:Refreshing collection view filter.
25-02 21:09:55.808|WARN|GenericAchievements:SuccessStory - No console find for The King of Fighters '97 with Neo Geo
25-02 21:09:55.808|WARN|GenericAchievements:SuccessStory - No game find for The King of Fighters '97 with Neo Geo in 0
25-02 21:10:00.207|WARN|GenericAchievements:SuccessStory - No console find for The King of Fighters '98: The Slugfest  with Neo Geo
25-02 21:10:00.207|WARN|GenericAchievements:SuccessStory - No game find for The King of Fighters '98: The Slugfest  with Neo Geo in 0
25-02 21:10:04.260|DEBUG|BaseCollectionView:Refreshing collection view filter.
25-02 21:10:11.205|WARN|GenericAchievements:SuccessStory - No game find for Streets of Rage 2 with 2b7b63b7d44a4f5a979998a4ea4c0b86 in PlatformType.All
25-02 21:10:11.229|WARN|GenericAchievements:SuccessStory - No game find for Streets of Rage 2 with b5ae481f806d9529ef6f32553fa725fe in PlatformType.SNES
25-02 21:10:11.355|WARN|GenericAchievements:SuccessStory - No game find for Streets of Rage 2 with 2b7b63b7d44a4f5a979998a4ea4c0b86 in PlatformType.SNES
25-02 21:10:11.355|WARN|GenericAchievements:SuccessStory - No game find for Streets of Rage 2 with a9f1a07a43e2f57250f3e128c3801e8c in PlatformType.Sega_CD_Saturn
25-02 21:10:11.460|WARN|GenericAchievements:SuccessStory - No game find for Streets of Rage 2 with 2b7b63b7d44a4f5a979998a4ea4c0b86 in PlatformType.SNES
25-02 21:10:11.472|WARN|GenericAchievements:SuccessStory - No game find for Streets of Rage 2 with e11967e168bd093ff06e2d7d4da465f4 in PlatformType.Sega_CD_Saturn
25-02 21:10:11.493|WARN|GenericAchievements:SuccessStory - No game find for Streets of Rage 2 with Genesis/Mega Drive in 7
```

**Comment by BloodShed-Oni** [comment]
Same problem with Croc - Legend of the Gobbos for Playstation.
Achievements are loaded and unlock fine in retroarch.

`13-07 21:18:54.805|WARN|GenericAchievements:SuccessStory - No game find for Croc - Legend of the Gobbos with bb8f3408ad9997b3d1df55cc14797c9d in PlatformType.All
13-07 21:18:54.818|WARN|GenericAchievements:SuccessStory - No game find for Croc - Legend of the Gobbos with bb8f3408ad9997b3d1df55cc14797c9d in PlatformType.SNES
13-07 21:18:54.827|WARN|GenericAchievements:SuccessStory - No game find for Croc - Legend of the Gobbos with bb8f3408ad9997b3d1df55cc14797c9d in PlatformType.SNES
13-07 21:18:54.827|WARN|GenericAchievements:SuccessStory - No game find for Croc - Legend of the Gobbos with c1d374dd76cc37dee03456f7c34f3b5d in PlatformType.Sega_CD_Saturn
13-07 21:18:54.845|WARN|GenericAchievements:SuccessStory - No game find for Croc - Legend of the Gobbos with bb8f3408ad9997b3d1df55cc14797c9d in PlatformType.SNES
13-07 21:18:54.845|WARN|GenericAchievements:SuccessStory - No game find for Croc - Legend of the Gobbos with bf619eac0cdf3f68d496ea9344137e8b in PlatformType.Sega_CD_Saturn
13-07 21:18:54.858|WARN|GenericAchievements:SuccessStory - No game find for Croc - Legend of the Gobbos with Sony PlayStation in 12`
