### ISSUE TITLE
SucessStory without Steam API Key broken

### ISSUE THREAD

**Issue by Fancy2209** [Lacro59/playnite-successstory-plugin#113]
I accidentally pressed enter but well
Seding this to get the bug tracked
The option to use steam achivements without the api key is bugged

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-successstory-plugin/commit/8c14d60c748350cc9e05320e391ea407ccf94bfb
https://github.com/Lacro59/playnite-successstory-plugin/commit/51ba7503f4e3d742423361d40f44ab1915b10779

**Comment by Fancy2209** [comment]
is this fixed on 1.4.4 or do I need to wait to 1.4.5?

**Comment by Lacro59** [comment]
It will be for 2.x
