### ISSUE TITLE
Google Drive forces download with RetroAchievements turned on

### ISSUE THREAD

**Issue by ferrazpedro** [Lacro59/playnite-successstory-plugin#114]
I have my ROMs in my Google Drive and uses File Stream to mount them in my PC. When I have RetroAchievements turned on, it always forces the download of any game I click to see it's info. Is the search for RetroAchievements being done by hash? If yes, would it be feasible to have an option to just search by game name? Thanks in advance!

**Comment by Lacro59** [comment]
Yes, the search is done with a hash before doing it with the name of the game.
I did not add an option but there will be no systematic new hash except during a manual update.
