### ISSUE TITLE
add manual achievements even for stores that have them

### ISSUE THREAD

**Issue by Lacro59** [Lacro59/playnite-successstory-plugin#117]
from adrian5683 on [forum](https://playnite.link/forum/thread-275-post-4588.html#pid4588)

I had a question about manual achievements as I am unable to make it work, perhaps I'm misunderstanding how it works. I own Baldur's Gate (1 and 2) on GOG, where they do not have achievements. Am I correct in assuming I could use manual achievements and pull them from the Steam store? If so, how is that done? I don't really understand the instructions on Github, where it says I can "Add the achievements list from the game menu"...

**Comment by FaithTheSlayer** [comment]
What was the answer?
