### ISSUE TITLE
Knockout city crashing Playnite (isolated to success story)

### ISSUE THREAD

**Issue by cresscendo** [Lacro59/playnite-successstory-plugin#119]
This only just started happening since I was able to play fine other days, but trying to click on Knockout City Block Party Trial within Playnite is immediately crashing Playnite. I've isolated it down to success story, but I tried turning off steam and origin achievements (game is launched through steam and then origin) but it still crashes. 

[playnite.log](https://github.com/Lacro59/playnite-successstory-plugin/files/6565046/playnite.log)

**Comment by Lacro59** [comment]
If you try the Playnite 9 beta, can you check with the v2.0?
