### ISSUE TITLE
Add "percent of achievements unlocked" tags/filters + Retroachievements "Features" metadata

### ISSUE THREAD

**Issue by drnooooo** [Lacro59/playnite-successstory-plugin#124]
As requested on the Playnite forums, I think it'd be good to have the ability to filter games by how many achievements have been unlocked out of the total. For instance, "No Achievements unlocked," "50% of Achievements unlocked," and "All Achievements unlocked" would all be useful. This way you could see at a glance which games have been started but not completed, which games haven't been played at all, and which games you've unlocked all the achievements for.

Similarly, the "Feature" filter for Achievements currently does not display Retroachievements because games with Retroachievements do not have that metadata added or built-in. Adding the appropriate Features metadata or having a tag/filter for all games with achievements including Retroachievements would also be handy.

**Comment by Lacro59** [comment]
done with [QuickSearch](https://playnite.link/forum/thread-677.html)
