### ISSUE TITLE
Clicking on Fallout New Vegas causes Playnite to crash when SuccessStory is enabled

### ISSUE THREAD

**Issue by wolfrik17** [Lacro59/playnite-successstory-plugin#128]
This is the log from playnite

[log.txt](https://github.com/Lacro59/playnite-successstory-plugin/files/7040404/log.txt)

**Comment by Lacro59** [comment]
Have you try with the beta version in Playnite 9?

**Comment by wolfrik17** [comment]
No issues so far in the beta version of Playnite 9 and SuccessStory v2.0
