### ISSUE TITLE
Always space provided to user game stats, even when disabled

### ISSUE THREAD

**Issue by Driesmann** [Lacro59/playnite-successstory-plugin#129]
I'd rather disable user game stats because it doesn't look very nice. But when I do, I get an empty space where the user game stats would normally be. Only happens with games that provide stats. Nothing major, just a bit annoying due to the empty space.

![image](https://user-images.githubusercontent.com/89516301/130766435-97e0e3d3-9b78-48c1-826f-e7b1d5a5646f.png)

![image](https://user-images.githubusercontent.com/89516301/130766537-1272600b-633d-4277-ad83-5103a10a32f4.png)

Compared to for example

![image](https://user-images.githubusercontent.com/89516301/130767446-8ba3d4e1-85e1-4fa0-9be2-a0a50cc7e9c3.png)

Which is visually more pleasing.

Using Magpie, but not the provided integration because it doesn't allow for the customisation I want.

**Comment by Lacro59** [comment]
Is the issue fixed on Playnite 9 beta?

**Comment by Driesmann** [comment]
Unfortunately I am unable to test this directly given that the theme does not have a version compatible with playnite 9. Using the Harmony theme however, the space allocated to user stats disappears when disabling user stats. 

So I assume that either the issue is fixed or, if the issue persists with Magpie should it get a Playnite 9 update, the issue is not on your end. I'll close with this comment.
