### ISSUE TITLE
Plugin causes Playnite to become unresponsive while waiting for xbox achievements

### ISSUE THREAD

**Issue by sharkusmanch** [Lacro59/playnite-successstory-plugin#130]
- Fullscreen mode, default lime theme
- After exiting Psychonauts 2, playnite becomes unresponsive
- I've narrowed the cause down to be success story. If I remove success story from my extensions folder, the issue does not occur.
- Playnite is unresponsive indefinitely until force killed by task manager.

Last log entry:
```
27-08 18:02:37.773|DEBUG|GenericAchievements:SuccessStory [Ignored] - GetXboxAchievements() - name: Psychonauts 2 - pfn: Microsoft.Psychonauts2_8wekyb3d8bbwe
```

**Comment by Jeshibu** [comment]
Happens in P9 beta 2 too

**Comment by Lacro59** [comment]
Is this issue specific with this game?
I've not this issue with my xbox games.

**Comment by Lacro59** [comment]
Do you still have the issue?
