### ISSUE TITLE
Change Success Story to use pluginID instead of source name

### ISSUE THREAD

**Issue by azuravian** [Lacro59/playnite-successstory-plugin#131]
There are issues with SuccessStory working correctly if you ever change the source name for a given game.

As an example, there is a plugin called "Game Pass Browser" by darklinkpower that let's you import games from Xbox Game Pass.  Those games are Xbox games, but have a source of "Xbox Game Pass".  Unless I manually change the source to "Xbox", I cannot see any achievements.

Crow has mentioned to use pluginID instead for this reason.

**Comment by Lacro59** [comment]
If you try the Playnite 9 beta, can you check with the v2.0?
