### ISSUE TITLE
Too eager to refresh achievements

### ISSUE THREAD

**Issue by Jeshibu** [Lacro59/playnite-successstory-plugin#136]
When I press right mouse on a game entry, or hit ... in the details view, achievements are refreshed, or at least some type of web call is done that delays the display of the menu. This is an annoyance, especially since some services can be slow to respond. I would prefer all refreshing be done manually or only after game shutdown, but an option would work too.

This concerns version 2.0 running on Playnite 9 Beta 2

**Comment by Lacro59** [comment]
Achievements are only refreshed automatically when the game is stopped.

However, when starting Playnite, the plugin checks the correct authentication to stores.
Once terminated, there is no latency to open a game menu, normally.
But, I must improve this checks to reduce their impact.
