### ISSUE TITLE
Failed to load properly

### ISSUE THREAD

**Issue by Nukibah** [Lacro59/playnite-successstory-plugin#141]
I get a Playnite notification saying "SuccessStory failed to load properly" using last update (2.0). I also see that text when checking the Settings menu:
![image](https://user-images.githubusercontent.com/90582370/133007197-b305f82d-4875-4fea-9cc3-6e749633dc75.png)

I'm using Playnite's last update and I've got no other plugging installed.

**Comment by Lacro59** [comment]
I can't reproducte this issue.
Can you post your playnite.log?

**Comment by Nukibah** [comment]
Here you are. Thanks for the help!

[playnite.log](https://github.com/Lacro59/playnite-successstory-plugin/files/7154602/playnite.log)

**Comment by Lacro59** [comment]
Can you try with the new version (v2.1)?

**Comment by Lacro59** [comment]
Do you use Playnite 8?
Beacause the versions 2.x are Playnite 9 only. It's in changelog.

**Comment by Nukibah** [comment]
Aagh, that's it, my bad, I was focused on working around issue #142 and I didn't see the changelog, sorry.
