### ISSUE TITLE
Game achievements not showing up

### ISSUE THREAD

**Issue by Nukibah** [Lacro59/playnite-successstory-plugin#142]
I simply installed version 1.4.4 and the extension seems to be finding the games with achievements in my libraries.
![image](https://user-images.githubusercontent.com/90582370/133007444-9558c31b-fd06-4125-87cd-98ad05ee427f.png)
However, no achievement shows in the "View the game achievements" tab display:
![image](https://user-images.githubusercontent.com/90582370/133007505-a71a6e03-c218-46b8-9aff-65c51bf54fd5.png)
Might I be doing something wrong? I tried installing version 2.0, but it didn't load at all.

**Comment by Lacro59** [comment]
Can you post your playnite.log?

**Comment by Nukibah** [comment]
Here you are. Thanks for the help!

[playnite.log](https://github.com/Lacro59/playnite-successstory-plugin/files/7154602/playnite.log)

**Comment by Lacro59** [comment]
Do you use the plugin without Steam API key?
In this case, you must authenticate in Steam library plugin.

**Comment by Nukibah** [comment]
I cannot get the API key as I've always bought my Steam game keys from the videogame's official store or got them for free, so Steam won't allow me using the API key until I make some purchases through the platform.

However, I already tried disabling Steam achievements (I also suspected that might be the cause) but the achievements from other libraries still never showed up.

**Comment by Nukibah** [comment]
Update on this issue: I removed the extension and tried installing it again without checking Steam library. Now I can see just 1 game from GOG while I should be seing 9 (not counting Steam): 
![image](https://user-images.githubusercontent.com/90582370/133896309-ad67e2e5-784a-4b33-9ced-f4c7e2a5c8d9.png)

**Comment by Nukibah** [comment]
Yes, it's working wonderfully with the new release,, thanks for the help!
