### ISSUE TITLE
Add the percentage unlocked as one of the "Plugin data for game selected"

### ISSUE THREAD

**Issue by davidkgriggs** [Lacro59/playnite-successstory-plugin#143]
Can the percentage unlocked be added as one of the "Plugin data for game selected" so I can use it for full screen themes.

Thanks.

**Comment by Lacro59** [comment]
I added new data available: https://github.com/Lacro59/playnite-successstory-plugin/wiki/Addition-in-a-custom-theme
Be wait the next release.
