### ISSUE TITLE
Remove update check, Release 1.4.4 - SDK 5.5.0

### ISSUE THREAD

**Issue by FiyreWyrkz** [Lacro59/playnite-successstory-plugin#154]
As the title says. It would be fantastic to have the update checks removed from v.1.4.4 - so as not to get the notification within client on startup about updating to newer versions that do not support the Playnite 8, 5.5.0 SDK.

That or direction on how to manually remove the update checks if this is any easy process from configs. I apologize as I am honestly not familiar with the Playnite SDK and extension framework. Much appreciated.

**Comment by Lacro59** [comment]
You can do it:
https://playnite.link/forum/thread-275-post-5075.html#pid5075

**Comment by FiyreWyrkz** [comment]
Appreciate the direction. Closed as solved.
