### ISSUE TITLE
Playnite crashes when Achivements window view is opened, change to other window and come back to it

### ISSUE THREAD

**Issue by darklinkpower** [Lacro59/playnite-successstory-plugin#166]
Playnite crashes when Achivements window view is opened, change to other window and come back to it. Sorry for this description but that's how we could reproduce it. Happened with xbox 360 games.

> Happened when I came back to Playnite

![image](https://user-images.githubusercontent.com/1389286/135492836-396319b3-6d14-479e-842d-ace22a8c471d.png)

> yea, same thing. i left it for a while, came back to it and its frozen

![image](https://user-images.githubusercontent.com/1389286/135492865-d7cb3424-5b7d-4e5c-afb6-634cd2941c2f.png)

**Comment by XenorPLxx** [comment]
For me it doesn't crash but it freezes for a long time for every NEW game I open for the first time. If achievement icons were already loaded before, then it works good. Doesn't matter what the platform is, happen for Epic, PSN and Xbox

**Comment by Lacro59** [comment]
Have you tried with the latest versions?

**Comment by darklinkpower** [comment]
It's no longer happening in the latest version
