### ISSUE TITLE
Refreshing achievements for Hades on Epic Games giving an error

### ISSUE THREAD

**Issue by Jhanlon95** [Lacro59/playnite-successstory-plugin#194]
When trying to refresh Hades for Epic Games Achievements it is showing an error. I was able to successfully refresh data for Alan Wake Remastered and could see those achievements within Playnite

Have attached my extensions.log. The error is at the very bottom of the log

[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/7448933/extensions.log)

**Comment by FolkSong** [comment]
I get the same error for Hades on EGS. "Unterminated string... position 4365."

My only other EGS game with achievements is PC Building Simulator and that works fine.
