### ISSUE TITLE
[Bug] Xbox achievement rarity incorrectly shows 100%

### ISSUE THREAD

**Issue by Knicey** [Lacro59/playnite-successstory-plugin#205]
Whenever I refer to "Xbox", I mean games downloaded through the Xbox windows app using PC Gamepass.

Refreshing data seems to overwrite the correct rarity of achievement data.

When I did a global refresh (download plugin data) of my Xbox achievement data, it changed all achievement rarity to 100%
The only games that were not affected by this change were the Xbox games I did not have installed on my PC at the time (I assume this is because the extension ignores games that you don't have installed when you refresh data?)

I am struggling to remember if this issue occurred in the Playnite 8 version of this extension, but I think it did. I remember not really caring about having correct achievement rarity until recently.
Frankly, I have no idea that I had the correct achievement rarity for these uninstalled games until I checked it manually just a few days ago.

When I refreshed the data for one of these uninstalled games (that had the correct rarities), it suddenly broke all the rarities and made them 100%.

I do not believe which it matters specifically what these games were, but I'll leave their names here for the purposes of documentation.
Tales of Vesperia - 
Uninstalled (~October 2nd)
Refreshed data and rarity broke (just a few days ago)

Final Fantasy XIII - 
Uninstalled (I don't remember when, mid-september i think)

**Comment by Lacro59** [comment]
I can't reproducte your issue.
Can you post your extension.log?

**Comment by Knicey** [comment]
I couldn't find a file called extension.log (using the everything application)
Could you tell me where I can find this file?
Also, I just redownloaded all plugin data and got this error
![image](https://user-images.githubusercontent.com/45131167/141649959-d982028a-639d-419b-8b69-39d0110785cd.png)

**Comment by Lacro59** [comment]
If you have Playnite portable, the file is in Playnite directory.
If you have the normal installation, the fileis in %AppData%\Playnite.

**Comment by Knicey** [comment]
Found it 👍 
[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/7532331/extensions.log)

**Comment by Knicey** [comment]
Something I noticed just reading through the document
It looks like the achievement list is offset by 1
![image](https://user-images.githubusercontent.com/45131167/141650595-bcfa8b8b-a3a3-45bd-a770-62fcb21aafdf.png)
I've boxed the achievements that I know to be connected to the game above
This also happens to Octopath Traveler on lines 2853-2940
This happens in every instance I can recognize the achievement names

**Comment by Lacro59** [comment]
This log warn that no correspondence with Exophase to set rarity percent.

**Comment by Knicey** [comment]
oops, I did not mean to push that button

**Comment by Knicey** [comment]
I just restarted my Playnite client and individually refreshing data seems to list the correct rarity for achievements

**Comment by Knicey** [comment]
https://youtu.be/iLdyziL0EWs
So I'm pretty sure the glitch is caused by trying to refresh games in quick succession

**Comment by Knicey** [comment]
Here's my new extension file
[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/7532607/extensions.log)

**Comment by Lacro59** [comment]
fixed with the next release
