### ISSUE TITLE
SuccessStory makes my Playnite freeze and eventually crash

### ISSUE THREAD

**Issue by XenorPLxx** [Lacro59/playnite-successstory-plugin#207]
As seen in the video - when I browse through my library using a theme that displays achievements Playnite eventually freezes. I can wait for a few minutes until it unfreezes, but if I try to go to the menu, it crashes.
If I disable SuccessStory, everything works fine.

[Freeze video](https://www.youtube.com/watch?v=Ii74HWMlydU)
There are 3 attempts in the video - 1st froze literally on the first game after starting recording, second is with SuccessStory disabled - no freezes, and third froze after exploring a few games.

[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/7496489/extensions.log)

First time it froze on PS5 game, GameId: `PPSA01750_00`
Second time it froze on Steam game, GameId: `845070`

I think I've noticed it happening first time on the Wednesday evening, 3.11.2021.

**Comment by Lacro59** [comment]
Have you tried with the latest versions?
