### ISSUE TITLE
Achievements far in the past (1753) freeze Playnite when switching to a game

### ISSUE THREAD

**Issue by Jeshibu** [Lacro59/playnite-successstory-plugin#208]
Xbox 360 achievements gained while offline are dated 1753-1-1. Switching to a game with at least one 1753 achievement will freeze Playnite for a long time (eventually unfreezing), I assume this is to render the graph. This also happens when opening the achievement window, I assume to also render the graph there.

**Comment by Lacro59** [comment]
Can you post an screenshot with an example?

**Comment by Jeshibu** [comment]
![image](https://user-images.githubusercontent.com/37979717/144322628-92550dfc-975a-4b56-a16e-ccb53bc264da.png)
