### ISSUE TITLE
[Bug] Epic Achievements not Counting in SuccessStory

### ISSUE THREAD

**Issue by TheDenunci** [Lacro59/playnite-successstory-plugin#209]
Problem: Epic achievements are not being loaded into the SuccessStory achievement list. Epic Achievements are also being listed as 178/228 even though I re-downloaded achievement data for all games, and not just Recently Added or Installed. Specific game being played is Kena Bridge of Spirits.

Playnite Version: 9.6
SuccessStory Version: 2.4 (updated to latest)
Windows 
![Playnite DesktopApp_4z5NHaU62P](https://user-images.githubusercontent.com/93968404/140875785-5f12b60a-db54-4e52-83dd-02a62c5c86c0.png)
![firefox_aw14zmmDlF](https://user-images.githubusercontent.com/93968404/140875788-6d3a6982-126b-4929-9e0a-7262d1e42bd5.png)
![Playnite DesktopApp_1qe3QpqMD5](https://user-images.githubusercontent.com/93968404/140875792-7e3af67a-ac1a-4278-a013-50bd49edaeb1.png)
1
[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/7502574/extensions.log)
0

**Comment by Lacro59** [comment]
Can you try with the last release?

**Comment by TheDenunci** [comment]
I updated to 2.5.1, then tried right clicking the game -> Success Story -> Refresh data and it still lists 0/41 in my achievements for this specific game.

**Comment by Lacro59** [comment]
Are you authenticated in the Epic Library plugin?

**Comment by awbooze** [comment]
If this helps, I'm also experiencing this issue with Epic Achievements using both SuccessStory 2.4 and 2.5.1 on Playnite 9.6 while authenticated to Epic via Playnite. If I refresh the data for _Rocket League_, for instance, it shows that I have zero out of 88 achievements, despite that when I clicking the source link, it shows my actual achievements in my browser. 

I thought of two hypotheses for this behavior:
- Local language needs to include the market or country as well. I noticed that when clicking the source link for _Rocket League_ in SuccessStory, it sends me to https://www.epicgames.com/store/en/achievements/rocket-league, which then redirects to https://www.epicgames.com/store/en-US/achievements/rocket-league. If the `WebViewOffscreen.NavigateAndWait(Url)` call doesn't redirect, that could be an issue. However, it's still downloading the achievement list, so I don't think that's the problem.
- The WebView isn't logging the user in correctly. When I'm on the [_Rocket League_ Achievements page](https://www.epicgames.com/store/en-US/achievements/rocket-league) while I am logged out, it still lists the achievements. Additionally, if you `curl https://www.epicgames.com/store/en-US/achievements/rocket-league` it will grab the page which has a list of `achievements`, but no list of `playerAchievements`. I think this is more likely.

I wanted to test logging into Epic again like you have us re-authenticate into Steam, but it looks like Epic is using hCaptcha now, which is a pain to fill out and was resulting in error text reading "Incorrect response. Please refresh the page." even if I selected the correct images, so I wasn't able to test that.

**Comment by awbooze** [comment]
The Epic Store Library Integration was updated to version 2.6 today, which reworked the authentication system. After re-authenticating with version 2.6, it did not fix the issue.

**Comment by drnooooo** [comment]
Am also having this problem.

**Comment by TheDenunci** [comment]
> Are you authenticated in the Epic Library plugin?

Yes, I am. I tried re-doing the authentication multiple times as well.

**Comment by Lacro59** [comment]
Can you try with the last release?

**Comment by awbooze** [comment]
I can confirm that v2.6 of SuccessStory is working for me on the Epic copies of _Rocket League_ and _Hades_. Thanks for your work!

**Comment by drnooooo** [comment]
Can also confirm the new version works for me in Hades. Thank you!

**Comment by TheDenunci** [comment]
I can confirm that it works now as of the latest version. Achievements are loading properly for Kena Bridge of Spirits. 
![image](https://user-images.githubusercontent.com/93968404/144428158-a40811fb-b14d-491c-b2e8-99dc26143eda.png)
