### ISSUE TITLE
Extension failed to load properly

### ISSUE THREAD

**Issue by lilsickdude** [Lacro59/playnite-successstory-plugin#213]
When i go to the Playnite Settings>Extensions>Generic, Playnite give me this error
"Extension failed to load properly"
![y3nt5HvaVQ](https://user-images.githubusercontent.com/64420285/141700669-56b5c0f5-3926-4f68-92ee-4ccb524abd90.png)

**Comment by Lacro59** [comment]
Can you post your playnite.log and extension.log?
