### ISSUE TITLE
export statistics

### ISSUE THREAD

**Issue by Lacro59** [Lacro59/playnite-successstory-plugin#22]
from sheepbeep [(https://playnite.link/forum/thread-275-post-998.html#pid998)](https://playnite.link/forum/thread-275-post-998.html#pid998)

export total statistics to CSV (by month and tabulated by platform)

**Comment by jose-l-martins** [comment]
Hi. It would be nice if the plugin was able to export a "backup" of all the current unlocked achievements (icons, names, descriptions...) to a CSV or HTML format, for offline archival purposes. Thanks.
