### ISSUE TITLE
[Bug] Can't open SuccessStory settings

### ISSUE THREAD

**Issue by Jhanlon95** [Lacro59/playnite-successstory-plugin#221]
Have just updated to the latest version (2.5). When trying to view SuccessStory settings within the Add-on menu I am given a "Failed to load settings"

![image](https://user-images.githubusercontent.com/11045596/142775247-9c533c5c-9ae5-4c49-a403-c0cc88b62a16.png)

**Comment by DivineBladeofDarkness** [comment]
Same here, setting is failing to load

**Comment by Lacro59** [comment]
Can you post your extension.log?

**Comment by Jhanlon95** [comment]
This is my extension.log

[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/7577020/extensions.log)

**Comment by Lacro59** [comment]
fixed
