### ISSUE TITLE
Unexpected character encountered while parsing value: G. Path ''

### ISSUE THREAD

**Issue by alpe12** [Lacro59/playnite-successstory-plugin#222]
I updated all my achievements because of the last update.
And I got this error.
[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/7577098/extensions.log)

**Comment by Lacro59** [comment]
Can you try with the last release?

**Comment by alpe12** [comment]
That error is now gone, thanks.
But I got a few ```
|ERROR|SuccessStory#Common:Error on <GetSelectData>b__2()|D:\GitHub\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryDatabase.cs|1291
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized)
```
[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/7696221/extensions.log)
Might be unrelated though.
