### ISSUE TITLE
Xbox Achievements showing the wrong percentage

### ISSUE THREAD

**Issue by joesp97** [Lacro59/playnite-successstory-plugin#223]
The bug comes up after updating to 2.5.1
![image](https://user-images.githubusercontent.com/9094451/142838774-da088bb5-6bc6-4f39-b4eb-b39c917eb4a3.png)

**Comment by Lacro59** [comment]
Can you try this version and post your extension.log after a refresh?
[playnite-successstory-plugin.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/7589443/playnite-successstory-plugin.zip)

**Comment by joesp97** [comment]
[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/7599250/extensions.log)

**Comment by Lacro59** [comment]
Can you try this version?
[playnite-successstory-plugin.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/7603143/playnite-successstory-plugin.zip)

**Comment by joesp97** [comment]
> Can you try this version? [playnite-successstory-plugin.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/7603143/playnite-successstory-plugin.zip)

That works
![image](https://user-images.githubusercontent.com/9094451/143492772-f1fe8733-0db4-4bd2-8044-deabe20679b3.png)
