### ISSUE TITLE
Plugin creates CEF subprocesses that never close and use a lot of resources

### ISSUE THREAD

**Issue by darklinkpower** [Lacro59/playnite-successstory-plugin#224]
Can be replicated with game [Deep Rock Galactic](https://store.steampowered.com/app/548430/Deep_Rock_Galactic/) from Steam
SuccessStory creates 2 CEF subprocesses. I've waited a lot of time and they never go away or close

- 3 CEF subprocesses start using CPU usage. 2 of them use up to 5% CPU, while another uses up to 60% at times
- 1 subprocess uses all available internet bandwidth and never goes away

Before closing game:
![image](https://user-images.githubusercontent.com/1389286/142989443-0feea4bc-67c7-4279-b526-b061d6219f61.png)

After closing game:
![image](https://user-images.githubusercontent.com/1389286/142988157-959bea4e-815f-495b-a8a5-961f12b726ea.png)

Extensions log
```
23-11 01:38:49.298|INFO |SuccessStory#PluginDatabaseObject`3:RefreshNoLoader(Deep Rock Galactic - 6892627f-3fdb-4992-a13e-04be63643eae)
23-11 01:38:49.298|WARN |SuccessStory#PluginDatabaseObject`3:Used SuccessStory.Clients.SteamAchievements for Deep Rock Galactic - 6892627f-3fdb-4992-a13e-04be63643eae
23-11 01:38:54.761|WARN |SuccessStory#GenericAchievements:No Exophase (description) matching achievements found for Deep Rock Galactic - 6892627f-3fdb-4992-a13e-04be63643eae - Now We Have A BET-C in https://www.exophase.com/game/deep-rock-galactic-steam/achievements/
23-11 01:38:57.534|INFO |SuccessStory#PluginDatabaseObject`3:Find 69 achievements find for Deep Rock Galactic - 6892627f-3fdb-4992-a13e-04be63643eae
```

**Comment by darklinkpower** [comment]
Plugin settings

![image](https://user-images.githubusercontent.com/1389286/142990721-b6756589-f7bc-493e-9d58-d9954114e96c.png)

![image](https://user-images.githubusercontent.com/1389286/142990738-74952baa-cd8a-4ce2-b1e9-d044dcf6584c.png)

![image](https://user-images.githubusercontent.com/1389286/142990756-eae37b29-7cf7-4db6-b215-da5531ffeb34.png)

![image](https://user-images.githubusercontent.com/1389286/142990767-2dfba3bb-0238-460f-bd5f-a5fea304bd37.png)

**Comment by Lacro59** [comment]
Can you try with the last release?

**Comment by darklinkpower** [comment]
Seems to be fixed, I'll be monitoring to further confirm this

**Comment by Lacro59** [comment]
Can you check with the last release?
Thanks.

**Comment by darklinkpower** [comment]
I gave it a check and it seems it's resolved. If something comes up I'll let you know
