### ISSUE TITLE
Exophase Blizzard games achievements not Syncing

### ISSUE THREAD

**Issue by Darakah** [Lacro59/playnite-successstory-plugin#226]
Hello,

Thank you for the amazing work, really love this plugin!

![Screenshot 2021-11-30 190532](https://user-images.githubusercontent.com/29651407/144103264-6fa02a98-de1d-4c87-aba2-59d1b4c07840.png)

**Problem**:  Blizzard games such as world of warcraft and starcraft achievements do not sync properly with the linked and authenticated Exophase account. Achievement stats and completion status appear correctly on the Exophase profile page however the extension only retrieves the achievements without the user info (also achievement images are not retrieved, source is correct and directs to the proper Exophase  page). 

- I have authenticated the Exophase account from the addon settings tab and made sure I am logging in with the proper credentials.
- No warning appears when game achievements are added
- I have attempted to remove and then add again the game however the outcome is always the same
- After adding the achievements: Right click -> SuccessStory -> Edit -> Causes the error box below

![Screenshot 2021-11-30 191138](https://user-images.githubusercontent.com/29651407/144104302-1db41dfa-4bc7-49b1-9f4c-ae29bfb25055.png)

Is it because there are too many? 

Thanks again for the great plugin!

**Comment by Lacro59** [comment]
Can you post your extension.log?

**Comment by Darakah** [comment]
extension.log file: [extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/7627966/extensions.log)

I removed the extension file and then: 
- removed achievements from starcraft -> added it using "Add"
- removed achievements from wow -> added it using "Add" option -> edit for it to crash

Though this time instead of getting the "Edit" option for starcraft there was refresh and when I clicked it it synched properly. However the same did no happen for wow it remains as is.

**Comment by Darakah** [comment]
Not sure if this can help as well, 
I created my Exophase account **today** and then shortly after synced the blizzard games.

**Comment by Lacro59** [comment]
Authentication on Exophase is only to have localized achievements and to have the right match for rarity if your language is not English.
however there is this: #227

**Comment by Darakah** [comment]
Thank you for the help and the amazing work!
Feel free to close this issue!

**Comment by Lacro59** [comment]
Can you post your playnite.log?

**Comment by Darakah** [comment]
[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/7637659/extensions.log)
[playnite.log](https://github.com/Lacro59/playnite-successstory-plugin/files/7637661/playnite.log)

I installed the 2 recent versions of the plugin though the problem still remains with Wow (same as above, no achievements retrieved and no images).

**Comment by Darakah** [comment]
Nevermind, I am mentally challenged.
I found the new settings opttion to enable the wow achievements. It works perfectly now!!

Thanks so much! Amazing work!
