### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by burnpsy** [Lacro59/playnite-successstory-plugin#235]
For the past while Success Story has been intermittently giving me an "object reference not set to an instance of an object" error when starting Playnite, after my libraries are checked at startup.

Clicking on the error had Playnite generate [this log package](https://github.com/Lacro59/playnite-successstory-plugin/files/7656954/SuccessStory_2021-12-05.zip).

**Comment by xii7** [comment]
I'm also getting this error.

[SuccessStory_2021-12-06.zip](https://github.com/Lacro59/playnite-successstory
[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/7659776/extensions.log)
-plugin/files/7659772/SuccessStory_2021-12-06.zip)
r

**Comment by Carighan** [comment]
Same for me. Adding 
[my log package](https://github.com/Lacro59/playnite-successstory-plugin/files/7673785/SuccessStory_2021-12-08.zip), hth.

**Comment by demonstrable** [comment]
I am also getting this error. I have attached my log package.
[SuccessStory_2021-12-09.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/7689274/SuccessStory_2021-12-09.zip)
.

**Comment by Kyzoku** [comment]
I'm getting this error message.

[SuccessStory_2024-09-06.zip](https://github.com/user-attachments/files/16910934/SuccessStory_2024-09-06.zip)
