### ISSUE TITLE
Manual Achievements: two issues

### ISSUE THREAD

**Issue by Driesmann** [Lacro59/playnite-successstory-plugin#244]
First, I cannot remove existing lists with achievements. AC Valhalla got two new achievements since I last played it, but I cannot remove the current list in order to download a new one. I am still able to edit though.

Second, I cannot add new achievements lists at all, it gives the "nullable object must have value" which I've had before already. 

[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/7781327/extensions.log)
[playnite.log](https://github.com/Lacro59/playnite-successstory-plugin/files/7781328/playnite.log)

**Comment by Lacro59** [comment]
> First, I cannot remove existing lists with achievements. AC Valhalla got two new achievements since I last played it, but I cannot remove the current list in order to download a new one. I am still able to edit though.
Do you want to be able to update the existing list?
Do you have issue to remove the existing list to update after?

**Comment by Driesmann** [comment]
I want to update the existing list, yes, but cannot remove the current one. Of no game where I added manual achievements can I do this.

**Comment by Driesmann** [comment]
Hi, was the update supposed to fix both issues? If it was, just letting you know both still persists and I'm attaching the logs again.
If it wasn't, you can just ignore this message :)

[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/7799151/extensions.log)
[playnite.log](https://github.com/Lacro59/playnite-successstory-plugin/files/7799152/playnite.log)
