### ISSUE TITLE
Bug: All RPCS3 trophies are Bronze

### ISSUE THREAD

**Issue by thundercatsNZ** [Lacro59/playnite-successstory-plugin#251]
All of the RPCS3 trophiesare being created as Bronze trophies, instead of the correct color. I have attached a screenshot slowing a game with 100% trophies so you can see what I mean:

![Screenshot 2022-01-05 182238](https://user-images.githubusercontent.com/25402358/148268958-0c965898-f048-44b1-9a88-b52bce65d9a5.png)

Assume you are loading the data in from TROPCONF.SFM? If so the "ttype" attribute has the correct values to use.

Thanks!

**Comment by Lacro59** [comment]
Fixed with the next release but you must do a refresh.

**Comment by thundercatsNZ** [comment]
Cool, I'll test the new release and let you know if there are any further issues.Thanks again for your work on this plugin! 😊
