### ISSUE TITLE
Enhancement Request: Steam web authentication issues

### ISSUE THREAD

**Issue by chocolatechipcats** [Lacro59/playnite-successstory-plugin#263]
I have a private Steam account and I've been hit with frequent Steam authentication errors again. Re-authenticating from the Steam plugin works but it comes back after a day or two. 

The Steam plugin is still reporting that the authentication is valid, so I am guessing that SuccessStory is either expiring quicker or not renewing an existing session.

If a log would be of help I can provide one.

**Comment by Lacro59** [comment]
Can you try with the last release?

**Comment by chocolatechipcats** [comment]
It's stopped giving me authentication errors, but now it is just silently failing to fetch new achievements at all. :( I re-authenticated but that didn't fix it. 

Using 'Download data' gave me an error, attached the log.  [SuccessStory_2022-01-28.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/7955739/SuccessStory_2022-01-28.zip)

**Comment by OsoaGH** [comment]
I am having the same issue, can give a log if needed

**Comment by chocolatechipcats** [comment]
Would like to confirm that new achivevements are still not being fetched with 2.9.1. :(

**Comment by IceBeach7** [comment]
Same for me

**Comment by Lacro59** [comment]
Can you post your extension.log?

**Comment by chocolatechipcats** [comment]
Here's a log of me trying to manually refresh data on three games and then using "download plugin data" on recently played games (which gave an error)

[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/8089149/extensions.log)
[SuccessStory_2022-02-17.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/8089150/SuccessStory_2022-02-17.zip)

**Comment by IceBeach7** [comment]
For me it outputs this error (`SuccessStory#GenericAchievements:Steam user is not authenticated`) in the log.
When I reauthenticate with Steam it will work for a few days.

**Comment by chocolatechipcats** [comment]
As of the newest version, it is downloading the achievements again. :) I'll post again in a day or two about whether the authentication expires.

**Comment by IceBeach7** [comment]
Still not working on the latest update.

**Comment by chocolatechipcats** [comment]
Authentication expired. This time it just silently deleted all the achievements upon failure. Re-authenticating restored them.

**Comment by IceBeach7** [comment]
Same behavior for me

**Comment by chocolatechipcats** [comment]
Further update: Silently deleting achievements only happens when the sync is manually triggered. The automatic one that comes after a game is shut down will give an error and not delete.

**Comment by OsoaGH** [comment]
@Lacro59 sorry for ping but do you have any updates on this? it ruins the addon for me personally as most of my games are on steam

**Comment by Lacro59** [comment]
@OsoaGH I must rewrite the plugin api for Steam. Be wait.

**Comment by OsoaGH** [comment]
I'm not having this issue anymore. Maybe a server-side change from Steam? What about others?

**Comment by chocolatechipcats** [comment]
Unfortunately, I'm still getting it.

_However_, I've noticed that if the Steam authentication popup has the "remember user" option, that will prevent it for quite a while. Unfortunately, I've only gotten that option to appear once or twice, and am not sure why.

**Comment by MeatSafeMurderer** [comment]
I get the authentication issue quite literally every day. I can reauthenticate but within a day it's right back to refusing to sync. It's making it basically useless for tracking Steam achievements.

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-successstory-plugin/commit/c28ea8d148b8ff36060f4ee4fb2dab809e0cff52
