### ISSUE TITLE
When downloading detects as trojan

### ISSUE THREAD

**Issue by Aleorhon** [Lacro59/playnite-successstory-plugin#267]
When I download it detects the file as a trojan

**Comment by Lacro59** [comment]
What antivirus?
Where do you download the plugin? Github? From Playnite?

**Comment by mearl72** [comment]
yeah I'm getting the same thing. it's from Windows Defender. Here are some screenshots.
![download](https://user-images.githubusercontent.com/52020227/152685218-c07de45a-91d7-4436-a127-6a60de9ac05c.png)
![notification](https://user-images.githubusercontent.com/52020227/152685222-9447a242-5c8a-476a-a818-4fac8b4da5ef.png)
![Windows Security](https://user-images.githubusercontent.com/52020227/152685227-7234a439-55f3-4ad5-b31c-59d29950bb71.png)

**Comment by Lacro59** [comment]
I have the same problem with all versions of the plugin since v2.0 when I've dowlonad from GitHub... :(

**Comment by Lacro59** [comment]
> It looks like this only happens when downloading it from GitHub. I was able to download it through the Add-ons window in Playnite

Are you tried to scan the extension folder of Playnite with Windows Defender?

**Comment by mearl72** [comment]
> > It looks like this only happens when downloading it from GitHub. I was able to download it through the Add-ons window in Playnite
> 
> Are you tried to scan the extension folder of Playnite with Windows Defender?

I actually have my folder excluded from the AV so it’s possible it might still get seen by Defender if it wasn’t.

**Comment by Lacro59** [comment]
> I actually have my folder excluded from the AV so it’s possible it might still get seen by Defender if it wasn’t.

Why do you have exclude the folder?

**Comment by mearl72** [comment]
> Why do you have exclude the folder?

I’m using the portable Playnite and I just put it in a folder that I happen to already have excluded.

**Comment by Lacro59** [comment]
> > Why do you have exclude the folder?
> 
> I’m using the portable Playnite and I just put it in a folder that I happen to already have excluded.

Can you test a manual scan on Playnite folder?

**Comment by mearl72** [comment]
> Can you test a manual scan on Playnite folder?

Had to move the Playnite folder out of the excluded directory but I was able to scan it and no threats were found. I even tried removing it and redownloading it through the Add-ons window. Still worked fine. Weird. It seems to have an issue with SuccessStory.dll for the .pext file when downloading from GitHub but it didn't see it as an issue from the one downloaded through Playnite.

**Comment by goldmojo** [comment]
Same here, version 2.9.1 is detected as a trojan by windows defender.
