### ISSUE TITLE
RetroAchievements heavily reliant on filetypes? (no .7z support for SNES games)

### ISSUE THREAD

**Issue by NatParable** [Lacro59/playnite-successstory-plugin#268]
I have my SNES games in 7z files because it helps to save on space. These 7z files can be easily read by emulators like RetroArch no problem.

However, it seems that this is stopping SuccessStory from detecting these games. If a SNES game is linked to a .7z file, SS won't find achievements. But if the exact same SNES game is pointing to an .sfc file instead, SS detects it easily. Strangely enough i've had no problem with SS detecting my Sega Genesis games, which are also in the form of .7z files.

I really don't understand why this would affect SS's functionality. If a game is named "Mario Paint" and has the platform "Nintendo SNES", surely that should be enough for SS to detect it regardless of the state of the file?

I'm also starting to wonder if this may be related to the reason why my PSP games (.iso) are never detected by SS either.

**Comment by Lacro59** [comment]
Normally the name of the game and the platform are sufficient.
Can you post your extension.log after to try to refresh achievements for game with the issue?

**Comment by NatParable** [comment]
Ok, for some reason I can't attach my extension.log, so here's a copy paste of what happens when I try to refresh a SNES game that uses a 7z file.

`18-02 21:29:17.932|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(Super Mario World - 0a888d7c-402d-4e1f-866c-4264ea5c3a27)
18-02 21:29:17.932|WARN |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.RetroAchievements for Super Mario World - 0a888d7c-402d-4e1f-866c-4264ea5c3a27
18-02 21:29:18.258|WARN |SuccessStory#GenericAchievements:No game find for Super Mario World with 18265da8b39d145fea99680d347c9521 in PlatformType.All
18-02 21:29:18.269|WARN |SuccessStory#GenericAchievements:No game find for Super Mario World with ef43b8ef2b0bad0f0b8cee7c220cd2df in PlatformType.SNES
18-02 21:29:18.294|WARN |SuccessStory#GenericAchievements:No game find for Super Mario World with 18265da8b39d145fea99680d347c9521 in PlatformType.SNES
18-02 21:29:18.308|WARN |SuccessStory#GenericAchievements:No game find for Super Mario World with cb57c0e998748f3b542e9e0d5faacd7d in PlatformType.Sega_CD_Saturn
18-02 21:29:18.335|WARN |SuccessStory#GenericAchievements:No game find for Super Mario World with 18265da8b39d145fea99680d347c9521 in PlatformType.SNES
18-02 21:29:18.335|WARN |SuccessStory#GenericAchievements:No game find for Super Mario World with b31e1500a2b3ccf2268394fd7d158787 in PlatformType.Sega_CD_Saturn
18-02 21:29:18.348|WARN |SuccessStory#GenericAchievements:No console find for Super Mario World with Nintendo SNES
18-02 21:29:18.348|WARN |SuccessStory#GenericAchievements:No game find for Super Mario World with Nintendo SNES in 0
18-02 21:29:18.348|INFO |SuccessStory#PluginDatabaseObject`4:No achievements find for Super Mario World - 0a888d7c-402d-4e1f-866c-4264ea5c3a27`

**Comment by NatParable** [comment]
Also, just in case this is somehow related, this is what happens when I try to get achievements for my PSP games.

> 19-02 20:57:02.591|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(Pangya: Fantasy Golf - 8d58f2d9-3812-40a2-b869-a8be2ce9638f)
> 19-02 20:57:02.591|WARN |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.RetroAchievements for Pangya: Fantasy Golf - 8d58f2d9-3812-40a2-b869-a8be2ce9638f
> 19-02 20:57:02.630|WARN |SuccessStory#GenericAchievements:Hash impossible - The file is too long - C:\Users\Nathan\Games\PSP\\Pangya - Fantasy Golf (USA).iso
> 19-02 20:57:02.637|WARN |SuccessStory#GenericAchievements:No console find for Pangya: Fantasy Golf with Sony PlayStation Portable
> 19-02 20:57:02.637|WARN |SuccessStory#GenericAchievements:No game find for Pangya: Fantasy Golf with Sony PlayStation Portable in 0
> 19-02 20:57:02.637|INFO |SuccessStory#PluginDatabaseObject`4:No achievements find for Pangya: Fantasy Golf - 8d58f2d9-3812-40a2-b869-a8be2ce9638f
