### ISSUE TITLE
Missing Genshin Impact achievements after enabling and disabling new option

### ISSUE THREAD

**Issue by Krylan** [Lacro59/playnite-successstory-plugin#274]
I noticed in SuccessStory, that there is new option: "Enable Genshin Impact achievements" (I guess these should be in-game achievements). I enabled that, but after refreshing data on this game, not only didn't get anything new, but my achievement data from PSN disappeared.
I was enlightened, that these would work with PC version of the game, not PS4, but now, even if I disable this option and try to refresh data, I can't get back my PSN achievements for this particular game.
I re-authenticated for PSN, but refreshing data still changes nothing. I also don't get any notifications about that.

In extensions.log file after refreshing data from selected PSN games I got this:
```
23-02 20:20:39.529|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(Genshin Impact - 6c5f23a2-3768-4e40-a24f-0a15c97550a7)
23-02 20:20:39.596|INFO |SuccessStory#PluginDatabaseObject`4:No achievements find for Genshin Impact - 6c5f23a2-3768-4e40-a24f-0a15c97550a7
23-02 20:20:45.975|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(KINGDOM HEARTS - HD 1 5+2 5 ReMIX - - 62544051-38b1-4473-95bf-6f753e1d355f)
23-02 20:20:48.676|WARN |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.PSNAchievements for KINGDOM HEARTS - HD 1 5+2 5 ReMIX - - 62544051-38b1-4473-95bf-6f753e1d355f
23-02 20:20:50.818|WARN |SuccessStory#TrueAchievements:No url for GetEstimateTimeToUnlock()
23-02 20:20:51.478|INFO |SuccessStory#PluginDatabaseObject`4:Find 48 achievements find for KINGDOM HEARTS - HD 1 5+2 5 ReMIX - - 62544051-38b1-4473-95bf-6f753e1d355f
```
So it looks like after enabling and then disabling the option, it can't find the achievements for "Genshin Impact" anymore.

**Comment by Lacro59** [comment]
Have you tried with the latest version?

**Comment by Krylan** [comment]
@Lacro59 On latest version, when I check "Enable Genshin Impact achievements", then refreshing data gets all in-game achievements (which is 653 at the moment). They are not checked, which ones I obtained (it works for PC version, or it's manual-edit only?).
However still, when I disable this option, PS4 achievements for this game are not getting downloaded.
