### ISSUE TITLE
Achievements not being found for game on Epic

### ISSUE THREAD

**Issue by Jhanlon95** [Lacro59/playnite-successstory-plugin#287]
I bought Astalon -Tears of the Earth- on Epic Games, after it's been imported into Playnite it's showing that it does not have achievements, however it does have them as I can see them within the launcher and on the "My Achievements" section of my account

```
02-04 15:16:20.446|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(Astalon -Tears of the Earth- - dbf145e9-3221-46a7-b002-50dd87543fb1)
02-04 15:16:20.917|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.EpicAchievements for Astalon -Tears of the Earth- - dbf145e9-3221-46a7-b002-50dd87543fb1
02-04 15:16:21.432|WARN |SuccessStory#GenericAchievements:No ProductSlug for Astalon -Tears of the Earth-
02-04 15:16:21.432|WARN |SuccessStory#GenericAchievements:No ProductSlug for Astalon -Tears of the Earth-
02-04 15:16:21.432|INFO |SuccessStory#PluginDatabaseObject`4:No achievements find for Astalon -Tears of the Earth- - dbf145e9-3221-46a7-b002-50dd87543fb1
```

Image showing that they do show up

![image](https://user-images.githubusercontent.com/11045596/161387430-2ea96871-030b-4fe3-8ee6-d4e21fc0ae18.png)

Other Epic games achievements are able to be found such as Zombie Army 4:

```
02-04 15:17:44.371|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(Zombie Army 4 Dead War - 135f4767-5410-4a10-a793-fa27f219e793)
02-04 15:17:44.371|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.EpicAchievements for Zombie Army 4 Dead War - 135f4767-5410-4a10-a793-fa27f219e793
02-04 15:17:47.895|WARN |SuccessStory#TrueAchievements:No url for GetEstimateTimeToUnlock()
02-04 15:17:48.632|INFO |SuccessStory#PluginDatabaseObject`4:Find 66 achievements find for Zombie Army 4 Dead War - 135f4767-5410-4a10-a793-fa27f219e793
02-04 15:17:48.701|WARN |SuccessStory#TrueAchievements:No url for GetEstimateTimeToUnlock()
```

**Comment by Jhanlon95** [comment]
I tried unlocking some achievements and they are still not showing within Playnite

If achievements are found then there should be a tab beside "Description" for "Achievements"

![image](https://user-images.githubusercontent.com/11045596/161956575-803f1e8e-ac2e-49a0-b9c3-0832a923df3e.png)

**Comment by sharkusmanch** [comment]
Happening to me as well in `Kena: Bridge of Spirits`

**Comment by Jhanlon95** [comment]
I believe I've discovered the reason that this is happening. Within the code you're looking for a "productSlug" which usually is just the name of the game. However, when querying Epic Games API for some games the "productSlug" is null, I'm not sure why this happens. I believe this is what is causing the issue. It is possible to query achievements using a "sandboxId" but I'm not entirely sure how to get that from what SuccessStories gets currently

**Comment by Jhanlon95** [comment]
A possible solution that I have investigated is when checking the query that the Epic Games Store itself runs (done by using firefox dev tools and inspecting the network), the graphql that is being ran actually contains an object within the json called "catalogNs", within this there's a pageSlug which is actually being used for the URL. 

It appears that when productSlug is null that it falls back to using pageSlug. I'm unsure of what response data that Playnite gets 
from the query they run, but if it's similar to the one that's ran on the store itself then it should have access to this variable

**Comment by Jhanlon95** [comment]
I was able to fix this by altering the query being searched within the code to include "catalogNs" which has the pageSlug variable. 

[SuccessStory changes](https://github.com/Jhanlon95/playnite-successstory-plugin/commit/092f0f1abdd394812f273b768589fb3483102961)
[playnite-plugincommon changes ](https://github.com/Jhanlon95/playnite-plugincommon/commit/9e7b8c6512a80390b460b7a5a8f76369091c1c98)

With these changes I was able to find the achievements for Astalon no problem

**Comment by TheDarkSpock** [comment]
I am having an issue where Success Story has found achievements for games, such as Grindstone, but it does not unlock/sync any of the achievements with Playnite, once they've been upclocked within the Game/Epic

**Comment by Jhanlon95** [comment]
Ignore my last message, I closed Playnite and reopened it and then refreshed and now they are coming through. I'm happy for this to be closed

**Comment by TheDarkSpock** [comment]
This issue has not been fixed for me with Grindstone, even after update.

**Comment by Jhanlon95** [comment]
@TheDarkSpock is the issue only happening on Grindstone, or does it happen with other Epic Achievement games that you have? Could you also ensure that you're privacy settings on your achievements page is set to "Public"? Don't think that should cause any issues but would like to double check

**Comment by TheDarkSpock** [comment]
It appears to be happening with Disco Elysium, I can also try downloading a couple other games to try, but so far it doesn't seem to be importing any achievements from Epic for me. I set my achievements page to public, restarted both epic and playnite after updates, and nothing so far.

**Comment by Lacro59** [comment]
Can you try this vcersion?
[playnite-successstory-plugin_2_12.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/8706777/playnite-successstory-plugin_2_12.zip)

**Comment by TheDarkSpock** [comment]
hasn't changed anything

**Comment by Lacro59** [comment]
Can you try this version?
[playnite-successstory-plugin_2_12.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/8764471/playnite-successstory-plugin_2_12.zip)
