### ISSUE TITLE
Percentage bar not filled completely in the left side

### ISSUE THREAD

**Issue by darklinkpower** [Lacro59/playnite-successstory-plugin#3]
Tested with version 0.4a

![imagen](https://user-images.githubusercontent.com/1389286/82915184-0d651480-9f36-11ea-84ec-fbfbedab2e17.png)

**Comment by Lacro59** [comment]
I don't this problem.
Perhaps the theme is the problem.

**Comment by Lacro59** [comment]
With the different versions, your problem is still present?

**Comment by Lacro59** [comment]
no response
