### ISSUE TITLE
Allow to add manual achievements to GOG Library

### ISSUE THREAD

**Issue by WildGenius** [Lacro59/playnite-successstory-plugin#300]
Offline gog installers use the same default installation directory name (`GOG Games`) with Galaxy, yet the games can be launched without using Galaxy, and so without achievements. Currently, your plugin sees that the library is GOG, so it assumes that the game will be launched via galaxy and doesn't allow to add manual achievements.

**Comment by Driesmann** [comment]
+1: also can't add achievements to GOG games that don't have any, it would be nice if we could do that.

**Comment by Lacro59** [comment]
You can already add manual achievements for gog games.
Have you enabled manual achievements in plugin settings?

**Comment by WildGenius** [comment]
Of course. What seems to happen is that once the plugin assigns the "automatic" achievements (ones that would be managed by Galaxy, as the games are installed into the same folder), there is no option to add manual ones, only "View Achievements", "Refresh data", and "Ignore game". If I disable GOG achievements in settings while leaving manual achievements on, there is no SuccessStory in the game's menu at all.
