### ISSUE TITLE
Achievement List for Fullscreen themes (ps5ish)

### ISSUE THREAD

**Issue by BrunoYagami** [Lacro59/playnite-successstory-plugin#304]
suggestion: be able to access a list of achievements through the ps5ish fullscreen theme, similar to what already happens in windowed mode.
A simple list so that we can see the achievements that we have unlocked and which are still to be unlocked, by the ps5ish theme in fullscreen.
mouse.
great work, keep it up.
![ef47a04b-2d3e-4f00-8e8b-b155d65612de](https://user-images.githubusercontent.com/55263547/173457438-cd1da7d9-8029-4307-a939-ef85b549f612.jpg)
![xqf6qtvvc0f61](https://user-images.githubusercontent.com/55263547/173457443-a79f98f7-15d6-455a-9ddb-6e6ecbc6b4d8.jpg)

**Comment by zetalex** [comment]
I second this, because when you open the window of achievements in PS5ish you cannot do anything without using a mouse and that beats the whole reason of having the fullscreen mode instead  of desktop mode.

**Comment by Dukobpa3** [comment]
I Suggest to share IEnumerable<AchievementImage>.

Similar to `ListAchievements` or `EstimateTimeToUnlock `– but it is models, and would be great to get list of prepared ItemViews.

Then many theme makers will be able to make their own implementations of achievements for fullscreen.
They can draw this list like they want to see in the theme (and me too :) )

**Comment by Dukobpa3** [comment]
+1 

I've tried to get them by ListAchievements as described in FAQ but not achieved result.
List is empty, or maybe I've tried some wrong binding.

**Comment by Lacro59** [comment]
In `Main.Xaml` & `GameDetails.xaml`, you can use `ListAchievements` with property taht you find [here](https://github.com/Lacro59/playnite-successstory-plugin/blob/master/source/Models/Achievements.cs).

example:
```
<ItemsControl ItemsSource="{PluginSettings Plugin=SuccessStory, Path=ListAchievements}" >
	<ItemsControl.ItemTemplate>
		<DataTemplate>
			<Grid Margin="0,0,0,5">
				<Grid.ColumnDefinitions>
					<ColumnDefinition Width="*" />
				</Grid.ColumnDefinitions>

				<TextBlock Text="{Binding Name}" />
			</Grid>
		</DataTemplate>
	</ItemsControl.ItemTemplate>
</ItemsControl>
```
