### ISSUE TITLE
Issue with GOG games

### ISSUE THREAD

**Issue by ivanlorusso** [Lacro59/playnite-successstory-plugin#307]
[SuccessStory_2022-06-19.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/8935007/SuccessStory_2022-06-19.zip)
Success story doesn't seem to work with certain GOG games (in my case it's BioShock Remastered).

**Comment by chocolatechipcats** [comment]
Does the game actually have GOG achievements? 

I've noticed that if there isn't, SuccessStory attempts to pull the achievements anyways and fails with an error. 'Ignore game' fixes it.
