### ISSUE TITLE
Error message: Response status code does not indicate success: 401 (Unauthorized)

### ISSUE THREAD

**Issue by adrian5683** [Lacro59/playnite-successstory-plugin#311]
Hi, I'm getting this error message recently every time I open Playnite. I've created the log package and am attaching it here.
[SuccessStory_2022-07-11.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/9084577/SuccessStory_2022-07-11.zip)

**Comment by Lacro59** [comment]
duplicate #307
