### ISSUE TITLE
Cannot import some games from RetroAchievements

### ISSUE THREAD

**Issue by Biel675** [Lacro59/playnite-successstory-plugin#318]
Some games couldn't be imported from RetroAchievements. The list of games is as follows:

- [Nintendo NES](https://retroachievements.org/gameList.php?c=7):
  - [The Legend of Zelda](https://retroachievements.org/game/1454)

- [Nintendo 64](https://retroachievements.org/gameList.php?c=2):
  - [The Legend of Zelda: Ocarina of Time](https://retroachievements.org/game/10113)
  - [The Legend of Zelda: Majora's Mask](https://retroachievements.org/game/10679)

- [Nintendo Game Boy](https://retroachievements.org/gameList.php?c=4):
  - [Pokémon Yellow](https://retroachievements.org/game/723)

- [Nintendo Game Boy Color](https://retroachievements.org/gameList.php?c=6):
  - [Pokémon Gold](https://retroachievements.org/game/576)
  - [Pokémon Silver](https://retroachievements.org/game/722)
  - [Pokémon Crystal](https://retroachievements.org/game/810)
  - [The Legend of Zelda: Link's Awakening DX](https://retroachievements.org/game/5371)
  - [The Legend of Zelda: Oracle of Seasons](https://retroachievements.org/game/676)
  - [The Legend of Zelda: Oracle of Ages](https://retroachievements.org/game/710)

- [Nintendo Game Boy Advance](https://retroachievements.org/gameList.php?c=5):
  - [Pokémon Ruby](https://retroachievements.org/game/790)
  - [Pokémon Sapphire](https://retroachievements.org/game/791)
  - [Pokémon FireRed](https://retroachievements.org/game/515)
  - [The Legend of Zelda: A Link to the Past & Four Swords](https://retroachievements.org/game/580)
  - [The Legend of Zelda: The Minish Cap](https://retroachievements.org/game/559)

- [Nintendo DS](https://retroachievements.org/gameList.php?c=18):
  - [Pokémon HeartGold](https://retroachievements.org/game/7212)
  - [Pokémon SoulSilver](https://retroachievements.org/game/7212)
  - [Pokémon Black](https://retroachievements.org/game/3887)
  - [Pokémon White](https://retroachievements.org/game/16211)
  - [Pokémon White 2](https://retroachievements.org/game/16197)
  - [The Legend of Zelda: Phantom Hourglass](https://retroachievements.org/game/14323)
  - [The Legend of Zelda: Spirit Tracks](https://retroachievements.org/game/9898)

It's weird that games like Pokémon FireRed and Pokémon Black weren't found while Pokémon LeafGreen and Pokémon Platinum were.

**Comment by Lacro59** [comment]
Can you try with the last release?

**Comment by Biel675** [comment]
The same error happens, even when the game has the same name as on RetroAchievements.

**Comment by NoShotz** [comment]
I too am having this issue but with TimeSplitters 2 for PS2. The logs say this.
`15-03 18:38:35.517|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(TimeSplitters 2 - 255a1ce5-16b0-42d8-ae27-6008c61ceba3)
15-03 18:38:35.517|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.RetroAchievements for TimeSplitters 2 - 255a1ce5-16b0-42d8-ae27-6008c61ceba3
15-03 18:38:35.560|WARN |SuccessStory#RetroAchievements:No game find for TimeSplitters 2 with Sony PlayStation 2 in 10
15-03 18:38:35.560|INFO |SuccessStory#PluginDatabaseObject`4:No achievements find for TimeSplitters 2 - 255a1ce5-16b0-42d8-ae27-6008c61ceba3`

**Comment by NoShotz** [comment]
Actually right now, even on games that I already have it displaying retro achievements, refreshing the data gives the same "No game find" and "No achievements find" messages, so maybe their API is having issues currently?

**Comment by NoShotz** [comment]
Yeah, today without any changes the achievements are being imported fine.

**Comment by epeternally** [comment]
Playstation 2 achievements are currently broken for me. Importing from RetroAchievements yields nothing, even if the game name is a perfect match. And as @NoShotz mentioned, even games which have previously imported correctly show "no achievements found" in the log if you refresh the data. However, achievements are recognized correctly if I refresh a game for any other system - so it's not just server issues or something along those lines.

I wish it was possible to manually tie RetroAchievements to a library entry using the page URL, for instances where automatic lookup is malfunctioning.

**Comment by Lacro59** [comment]
RetroAchievements using wrong gamecode #482

**Comment by Lacro59** [comment]
[Feature Request] Manually Set RetroAchievements Game ID #475
