### ISSUE TITLE
EPIC not working

### ISSUE THREAD

**Issue by Rmdhn1** [Lacro59/playnite-successstory-plugin#322]
![image](https://user-images.githubusercontent.com/54092365/188296523-b0fb2391-b4be-4e9c-8431-18f5cbfdfa0b.png)

![Screenshot (823)](https://user-images.githubusercontent.com/54092365/188296503-9c5bc8bb-5bae-4709-82db-7f8c5357edbd.png)

**Comment by Rmdhn1** [comment]
I DON'T KNOW WHAT I DID, BUT IT WORKS, Might be conflict between ISTAD and steam wishlist

**Comment by Rmdhn1** [comment]
wait aminute epic not working

**Comment by Rmdhn1** [comment]
![image](https://user-images.githubusercontent.com/54092365/188298155-ad6b2388-5b3a-4743-a401-56d98af29590.png)
icon for achievements not showin
![image](https://user-images.githubusercontent.com/54092365/188298243-c8d1c11c-0774-40d5-9d1c-ecae57132eb1.png)
what the fuck happened to the icons and images on descriptions?

**Comment by Rmdhn1** [comment]
woops accidentally close

**Comment by Rmdhn1** [comment]
i restarted, metadata icons showing again and for a split second achievements icon also showed but no longer. 
i managed to get achievements icons and description to not be bugged by going into the achievements menu, and then back to library, but if i go to another game or go back to prev game it bugs again, but if i go to achievements menu and back it's fixed again?
https://www.youtube.com/watch?v=mWXsbOPU0wo&ab_channel=Rmdhn

**Comment by Lacro59** [comment]
Can you try with the last release?

**Comment by illogique** [comment]
hello, i don't know if it related but my epic achievement are not refreshing until i re-enter my login.
but the game listing does refresh without relogin.

09-01 14:59:59.955|INFO |SuccessStory#StoreApi:Expired cookies
09-01 15:00:02.992|WARN |SuccessStory#EpicApi:Error 404 for Filament
09-01 15:00:02.992|INFO |SuccessStory#PluginDatabaseObject`4:No achievements find for Filament - 4ebc12ce-5896-476d-a650-6619055a5198

09-01 16:30:12.210|DEBUG|EpicLibrary#EpicLibrary:Found 4 installed Epic games.
09-01 16:30:15.355|DEBUG|EpicLibrary#EpicLibrary:Found 359 library Epic games.

**Comment by illogique** [comment]
relogin on jan 9
working jan 10
10-01 12:20:47.028|INFO |SuccessStory#PluginDatabaseObject`4:Find 29 achievements find for Filament - 4ebc12ce-5896-476d-a650-6619055a5198
not working jan 11
11-01 22:35:04.391|INFO |SuccessStory#StoreApi:Expired cookies

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-successstory-plugin/commit/6e18b787673a605f422aa6dbcd2e6b64ef70cdbd
