### ISSUE TITLE
Duplicate Achievement Name Grabs Incorrect Image

### ISSUE THREAD

**Issue by NicholasHarmer** [Lacro59/playnite-successstory-plugin#323]
I have Destiny 2 and Assassin's Creed Revelations in my Library and they both have an achievement titled "Seal the Deal".

Destiny 2 is using the image from Assassin's Creed Revelations seen here:
![image](https://user-images.githubusercontent.com/38035213/191721997-195ba2b8-d7ba-44d0-8188-282642f1b164.png)
![image](https://user-images.githubusercontent.com/38035213/191722027-bc0a90fa-81d8-4c93-93e6-64ebd555ce0d.png)

This is similar to #122.

**Comment by NoShotz** [comment]
Yeah, I'm getting the same issue with the Jack of all trades achievement from Mass Effect Andromeda and Battlefield 5, both are using the Battlefield 5 images.
