### ISSUE TITLE
Extension doesn't open at all. (script error)

### ISSUE THREAD

**Issue by LuigiVs** [Lacro59/playnite-successstory-plugin#33]
![Annotation 2020-07-01 120118](https://user-images.githubusercontent.com/52753199/86272554-bee21000-bb9c-11ea-8fb3-c7bccfb5c60c.png)
The extension does not open for me at all. Only displays the above message.

**Comment by Lacro59** [comment]
Is it possible to have a extract to **playnite.log**?
This file is in folder _%AppData%\Playnite_ (or in _Playnite_ folder if portable installation).

**Comment by LuigiVs** [comment]
[playnite.log](https://github.com/Lacro59/playnite-successstory-plugin/files/4867534/playnite.log)
there ya go

**Comment by Lacro59** [comment]
Thanks.
