### ISSUE TITLE
Playnite 10 - Error 403: Forbidden with Playstation 4, 5, and PSN Games

### ISSUE THREAD

**Issue by Chaoxufurwa** [Lacro59/playnite-successstory-plugin#331]
Hello,

I noticed that Success Story gives me an error 403 upon trying to obtain achievement data for Playstation 4, Playstation 5, and games purchased off the PSN (Playstation Network).

![Imgur](https://i.imgur.com/S9p59DJ.png)

Here's an attached log file.

[SuccessStory_2022-10-26.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/9869625/SuccessStory_2022-10-26.zip)

**Comment by Chaoxufurwa** [comment]
I forgot to mention this happens on Playnite 10, specifically Playnite version 10.3

**Comment by eskypi** [comment]
Same Error :( 

Help please

**Comment by eskypi** [comment]
![image](https://user-images.githubusercontent.com/89943859/198905639-c2b9cf71-0336-45b2-aa45-404500090d12.png)
