### ISSUE TITLE
Epic Games Store keeps needing reauthenticated to find achievements

### ISSUE THREAD

**Issue by Jhanlon95** [Lacro59/playnite-successstory-plugin#337]
I've found that when you try and pull achievements from Epic Games Store sometimes it won't find anything even if you're authenticated in the Playnite Library plugin, it can be resolved by going through the reauthenticating service in the Playnite library again, but it's a bit of a pain. 

Could this be looked into?

**Comment by Jhanlon95** [comment]
Hey, I've noticed that this is still happening. If I don't reauthenticate with the Epic Library plugin then eventually Achievements just stop being found and/or updating.

**Comment by pmrpla** [comment]
Just checked and this is still an issue, I needed to re-authenticate to get the unlocked achievements.
