### ISSUE TITLE
PlayStaion Trophies cannot sync

### ISSUE THREAD

**Issue by hyam0615** [Lacro59/playnite-successstory-plugin#340]
Error when sync the trophies. I authenticate the playstation account again but it doesn't help.

**Comment by Lacro59** [comment]
duplicate https://github.com/Lacro59/playnite-successstory-plugin/issues/331

**Comment by hyam0615** [comment]
really sorry I don’t know about codes. Should I just wait for the next release?

**Comment by Lacro59** [comment]
Yes.

**Comment by hyam0615** [comment]
Thank u, big fan of your works
