### ISSUE TITLE
Hidden achievements remain hidden after being unlocked

### ISSUE THREAD

**Issue by sirrus233** [Lacro59/playnite-successstory-plugin#346]
SuccessStory now allows the hiding of achievement descriptions if that achievement is intended to be hidden, only showing the description as "Hidden Achievement". That placeholder description should be replaced by the real description when the achievement is unlocked, but it is not.

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-successstory-plugin/commit/449b44b3c97a5239a790afe903174c3dc823962d
