### ISSUE TITLE
Not loading RPCS3 achievements again

### ISSUE THREAD

**Issue by lucasmarotta** [Lacro59/playnite-successstory-plugin#347]
I noticed that using playnite 10.9 the RPCS3 achievements are not loading, even putting the home use folder, and RPCS3 showing them. This is a recurrent issue, since there was a older closed issue #328 with the same problem.

**Comment by Lacro59** [comment]
Can you post your extension.log?

**Comment by JohnGhostly** [comment]
Having the same issue. where can I find the log file?

**Comment by Lacro59** [comment]
In %appdata%\Playnite or Playnite folder (portable version).

**Comment by JohnGhostly** [comment]
[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/10610090/extensions.log)
I hope you dont mind but I censored my username for privacies sake.

**Comment by thundercatsNZ** [comment]
Any update on this? I have a similar issue, my extensions log reports:

14-04 17:58:09.350|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(Sly Cooper: Thieves in Time - 0c509dfc-0043-461e-a1de-af52a99ac120)
14-04 17:58:09.362|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.Rpcs3Achievements for Sly Cooper: Thieves in Time - 0c509dfc-0043-461e-a1de-af52a99ac120
14-04 17:58:09.362|INFO |SuccessStory#<>c__DisplayClass5_0:TrophyFolder: C:\Emulators\RPCS3\dev_hdd0\home\00000001\trophy
14-04 17:58:09.362|INFO |SuccessStory#<>c__DisplayClass5_0:GameTrophyFolder: B:\Sony\Sony PlayStation 3\dev_hdd0\game\NPUA80875\USRDIR\..\TROPDIR
14-04 17:58:09.362|WARN |SuccessStory#Rpcs3Achievements:No Trophy directoy found for Sly Cooper: Thieves in Time
14-04 17:58:09.368|INFO |SuccessStory#PluginDatabaseObject`4:No achievements find for Sly Cooper: Thieves in Time - 0c509dfc-0043-461e-a1de-af52a99ac120

Is there a problem with looking up the trophies online?

Thanks!

**Comment by thundercatsNZ** [comment]
Any update with this?

The plugin does seem to work for some games, but most fail. The logs just show this:

`14-04 19:25:22.225|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(God of War: Chains of Olympus - c73d2c99-9441-4fa9-8527-00611fd8d311)
14-04 19:25:22.225|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.Rpcs3Achievements for God of War: Chains of Olympus - c73d2c99-9441-4fa9-8527-00611fd8d311
14-04 19:25:22.225|INFO |SuccessStory#<>c__DisplayClass5_0:TrophyFolder: C:\Emulators\RPCS3\dev_hdd0\home\00000001\trophy
14-04 19:25:22.225|INFO |SuccessStory#<>c__DisplayClass5_0:GameTrophyFolder: C:\Emulators\RPCS3\dev_hdd0\game\NPUA80637\USRDIR\..\TROPDIR`

I hit Refresh for this game and nothing happens. How can I find out why the search is failing? I can find the game in Exophase if I look manually but then I have to add the trophies manually...

Thanks!

**Comment by lucasmarotta** [comment]
@Lacro59 I did a deep investigation about the issue, sorry for not responding with more details. Here's what I found. The main reason is that the RPCS3 client is not locating the "GameTrophyFolder". The "GameFolder" is found, but not the "GameTrophyFolder" as in the log below:

```.log
24-06 06:02:46.046|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(Metal Gear Solid 4: Guns of the Patriots - 395a0bd0-67fe-4fad-bbe1-7e36e2c4cf0f)
24-06 06:02:46.046|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.Rpcs3Achievements for Metal Gear Solid 4: Guns of the Patriots - 395a0bd0-67fe-4fad-bbe1-7e36e2c4cf0f
24-06 06:02:46.046|INFO |SuccessStory#<>c__DisplayClass5_0:TrophyFolder: E:\PS3\RPCS3\dev_hdd0\home\00000001\trophy
24-06 06:02:46.046|INFO |SuccessStory#<>c__DisplayClass5_0:GameTrophyFolder: E:\PS3\Games\METAL GEAR SOLID 4 GUNS OF THE PATRIOTS [BLUS30109]\PS3_GAME\USRDIR\..\TROPDIR
24-06 06:02:46.046|WARN |SuccessStory#Rpcs3Achievements:No Trophy directoy found for Metal Gear Solid 4: Guns of the Patriots
24-06 06:02:46.046|INFO |SuccessStory#PluginDatabaseObject`4:No achievements find for Metal Gear Solid 4: Guns of the Patriots - 395a0bd0-67fe-4fad-bbe1-7e36e2c4cf0f
```

So to what I understand, some games don't have in the base game trophies, like MGS4, so it needs a patch update. This update is installed on `{EmulatorDir}\dev_hdd0\game\{GameSerial}\` which have the `TROPDIR` dir folder. So initially I thought, I will change my Emulator Scanner to be `{ EmulatorDir}\dev_hdd0\game` which works, it detects the game, so I update the SuccessStory again, and no luck this time, with the following log error

```.log
24-06 06:11:11.183|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(Metal Gear Solid 4: Guns of the Patriots - 395a0bd0-67fe-4fad-bbe1-7e36e2c4cf0f)
24-06 06:11:11.183|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.Rpcs3Achievements for Metal Gear Solid 4: Guns of the Patriots - 395a0bd0-67fe-4fad-bbe1-7e36e2c4cf0f
24-06 06:11:11.187|INFO |SuccessStory#<>c__DisplayClass5_0:TrophyFolder: E:\PS3\RPCS3\dev_hdd0\home\00000001\trophy
24-06 06:11:11.187|INFO |SuccessStory#<>c__DisplayClass5_0:GameTrophyFolder: \dev_hdd0\game\BLUS30109\USRDIR\..\TROPDIR
24-06 06:11:11.187|WARN |SuccessStory#Rpcs3Achievements:No Trophy directoy found for Metal Gear Solid 4: Guns of the Patriots
24-06 06:11:11.187|INFO |SuccessStory#PluginDatabaseObject`4:No achievements find for Metal Gear Solid 4: Guns of the Patriots - 395a0bd0-67fe-4fad-bbe1-7e36e2c4cf0f
``` 

Notice that now strangely the log for the `GameTrophyFolder` is `\dev_hdd0\game\BLUS30109\USRDIR\..\TROPDIR` not showing the initials `E:\PS3\RPCS3\` which is the {EmulatorDir} for my machine. So lI decided to look in the [Rpcs3Achievements.cs](https://github.com/Lacro59/playnite-successstory-plugin/blob/master/source/Clients/Rpcs3Achievements.cs) file line 200:

```.cs
string GameTrophyFolder = Path.Combine(game.InstallDirectory, "..", "TROPDIR");
```
So in the plugin combines the `game.InstallDirectory` moving to the parent and then go the `TROPDIR` which doesn't look wrong for me. I decided to test this `game.InstallDirectory` using the game scripts tab with the following code:

```.ps1
$PlayniteApi.Dialogs.ShowMessage($Game.InstallDirectory)
```
The result is `{EmulatorDir}\dev_hdd0\game\BLUS30109\USRDIR\` which is exactly what is inside the "Installation Folder" on "Installation" tab. I know the Rpcs3Achievements file uses **InstallDirectory**, but this was for sanity check.

In conclusion, the error is the discovery of the GameTrophyFolder, which for games that don't ship with trophies, they are located inside the `dev_hdd0`. Why changing the ROM path to this location the plugin doesn't resolve properly the `game.InstallDirectory` I don't know. Right now, I found two ways to solve this, without updating the code:

- Use an absolute path (when using a emulator auto scan you can choose this) for inside your `dev_hdd0`, like `{EmulatorDir}\dev_hdd0\game\BLUS30109\USRDIR\`  (replace {EmulatorDir} with the full path)
- Or copy the `{EmulatorDir}\dev_hdd0\game\{GameSerial}\TROPDIR` to your ROM folder `{RomDir}\{GameDir}\PS3_GAME`

I hope this helps. The real mystery for me here is why using `{EmulatorDir}\dev_hdd0\game\BLUS30109\USRDIR\` as the installation folder don't work.

**Comment by mickaelxd** [comment]
Hey @lucasmarotta, any updates on this digging? I'm facing the same issue here, same logs.

**Comment by Lacro59** [comment]
Unable to detect RPCS3 trophies #481
