### ISSUE TITLE
Epic Achievements: List of unlocked achievements are no longer being found within the page source

### ISSUE THREAD

**Issue by Jhanlon95** [Lacro59/playnite-successstory-plugin#352]
Following up from my comment in this issue #337

It seems that after a certain amount of time (maybe a day or two) after authenticating with the Epic Library plugin you are unable to find new unlocked achievements when refreshing, or after a session where you've unlocked achievements. I tried debugging the code while I was not finding any new achievements and when it goes to the games achievement page url at line 214 of EpicApi.cs, the page source is indicating that the user is not logged in meaning that when it tries to get the unlocked achievements from the page source it returns that nothing is unlocked.

I believe it's something maybe to do with cookies? Possibly when checking for achievements when the webview is created it's resulting in a new authentication token being assigned rendering the previous one invalid? I'm not really sure.

It would be very much appreciated if this could be looked into again as having to reauthenticate every day or two can get quite tedious.

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-successstory-plugin/issues/365
