### ISSUE TITLE
Steam Achievements not updating correctly

### ISSUE THREAD

**Issue by easly1989** [Lacro59/playnite-successstory-plugin#355]
Hello there,
some time ago I completed Vampire Survivors Achievements, but on playnite I still see 3 achievements locked
![image](https://user-images.githubusercontent.com/3910202/213910420-fc1a472a-61b8-4007-82d2-279f18a42018.png)

but on steam I have all:
![image](https://user-images.githubusercontent.com/3910202/213910510-dffa16a0-3316-4166-9748-7ded944e0dbe.png)

PLaynite version is 10.9
SuccessStory is updated to latest version directly from playnite

any help?

**Comment by Lacro59** [comment]
Can you post your extension.log?

**Comment by easly1989** [comment]
[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/10510612/extensions.log)
here it is

**Comment by Lacro59** [comment]
Can you try this?
https://github.com/Lacro59/playnite-successstory-plugin/issues/479#issuecomment-2191342743
