### ISSUE TITLE
"Failed to load Settings" in Playnite 10.9

### ISSUE THREAD

**Issue by Targren** [Lacro59/playnite-successstory-plugin#357]
It looks like it might be related to RetroAchievements, but I can't get into the settings to disable it. 

[Playnite.log](https://gist.github.com/Targren/697b6edf764457248fd0437234a8d496)

[Extensions.log](https://gist.github.com/Targren/ffdf168b6951a9275de281e7d757e1d3)

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-successstory-plugin/pull/356
