### ISSUE TITLE
Custom Theme Support Not Working In Details View

### ISSUE THREAD

**Issue by xyifer12** [Lacro59/playnite-successstory-plugin#36]
I have integrated `<StackPanel x:Name="PART_Achievements_Graphics" Height="120" MaxHeight="120" Margin="0,5,0,5"></StackPanel>` and `<StackPanel x:Name="PART_Achievements_List" MaxHeight="300" Margin="0,5,0,5"></StackPanel>` into my theme and enabled custom theme support, but the display does not appear even after restarting Playnite.

The displays work correctly if I enable under-details view, so I know it's not my theme breaking anything.

**Comment by Lacro59** [comment]
Can you give the file with modifications?

**Comment by xyifer12** [comment]
[DetailsViewGameOverview.xaml.txt](https://github.com/Lacro59/playnite-successstory-plugin/files/5069833/DetailsViewGameOverview.xaml.txt)

I had to add .txt to the end to get GitHub to accept the file.

**Comment by Lacro59** [comment]
Where the elements are, they are not displayed because it does not respect the hierarchy defined by the theme.
To be sure to see that it will appear, you can define a red "background" in the editor to check.

The best is to put them in "PART_ElemDescription" for this case.

Otherwise, if you use the default theme, it's to use the integrations options.

**Comment by xyifer12** [comment]
I have added a red background to where the plugin panel is supposed to appear, it displays without issue. 
![2wtr5](https://user-images.githubusercontent.com/33806276/90325056-537db300-df3c-11ea-862e-004d088ddf36.png)

I have also tried adding the plugin panels to PART_ElemDescription as you suggested, which also failed to work.
![eas45t](https://user-images.githubusercontent.com/33806276/90325072-790abc80-df3c-11ea-8e27-832071402434.png)

**Comment by Lacro59** [comment]
With the differents releases & the wiki, have you resolve your issue?

**Comment by xyifer12** [comment]
No. 1.0 does not work in current Playnite, no section for it appears in the options menu. There was also no mention of a wiki anywhere.

**Comment by xyifer12** [comment]
Playnite 8.1 has resolved the issue.
