### ISSUE TITLE
Update also installed games when library updates

### ISSUE THREAD

**Issue by Destroy666x** [Lacro59/playnite-successstory-plugin#361]
It would be nice if the "Automatically update data when library is updated" functionality also updated all installed games, rather than only newly added games. Whether optionally (another checkbox) or not, but likely better optionally.

Why? Currently you either seem to have to play current games through Playnite (game end event) or update the achievements manually through menu. Personally I often launch games directly through other means, for various reasons, so games don't get updated automatically. I only have around 20 games installed at a time so I don't mind Playnite checking each time for changes.

**Comment by Mertica** [comment]
Yes please, having an "update all" option would be GREAT

I can't imagine having to Right-Click > SuccessStory > Refresh data for every single menu item... it's just too much, even though I want to see ALL achievements, all of them...

**Comment by Lacro59** [comment]
You have in the main menu of the plugin an option to download data with many options.
![image](https://github.com/Lacro59/playnite-successstory-plugin/assets/124054/16e15d6d-fd44-4585-9368-5f7c3c11c6e9)
![image](https://github.com/Lacro59/playnite-successstory-plugin/assets/124054/e259948e-ab22-4fc6-87ed-9f7fe88a0902)

**Comment by Destroy666x** [comment]
Yes. The point of this issue is that people don't want to click that manually but rather have an option to update with each library update like bunch of other plugins do.

**Comment by Lacro59** [comment]
#451
