### ISSUE TITLE
some games do not unlock achievements (RA)

### ISSUE THREAD

**Issue by FenixBlack1030** [Lacro59/playnite-successstory-plugin#364]
I have found that some games such as mega man (nes), pepsiman (ps1) or Hugo (ps1) have functional achievements, however, after unlocking some, this is not reflected in sucess story, although both in retroachievements or retroarch, they appear as unlocked.
Update: suddenly they worked, but I had to delete the achievements of those games and then hit "update". if I gave update with the placed achievements, nothing happened. However, it is still rare since this did not happen before. I seem to have to do the same for every retroachievements game (although with figthing force and adventure island 2 I work normally).

**Comment by Lacro59** [comment]
Can you post your extension.log after a game session where the issue occurs?

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-successstory-plugin/commit/f123fd63714c16774a74e4bd0c7d1ab9e7b167d4
https://github.com/Lacro59/playnite-successstory-plugin/commit/d9d37068823520049e85955b946ae26a0c83bdf6
https://github.com/Lacro59/playnite-successstory-plugin/commit/be7228f0c7ecb97b98d46a377e00e5ef0b8010ff
