### ISSUE TITLE
Xbox achievements stop being able to be refreshed

### ISSUE THREAD

**Issue by Driesmann** [Lacro59/playnite-successstory-plugin#367]
The way Xbox achievements are pulled/refreshed is bugged I believe.

When a game is first added, the plugin works fine and the list of achievements is pulled. Then, for a while the achievements get refreshed when quitting a game or when I manually refresh achievements. However, with basically every game, this stops working at some point. Quitting a game then doesn't pull the newly unlocked achievements, nor does manually refreshing.

The only fix is to remove the game from Playnite and then add them again via the Xbox library update. This only happens with Xbox titles (GamePass in this case, if it is relevant).

However, doing this fix also means the data for the Game Activity plugin is removed, which is a bummer, and it's just inconvenient overall.

Attached you will find the extension log, with the final entry being of me refreshing the achievements without success.
[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/11142298/extensions.log)

Thanks in advance!

**Comment by Lacro59** [comment]
Can you try with the last release?
