### ISSUE TITLE
Certain achievements of steam games don't have description

### ISSUE THREAD

**Issue by darklinkpower** [Lacro59/playnite-successstory-plugin#37]
![imagen](https://user-images.githubusercontent.com/1389286/87825208-4b96fa00-c83c-11ea-83b3-bd59e0650cc9.png)

For some reason it happens for all achievements with this icon in this game

![imagen](https://user-images.githubusercontent.com/1389286/87825089-15f21100-c83c-11ea-966d-7bd03567aaf4.png)

Opening achiemenvents link while not logged in doesn't show descriptions either https://steamcommunity.com/stats/742120/achievements:

![imagen](https://user-images.githubusercontent.com/1389286/87825141-2acea480-c83c-11ea-8ffd-dc31d462c26f.png)

While logged in:

![imagen](https://user-images.githubusercontent.com/1389286/87825158-35893980-c83c-11ea-962c-55ac578e5c35.png)

**Comment by SaltySamurai** [comment]
I imagine using the unlocked achievement description even for locked achievements might be a solution, but some games have funny alt text for locked vs unlocked.

**Comment by Lacro59** [comment]
The cause is a hidden achievement:
![screenshot_1](https://user-images.githubusercontent.com/124054/90137827-73637a00-dd76-11ea-8708-8a1779d0abab.png)
