### ISSUE TITLE
Starcraft 2 achievements are very incorrect

### ISSUE THREAD

**Issue by sirrus233** [Lacro59/playnite-successstory-plugin#374]
I'm trying to use this plugin to view SC2 achievements, but although I seem to be able to connect and sync, there are a lot of inaccuracies in the data.

Specifically:
* I am missing many achievements that I have unlocked in the game (51 reported in SuccessStory, vs. hundreds in the game client)
* Many achievements incorrectly show as being held by 100% of players 
* Many achievements incorrectly show as being held by 0% of players

**Comment by Lacro59** [comment]
The plugin uses the API to get the data.
It's weird not having it all.
Is your profile public so I can check it out?

**Comment by sirrus233** [comment]
It should be public, yes. My tag is Sirrus233#1184
