### ISSUE TITLE
Manual update (edit) on a local game's achievement, I get an error

### ISSUE THREAD

**Issue by Xeero13** [Lacro59/playnite-successstory-plugin#377]
After the latest update when I do a manual update (edit) on a local game's achievement, I get an error.

Also posted this on redit. See pic below

https://preview.redd.it/pcuhmnwbq31b1.png?width=568&format=png&auto=webp&v=enabled&s=1c38055b6c856366fefda281ea3d822d3fefe3dd

**Comment by Xeero13** [comment]
Update:

I reinstalled successstory 3.0 and error goes away. The error is related to the new version.

**Comment by Emad-ElBana** [comment]
I have the exact same error when I'm trying edit achievements manually it's first time happens to me any solution please?!

**Comment by Xeero13** [comment]
Hi,

I reinstalled 3.1.1 and unfortunately still have the same error. Can teach me how to send the error log?

Regards
