### ISSUE TITLE
some auth issue? log included.

### ISSUE THREAD

**Issue by triadne** [Lacro59/playnite-successstory-plugin#379]
[SuccessStory_2023-05-21.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/11524723/SuccessStory_2023-05-21.zip)

it's not loading steam achievements or ea achievements.

**Comment by PescheHelfer** [comment]
I am also getting an error message regarding auth: 
SuccessStory
Failed to parse
{"message":"Unauthenticated.","errors":["status":419,"code"."unauthorized","title":"Unauthenticated."}]}

Log:
[SuccessStory_2023-06-12.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/11715911/SuccessStory_2023-06-12.zip)

**Comment by triadne** [comment]
Try get yourself an api code for steam, even if your profile is set to public. I did that and success story started working.

**Comment by PescheHelfer** [comment]
Thanks for the hint! What do you do with the API code once you have it?

**Comment by triadne** [comment]
Put it in the box that says 'API'.

**Comment by triadne** [comment]
Ah, I'm sorry it hasn't worked for you. 
All I can suggest is 
![image](https://github.com/Lacro59/playnite-successstory-plugin/assets/29523389/409dd7bc-96c7-448e-9de9-607d1a9e9300)
try fiddle with these settings maybe. I'm not a coder so I can't help any further, I only know it worked when I did that.
Good luck!
(also, you could try asking at discord if you have no joy)

**Comment by PescheHelfer** [comment]
Thanks, I will try that. Thanks a lot for your help, anyway!

**Comment by PescheHelfer** [comment]
Figured it out! Steam was never the troublemaker; it was RetroAchievements (which I don't even use). After removing that checkmark, Playnite has been starting significantly faster and the error message is gone. :)

![RetroAchievements](https://github.com/Lacro59/playnite-successstory-plugin/assets/8842081/0493a09f-99a9-4ab5-9332-5153c583fcd4)

**Comment by Lacro59** [comment]
#389
