### ISSUE TITLE
Manually added Exophase achievements trigger NullReferenceException

### ISSUE THREAD

**Issue by dististik** [Lacro59/playnite-successstory-plugin#382]
Encountered specifically with the Default Extended theme. Steps to reproduce:

- Change to Details View
- Right click a game from your library and manually add achievements to it
- Choose to add achievements from any Exophase entry
- Click on the "Achievements" tab next to "Description"

Usually this causes a hard crash, but if you switch to that tab on say a Steam game and then change the game to one with Exophase achievements, Playnite will generate a crash log. As far as I can tell this only happens with Exophase and it only happens on that tab specifically; the SuccessStory button works as intended.

Log: 
[log.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/11542054/log.zip)

**Comment by Xeero13** [comment]
Same issue as what I posted. Not really fixed unfortunately. Try using 3.0 for now.

**Comment by dististik** [comment]
3.1.2 fixed the issue for me, actually. There may be something else extending the issue for you.

**Comment by Xeero13** [comment]
> 3.1.2 fixed the issue for me, actually. There may be something else extending the issue for you.

Hmm I think that's it. When I re-update the extension, all it gave me is 3.1.1. I'll try again to update.
