### ISSUE TITLE
Wrong set of achievements imported with manual import

### ISSUE THREAD

**Issue by jullebarge** [Lacro59/playnite-successstory-plugin#383]
When I try to import Ubisoft achievements from Exophase for The Division 2, the extension imports the Xbox version, where achievements are different from the PC version
In this capture, I select the first item, but it's the second one that is imported by the extension
![image](https://github.com/Lacro59/playnite-successstory-plugin/assets/11553167/62820970-ddf4-4b75-b04c-c4616cda67fd)

One thing I've noticed, the number of achivements is correct, but the names and description are inverted: I have 35 achievements like in Ubisoft version, but the names are from the Xbox version.

Here is the log after adding the achievements from Ubisoft source:
[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/11552926/extensions.log)

**Comment by Lacro59** [comment]
Can you try with the last release?

**Comment by jullebarge** [comment]
The last release fixed the problem :)
