### ISSUE TITLE
Error on Download Plugin Data

### ISSUE THREAD

**Issue by Chaoxufurwa** [Lacro59/playnite-successstory-plugin#384]
I was trying to use the function to download plugin data to update my achievements in bulk for games I've been playing, and it immediately threw an error. No achievement data was updated either.

Log file attached.

[SuccessStory_2023-05-29.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/11594469/SuccessStory_2023-05-29.zip)

**Comment by Lacro59** [comment]
RetroAchievements Success #389
