### ISSUE TITLE
Infinite loop when service down

### ISSUE THREAD

**Issue by SkyNinja** [Lacro59/playnite-successstory-plugin#387]
One of the services, I'm unsure which, is currently returning a 503. When trying to access the plugin's settings, it hangs Playnite and fills extensions.log with this error:

```
18-06 19:38:59.349|ERROR|SuccessStory#Common:|???|0
System.Exception: Failed to parse <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/11782995/extensions.log)
The log has some redactions for privacy. It only covers my last run and has a key redacted. Otherwise, it lasts until I terminated Playnite via command prompt.

**Comment by LGPlays** [comment]
![Captura de tela 2023-06-18 220308](https://github.com/Lacro59/playnite-successstory-plugin/assets/119265838/6be6844e-b6c6-4986-9c21-5a8c614ea137)

for me it has this error

**Comment by Lacro59** [comment]
duplicate https://github.com/Lacro59/playnite-successstory-plugin/issues/389
