### ISSUE TITLE
is not working

### ISSUE THREAD

**Issue by LGPlays** [Lacro59/playnite-successstory-plugin#388]
some error, it is not loading any achievement
![Captura de tela 2023-06-18 220308](https://github.com/Lacro59/playnite-successstory-plugin/assets/119265838/cab1b232-6d90-4312-8a4b-0b38b1dcd63e)

[SuccessStory_2023-06-18.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/11783060/SuccessStory_2023-06-18.zip)

**Comment by Lacro59** [comment]
duplicate https://github.com/Lacro59/playnite-successstory-plugin/issues/389
