### ISSUE TITLE
RetroAchievements Success

### ISSUE THREAD

**Issue by Vincent0047** [Lacro59/playnite-successstory-plugin#389]
Hello,

I have an errror when i try to get back the retroachievements : Unexpected character encountered while parsing value: <. Path '', line 0, position 0
[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/11800839/extensions.log)

Thanks for your help.

Vincent

**Comment by themerchant** [comment]
I have the exact same issue
[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/11804796/extensions.log)

**Comment by rachelhbush** [comment]
I also have this issue
[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/11820197/extensions.log)

**Comment by RaoulDukeKD** [comment]
Same issue here.
[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/11827048/extensions.log)

**Comment by SkyNinja** [comment]
I'm still having an infinite loop that causes my client to hang as I described and provided a log for in #387. I've uninstalled for now because this is causing me hell any time I misclick in settings.

**Comment by maurinhozonasul** [comment]
Same problem here.
Steam achievements are normal, though.
Whenever I try updating RA achievements, I get the same error.


[SuccessStory_2023-07-01.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/11924986/SuccessStory_2023-07-01.zip)

**Comment by NEXAnomaly** [comment]
Same here, RA won't sync but other sources will
[SuccessStory_2023-07-05.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/11954001/SuccessStory_2023-07-05.zip)

**Comment by renatordutra** [comment]
So, any chance of a fix?

**Comment by ZachJDev** [comment]
This is an issue with the Retro achievements API: https://retroachievements.org/viewtopic.php?t=22254. Long story short, they've turned off the endpoint that SuccessStory uses for the foreseeable future.

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-successstory-plugin/issues/420

**Comment by eldaniay** [comment]
I still get the error as of version 3.1.5

**Comment by Glorithan** [comment]
> This is an issue with the Retro achievements API: https://retroachievements.org/viewtopic.php?t=22254. Long story short, they've turned off the endpoint that SuccessStory uses for the foreseeable future.

This post links to another git regarding the api for retroachievements. That post ends in December of 2023 and implies that everything should be back up. That said, my successstory still doesn't want to pull in anything from retroachievements

![image](https://github.com/Lacro59/playnite-successstory-plugin/assets/78930333/e29ff87f-365c-4c35-86e2-c51e4f164336)
