### ISSUE TITLE
World of Warcraft achievements cannot be set up

### ISSUE THREAD

**Issue by LordBoos** [Lacro59/playnite-successstory-plugin#392]
When I enable it and select a region, I'm unable to select the Ream, because the list is empty and using refresh button next to it does not fill the list.
![image](https://github.com/Lacro59/playnite-successstory-plugin/assets/939813/dffa3ca7-327c-4bb4-a4bc-ce5816948ffb)
Error in extension log:
`30-06 21:20:57.951|ERROR|SuccessStory#Common:Error on GetRealm()|D:\GitHub\Lacro59\playnite-successstory-plugin\source\Clients\WowAchievements.cs|145
System.NullReferenceException`

**Comment by basedwinds** [comment]
I am having the same error :(

**Comment by mahgo** [comment]
@Lacro59 Is this definitely resolved? I'm having the same issue in v3.1.5, it appears the the graphql request returns BadRequest.
