### ISSUE TITLE
After installing v3.13 to fix #394, plugin tells me I am not authenticated to GOG

### ISSUE THREAD

**Issue by JustThat70** [Lacro59/playnite-successstory-plugin#395]
24-07 17:07:28.884|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(Tainted Grail: Conquest - bdcd31cf-cfb4-4293-95af-1b8fd6fcff44)
24-07 17:07:29.909|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.GogAchievements for Tainted Grail: Conquest - bdcd31cf-cfb4-4293-95af-1b8fd6fcff44
24-07 17:07:30.243|WARN |SuccessStory#GogApi:Not find: window.profilesData.currentUser
24-07 17:07:30.261|WARN |SuccessStory#GenericAchievements:GOG user is not authenticated
24-07 17:07:30.272|INFO |SuccessStory#PluginDatabaseObject`4:No achievements find for Tainted Grail: Conquest - bdcd31cf-cfb4-4293-95af-1b8fd6fcff44

I've disconnected and reconnected to GOG and I still get this error.

**Comment by Jeshibu** [comment]
Check the "Profile enabled" box here: https://www.gog.com/en/account/settings/privacy

**Comment by JustThat70** [comment]
Well, don't I feel silly. That fixed it. Thanks!

**Comment by Jeshibu** [comment]
It's not obvious, the error message should be clearer imo (also it pretty much does nothing with this data, so it's not even needed really, it's just shared code between PlayerActivities and SuccessStory that SuccessStory doesn't need).

Glad you got it working though!
