### ISSUE TITLE
Playnite crashes when I click successstory setting

### ISSUE THREAD

**Issue by hyam0615** [Lacro59/playnite-successstory-plugin#400]
using the lastest version of playnite and extension

**Comment by Hernald** [comment]
Yes, I'm getting that too.

**Comment by shlart** [comment]
I as well, switching from other themes including default has the same effect.

**Comment by manurtinez** [comment]
I too am having this issue, clicking on settings freezes whole Playnite. Tried on a new install and seems to work fine, so don't know what the problem is
