### ISSUE TITLE
Updated The Process cannot access the Loginusers.vdf

### ISSUE THREAD

**Issue by Phantomahawk** [Lacro59/playnite-successstory-plugin#401]
I have no clue how to fix this I also don't have much to say It looks so simple but I am new at this.
![Screenshot_2](https://github.com/Lacro59/playnite-successstory-plugin/assets/144281112/becb6267-7adf-4686-8f37-389e41e32fab)
[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/12708319/extensions.log)
[playnite.log](https://github.com/Lacro59/playnite-successstory-plugin/files/12708320/playnite.log)

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/5283b4a62fbb405d9d0e3fa08175c8bfc083aea0
