### ISSUE TITLE
SucceStory, The Process cannot access the Loginusers.vdf

### ISSUE THREAD

**Issue by Phantomahawk** [Lacro59/playnite-successstory-plugin#404]
the message is from SucceStory, the error occurs with only a couple games I don't know any error similar because I never fix any issues with Playnite before the games I noticed that the error occurs is with halo infinite and halo MCC this is the only games I know it occurs with, other possible games are CSGO 2 and State of Decay: Year-One.

here is the logs.
[playnite.log](https://github.com/Lacro59/playnite-successstory-plugin/files/12775069/playnite.log)
[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/12775070/extensions.log)

**Comment by Lacro59** [comment]
with https://github.com/Lacro59/playnite-successstory-plugin/issues/401
