### ISSUE TITLE
Feature Request: Optionally ignore/exclude games you have not earned any achievements/trophies

### ISSUE THREAD

**Issue by binarymelon** [Lacro59/playnite-successstory-plugin#414]
Would it be possible to have an option to ignore games that you have 0% on?

**Comment by Lacro59** [comment]
Do you want this option in the main plugin view with all achievements?

**Comment by Lacro59** [comment]
Can you explain further what you want?

**Comment by binarymelon** [comment]
Sorry, I must have missed or forgotten about your previous question.  Just a flag (checkbox) to exclude any game where you haven't unlocked a single achievement/trophy.  So, games with 0 achievements are treated the same as games that have never been started.
