### ISSUE TITLE
The Exosphere profile has an endless captcha when I trying login it.

### ISSUE THREAD

**Issue by death7lord** [Lacro59/playnite-successstory-plugin#415]
The Exosphere profile has an endless captcha when I trying login it.
Also I have a problems - I can't load Steam achievements. Others platforms is fine.

**Comment by Lacro59** [comment]
> The Exosphere profile has an endless captcha when I trying login it.  

I've not a catcha. Can you post a secreenshot?

> Also I have a problems - I can't load Steam achievements. Others platforms is fine.  

Do you have chek this ? https://github.com/Lacro59/playnite-successstory-plugin/wiki/Configure-Steam

**Comment by death7lord** [comment]
> Can you post a secreenshot?
![Clipboarder 2023 12 16](https://github.com/Lacro59/playnite-successstory-plugin/assets/3726465/b13aec20-d46e-4e2c-ba80-fb8f297d8f71)

**Comment by death7lord** [comment]
> I've not a catcha. Can you post a secreenshot?

![Clipboarder 2023 12 16](https://github.com/Lacro59/playnite-successstory-plugin/assets/3726465/e9c71eb7-f714-4ad8-b925-aec917542c4f)
