### ISSUE TITLE
Input string '1.0' is not a valid integer. Path 'games.pages', line 1, position 90.

### ISSUE THREAD

**Issue by kybeeTV** [Lacro59/playnite-successstory-plugin#422]
This notification seems to pop up every time I finish playing a Steam game.

[SuccessStory_2023-12-12.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/13654480/SuccessStory_2023-12-12.zip)

**Comment by Muckyfeet** [comment]
Same here...

![Screenshot 2023-12-13 033950](https://github.com/Lacro59/playnite-successstory-plugin/assets/1675319/4aa7c283-9463-4288-93c2-9705f4d0549d)

[SuccessStory_2023-12-13.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/13655652/SuccessStory_2023-12-13.zip)

**Comment by Lacro59** [comment]
duplicate #417
