### ISSUE TITLE
Input string '1.0' is not a valid integer

### ISSUE THREAD

**Issue by ivanlorusso** [Lacro59/playnite-successstory-plugin#423]
Thhis error pops up when tryingg to refresh Steam achievements for "Warhammer 40.000: Rogue Trader" (log package) and other games.
[SuccessStory_2023-12-13.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/13664875/SuccessStory_2023-12-13.zip)

**Comment by gr3y5had0w** [comment]
I also get this issue but for all my Steam games when downloading plugin data. It completely stopped working for Steam.

**Comment by hyam0615** [comment]
I also get this error when refreshing steam achievements

**Comment by Lacro59** [comment]
duplicate https://github.com/Lacro59/playnite-successstory-plugin/issues/417
