### ISSUE TITLE
[Bug] Exophase not working even when authenticated.

### ISSUE THREAD

**Issue by Nick2bad4u** [Lacro59/playnite-successstory-plugin#424]
It's returning nothing in the results, even after I login and it shows authenticated.

**Comment by Lacro59** [comment]
When trying to search for manual achievements?
Do you have an exaple?

**Comment by Nick2bad4u** [comment]
> When trying to search for manual achievements? Do you have an example?

Seems fixed since last update.

I was looking for "The Crew: Motorfest" - It works now.

**Comment by PescheHelfer** [comment]
If I may ask: what settings are you using? I can't manage to synchronize unlocked achievements, with or without Exophase.

**Comment by Koriebonx98** [comment]
I can’t seem to get this part working myself either. 

Out of curiosity does this add achievements automatically to the same games that’s on the user account?

e.g “skate 3” “Xbox 360” 

would this translate to 
“Skate 3” “Xbox 360” “Xenia” 

so if I have the Xbox 360 rom of skate 3 and my Microsoft account is linked to exophase. Would it then display my achievements from exophase to the game data in playnite automatically or would I have to manually add to each game I want achievements on?

If yes, couldn’t there be away to add Xenia emulator achievements with success story? 
we could keep our original game saves and then continue with the achievements too?

**Comment by Lacro59** [comment]
@Koriebonx98 
Exophase data only concerns manual achievements.
Your request must be a new request because it is different from the initial one.

**Comment by Lacro59** [comment]
find: Xbox 360 achievements #473

**Comment by Koriebonx98** [comment]
> Xbox 360 achievements #473 Manually updating via json #453

eFman made a custom fork with this in, i made a working script time ago to auto update xbox 360 ach like rpcs3 but via log.

eFman added it to a custom fork and works flawlessly.

am currently working on custom switch ach via ruyjinx log (Not all Games will work)
MK8D works, SM3dW, Sonic, kirby work as has data in log.. Pokemon doesnt gavent tried zelda
