### ISSUE TITLE
Success Story - Not Importing Retro Achievements (Plugin Data) for Certain Platforms

### ISSUE THREAD

**Issue by DeathspiralX** [Lacro59/playnite-successstory-plugin#425]
Symptom 

Download Plugin Data is only downloading Retro Achievements for SNES and Gameboy / GB Color out of the tested platforms below. 

Steps Taken

1) Enable Retro Achievements, Enter Username + API 
2) Associated Platforms Selected, Automatic Import turned on. 
3) Download Plugin Data 

Associated Platform appears on the dropdown list and is selected, however nothing is displayed once selected. 

NES - Not Importing
SNES - Importing
N64 - Not Importing
PSX - Not Importing
PS2 - Not Importing
Gameboy - Importing
Gameboy Color - Importing
Gameboy Advance - Not Importing
Neo Geo - Not Importing
Sega Dreamcast - Not Importing
Sega Genesis - Not Importing

![Image 4](https://github.com/Lacro59/playnite-successstory-plugin/assets/154023651/ed8f461c-93a9-45af-bf42-11575e586200)
![image 2 5](https://github.com/Lacro59/playnite-successstory-plugin/assets/154023651/2397ce5f-8a2b-426e-a5f4-650580767571)
![image 3 ](https://github.com/Lacro59/playnite-successstory-plugin/assets/154023651/634b44e0-9ece-4775-982a-65b1a47bad59)
![image2](https://github.com/Lacro59/playnite-successstory-plugin/assets/154023651/4330a0a8-047e-4c04-b016-6dad8ef3389f)
![image1](https://github.com/Lacro59/playnite-successstory-plugin/assets/154023651/f429746a-7110-425d-8424-79856abf017d)

**Comment by Lacro59** [comment]
Can you post tour extension.log?

**Comment by DeathspiralX** [comment]
Here is the extension log, and a few new screenshots. 

Highlighted it says Ninja Gaiden for example has no achievements, however when the games load into retroarch the achievements load and update to Retro achievements. Would this have to do with how the files are named in my directory?

[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/13693997/extensions.log)
![New Image 2](https://github.com/Lacro59/playnite-successstory-plugin/assets/154023651/726b9fcd-15f2-4af6-8182-02aa96b09513)
![New Image 1](https://github.com/Lacro59/playnite-successstory-plugin/assets/154023651/0a285458-672e-44c3-b010-aacf9f38c692)

**Comment by DeathspiralX** [comment]
Update, 

I deleted the games from Playnite and added them back again, now the achievements are importing for NES Games, i'll keep you updated if the rest of the platforms import once im done.  It sounds like ir might be a caching issue.

**Comment by nxllxvxid** [comment]
> Update 3
> 
> All Platforms are now importing

Did you just keep deleting them from Playnite and readding to achieve this with PS1 and PS2 games? I am unable to get it to work for those platforms.
