### ISSUE TITLE
Unlocked successes not loaded from steam

### ISSUE THREAD

**Issue by LeMimit** [Lacro59/playnite-successstory-plugin#426]
Hello all !

I am trying to get my unlocked successes from a game on steam.
Successes are loaded from steam but my unlocked success does not appear.

![image](https://github.com/Lacro59/playnite-successstory-plugin/assets/10245195/bf88019a-3968-41ac-9ea1-7105c7f2f443)

I tried every combinaison: public profil without and with key and private profil none is working.

In my lastest test I tried with public profil and with api key, my logs in `extensions.log` does not show errors:
```log
17-12 08:29:06.057|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(One Way: The Elevator - 3e99b331-ea8d-42da-82e8-ada617d9ff81)
17-12 08:29:06.057|INFO |SuccessStory#PluginDatabaseObject`4:RefreshManual(One Way: The Elevator - 3e99b331-ea8d-42da-82e8-ada617d9ff81)
17-12 08:29:06.062|INFO |SuccessStory#SteamAchievements:GetAchievements(1347420) - IsLocal : True, IsManual : True, EnableSteamWithoutWebApi: False, SteamIsPrivate: False
```

Here are my settings:

![image](https://github.com/Lacro59/playnite-successstory-plugin/assets/10245195/5c592cec-9c49-4d08-bfd5-818ab6cd7888)

![image](https://github.com/Lacro59/playnite-successstory-plugin/assets/10245195/5c2a013c-1e6b-4d63-a0a3-d0470b2cff70)

I did not find a way to have more logs ?

Tell me if I can help doing tasks helping finding a way to fix this problem.

**Comment by PescheHelfer** [comment]
Yes, I got the same issue. See also here:
https://github.com/Lacro59/playnite-successstory-plugin/issues/412
