### ISSUE TITLE
Unexpected character encountered while parsing value

### ISSUE THREAD

**Issue by Whitechapel-1888** [Lacro59/playnite-successstory-plugin#432]
I have this error pop up constantly no matter which game I am playing (steam, gog, games on emulators, you name it). Not sure what this is about, but I was told to mention this here.
[extensions.log](https://github.com/Lacro59/playnite-successstory-plugin/files/13788239/extensions.log)
[playnite.log](https://github.com/Lacro59/playnite-successstory-plugin/files/13788240/playnite.log)

Not sure if this is related, but for _**some**_ games, SuccessStory does not download any RetroAchievements. Affected are e.g. Vagrant Story or Parasite Eve. But the achievements work in the emulator I use, and only some games seem to be affected.

**Comment by hyam0615** [comment]
same problem here

**Comment by Whitechapel-1888** [comment]
Problem persists after update. It seems this only happens when connecting to RetroAchievements:
`07-01 21:07:46.250|ERROR|SuccessStory#Common:Error on GetMD5List()|G:\GitHub\Lacro59\playnite-successstory-plugin\source\Clients\RetroAchievements.cs|241
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.`

[SuccessStory_2024-01-08.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/13855210/SuccessStory_2024-01-08.zip)
