### ISSUE TITLE
Refresh Data (RetroAchievements) only working after saving plugin config

### ISSUE THREAD

**Issue by Whitechapel-1888** [Lacro59/playnite-successstory-plugin#434]
This is most likely the part of the problem why importing RetroAchievements (RA) does not work for some users. I am not entirely sure what the root of this problem is.

**Problem Description:**
The Success Story plugin does not add achievement data from RA when using either Refresh Data (right clicking on the game, then selecting SuccessStory > Refresh Data) or Download Plugin Data... (Main Menu > Extensions > SuccessStory). It may have worked before however, so some achievements for certain games are visible in playnite.

**Workaround Solution:**
 As found by [LukeMW](https://www.reddit.com/r/playnite/comments/18si70t/comment/kfdobjt/?context=3): Saving the SuccessStory plugin settings (changes are not necessary) temporarily fixes the issue. For this, go to Add-ons > Extension settings > Generic > SuccessStory and simply click on the save button. Then Refresh Data on any game missing achievements.
_For me at least, this downloads unlocked achievements, it does not download not yet unlocked achievements._

If you need logs, I can provide them, just tell me which ones you need.

**Comment by LukeMW** [comment]
I can confirm everything said above.  I also want to reiterate that the problem reoccurs every time Playnite is shutdown and restarted so the "fix" has to be performed each time as well.  Just to note, after the fix is performed, for me, it does in fact, download every achievement as normal, whether unlocked or not.

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-successstory-plugin/commit/f123fd63714c16774a74e4bd0c7d1ab9e7b167d4
https://github.com/Lacro59/playnite-successstory-plugin/commit/d9d37068823520049e85955b946ae26a0c83bdf6
https://github.com/Lacro59/playnite-successstory-plugin/commit/be7228f0c7ecb97b98d46a377e00e5ef0b8010ff
