### ISSUE TITLE
I can't Refresh Data data in SuccessStory

### ISSUE THREAD

**Issue by AleKing31** [Lacro59/playnite-successstory-plugin#440]
I can't Refresh Data the game in SuccessStory, it keeps giving this error
![erro](https://github.com/Lacro59/playnite-successstory-plugin/assets/25102223/957291a5-eaad-4fac-a002-2d648fa2fea1)
Here is the log
[SuccessStory_2024-01-07.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/13853717/SuccessStory_2024-01-07.zip)

**Comment by eldaniay** [comment]
i get the same error with 3.1.6

**Comment by Lacro59** [comment]
duplicate #432
