### ISSUE TITLE
Steam: The object reference was not set to an object instance

### ISSUE THREAD

**Issue by PescheHelfer** [Lacro59/playnite-successstory-plugin#441]
When I try to get the ulocked achievements from Steam games, the following error is logged:

The object reference was not set to an object instance. (Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.)

Consequently, the available achievements are downloaded, but it fails to get the unlocked achievements (no unlocked achievements are shown for any game).

This happens with version 3.1.6 (but I had troubles already before).

Interesting detail: I also started playing a new game recently. For that, unlocking achievements worked fine. It does not for all the games I started playing a while ago. I now reinstalled Successstory freshly, and it also stopped working for the new game: achievements unlocked previously are no longer unlocked, and achievements unlocked freshly don't get unlocked in Successstroy anymore, either.

Full error log from extensions.log:

`07-01 17:10:42.201|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.SteamAchievements for Trailmakers - b4c90ec9-5012-4c53-8126-790577087ed9
07-01 17:10:42.201|INFO |SuccessStory#SteamAchievements:GetAchievements() - IsLocal : False, IsManual : False, HasApiKey: True, SteamIsPrivate: False
07-01 17:10:42.672|INFO |SuccessStory#SteamAchievements:SteamApi.GetAchievements()
07-01 17:10:55.430|INFO |SuccessStory#PluginDatabaseObject`4:Find 22 achievements find for Trailmakers - b4c90ec9-5012-4c53-8126-790577087ed9
07-01 17:10:55.450|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.SteamAchievements for Gods Against Machines Demo - 0f91a595-2c48-49a5-b35b-f49850810326
07-01 17:10:55.450|INFO |SuccessStory#SteamAchievements:GetAchievements() - IsLocal : False, IsManual : False, HasApiKey: True, SteamIsPrivate: False
07-01 17:10:55.817|ERROR|SuccessStory#Common:Error on GetAchievements()|G:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\Steam\SteamApi.cs|412
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei CommonPluginsStores.Steam.SteamApi.GetAchievements(String Id, AccountInfos accountInfos) in G:\GitHub\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\Steam\SteamApi.cs:Zeile 412.`

**Comment by Lacro59** [comment]
Can you try with the latest version?

**Comment by PescheHelfer** [comment]
It works!  😀 👍 Thank you!!

**Comment by spidy2356** [comment]
for me this issue occured with latest version. so, I'm using 3.1.5 version

**Comment by Lacro59** [comment]
Can you try this?
https://github.com/Lacro59/playnite-successstory-plugin/issues/479#issuecomment-2191342743

**Comment by spidy2356** [comment]
@Lacro59 it's working. no issue now
