### ISSUE TITLE
Wrong set of Achievements imported via RetroAchievements

### ISSUE THREAD

**Issue by Whitechapel-1888** [Lacro59/playnite-successstory-plugin#442]
Success Story version: 3.1.6

After playing a game without an achievement set, yet Success Story pulled the wrong set of achievements. In this case, it pulled the achievements of a game I played just before:
![image](https://github.com/Lacro59/playnite-successstory-plugin/assets/44060684/e524121b-9b19-4253-bccd-1c9260489837)

As can be seen on the RA website, wipeout 3 SE doesn't have achievements:
https://retroachievements.org/game/13912

[SuccessStory_2024-01-08.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/13855210/SuccessStory_2024-01-08.zip)

**Comment by Lacro59** [comment]
Can you try with the latest version?

**Comment by Whitechapel-1888** [comment]
> Can you try with the latest version?

I refreshed data and the wrong achievements are still there:
![image](https://github.com/Lacro59/playnite-successstory-plugin/assets/44060684/f8e10525-2fd0-48a3-83f2-bdc5eaf8a501)

Is there a way to manually remove the data?

**Comment by Whitechapel-1888** [comment]
I found a workaround for this issue:
right-click on the game in your library and select "SuccessStory > Ignore game". The achievements should be gone then. Next, go into the plugin settings, "Add-ons > Extension Settings > Generic > Success Story > Ignored Games" and remove the game that was just added.

The game above now doesn't display the wrong achievement set anymore.

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-successstory-plugin/commit/be7228f0c7ecb97b98d46a377e00e5ef0b8010ff
