### ISSUE TITLE
Hash impossible - The file is too long errors

### ISSUE THREAD

**Issue by carks32** [Lacro59/playnite-successstory-plugin#445]
I tried updating with a few PS2 games I got on my playnite and this is what ended up popping out (while having another error but it's whatever)

```
08-01 12:27:21.545|DEBUG|Extras#ThemeExtras:Pushed "Grid View - .hack//Infection"
08-01 12:27:23.516|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(.hack//Infection - 07215d42-3485-410a-90eb-e0e660bdcc63)
08-01 12:27:23.516|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.RetroAchievements for .hack//Infection - 07215d42-3485-410a-90eb-e0e660bdcc63
08-01 12:27:23.516|WARN |SuccessStory#RetroAchievements:Hash impossible - The file is too long - D:\Games\Emulate\Games\ps2\\Dot Hack Part 1 - Infection (USA).chd
08-01 12:27:23.516|WARN |SuccessStory#RetroAchievements:No game find for .hack//Infection with Sony PlayStation 2 in 10
08-01 12:27:23.516|INFO |SuccessStory#PluginDatabaseObject`4:No achievements find for .hack//Infection - 07215d42-3485-410a-90eb-e0e660bdcc63
08-01 12:28:16.715|DEBUG|Extras#ThemeExtras:Pushed "Grid View - Fate-Unlimited Codes"
08-01 12:28:25.592|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(Fate-Unlimited Codes - 7a564d4c-d7ae-44bf-8b66-27bd6f1de5e7)
08-01 12:28:25.592|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.RetroAchievements for Fate-Unlimited Codes - 7a564d4c-d7ae-44bf-8b66-27bd6f1de5e7
08-01 12:28:25.592|WARN |SuccessStory#RetroAchievements:Hash impossible - The file is too long - D:\Games\Emulate\Games\ps2\\Fate-Unlimited Codes (Japan).chd
08-01 12:28:25.592|WARN |SuccessStory#RetroAchievements:No game find for Fate-Unlimited Codes with Sony PlayStation 2 in 10
```

Mind you, in pcsx2 they hash fine, achievements do pop up, so I don't know exactly what is the problem.

**Comment by MangoChocobo** [comment]
Just adding my own logs in here as well. Unsure the issue, got achievements for Dark Cloud, but its failing to get them?

`03-04 16:31:33.209|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(Dark Cloud 2 - 3e7fcd59-c140-42d7-9959-fb839e88da1b)
03-04 16:31:33.209|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.RetroAchievements for Dark Cloud 2 - 3e7fcd59-c140-42d7-9959-fb839e88da1b
03-04 16:31:33.238|WARN |SuccessStory#RetroAchievements:Hash impossible - The file is too long - G:\Emulators\Emulator_Games\ps2\\Dark Cloud 2.iso
03-04 16:31:33.274|INFO |SuccessStory#RetroAchievements:Find for Dark Cloud 2 [25597] / Dark Cloud 2  with Sony PlayStation 2 in 21
03-04 16:31:34.790|WARN |SuccessStory#TrueAchievements:No url for GetEstimateTimeToUnlock()
03-04 16:31:34.790|INFO |SuccessStory#PluginDatabaseObject`4:0/238 achievements find for Dark Cloud 2 - 3e7fcd59-c140-42d7-9959-fb839e88da1b
03-04 16:31:35.301|WARN |SuccessStory#TrueAchievements:No url for GetEstimateTimeToUnlock()`

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-successstory-plugin/commit/be7228f0c7ecb97b98d46a377e00e5ef0b8010ff
