### ISSUE TITLE
Crash problem

### ISSUE THREAD

**Issue by ZimCs** [Lacro59/playnite-successstory-plugin#447]
Seems like the last version cause some problem that makes playnite when is started in fullscreen mode to crash, doesnt appear an error message, just crash, i tried with multiples themes and its the same in all of them

**Comment by binarymelon** [comment]
I was also getting crashes in desktop mode.  There is nothing logged that seemed to indicate any type of issue though.  Disabling or reverting to the previous version has resolved the issue.

**Comment by Lacro59** [comment]
Can you post your playnite.log & extensions.log?

**Comment by binarymelon** [comment]
After upgrading again to 3.1.7 again after downgrading to 3.1.6 to resolve the crash I am no longer having any crashes.  Originally I had upgraded directly from 3.1.5 -> 3.1.7.  Could that have caused the problem?

**Comment by Lacro59** [comment]
Can you try this version?
[playnite-successstory-plugin_3_1_7_dev.zip](https://github.com/user-attachments/files/16013973/playnite-successstory-plugin_3_1_7_dev.zip)

**Comment by binarymelon** [comment]
I upgraded again a few weeks ago and it has been working fine since then.  Not sure what was causing the problem.  At the time someone on discord mentioned there was a common problem with a few plugins that was causing the crash, but I don't remember the specifics.
