### ISSUE TITLE
Achivements not updated for games already in library despite automatic updates being enabled

### ISSUE THREAD

**Issue by Quitch** [Lacro59/playnite-successstory-plugin#451]
SucessStory is correctly loading my achievements for games when they are first imported into my library, but it never updates them again after this.

"Automatically import data when library is updated" is checked, and Playnite is set to update libraries "once a day", but achievements are only added to new games. It's unclear whether this is a limitation by design, or a bug. Manually refreshing SuccessStory for a game via the context menu correctly updates the achievements.

I would very much like Playnite to always update achievements for installed games whenever the library is refreshed, regardless of whether the game's entry has changed.

I have attached my extensions log.

[extensions - Copy.log](https://github.com/Lacro59/playnite-successstory-plugin/files/14025510/extensions.-.Copy.log)

**Comment by Lacro59** [comment]
#471
