### ISSUE TITLE
Extension doesn't find achievements from RetroAchievements

### ISSUE THREAD

**Issue by DelaryHap** [Lacro59/playnite-successstory-plugin#454]
Hello, I have configured SS to work with RA but no matter what game I try to find achievements for, SS isn't finding anything for any game that RA supports. The achievements themselves work in all emulators, and my API key and name are correct in Playnite, but it changes nothing.
 
![image_2024-01-28_170814488](https://github.com/Lacro59/playnite-successstory-plugin/assets/25488267/f6f0829c-7b96-4be7-acee-d28d18d471cd)

![image_2024-01-28_170651796](https://github.com/Lacro59/playnite-successstory-plugin/assets/25488267/c55d276c-b842-43aa-b081-0d27a334923b)

**Comment by MangoChocobo** [comment]
Hey, 

So what you are going to want to do is set everything to their proper platform and not just have everything on them.

This example should help.
![image](https://github.com/Lacro59/playnite-successstory-plugin/assets/25861147/e320c0c3-c13c-4c22-8cb1-09397fe5646b)

**Comment by DelaryHap** [comment]
Oh my god thank you, it finally worked! It's been months, I had lost hope!
