### ISSUE TITLE
Adding achievements manually doesn't work

### ISSUE THREAD

**Issue by GNS7** [Lacro59/playnite-successstory-plugin#458]
I only get this error when trying to add achievements for a new game

![Screenshot 2024-02-14 061108](https://github.com/Lacro59/playnite-successstory-plugin/assets/61403819/d6e2094a-da5d-4b59-9798-29093c325b3f)

and this too, it's in portuguese, but basically means, object reference is not defined for object instance

![image](https://github.com/Lacro59/playnite-successstory-plugin/assets/61403819/95c9a65f-b85a-4265-b834-1115481514c4)

Is there anything I'm doing wrong?

**Comment by AadilValconi** [comment]
I get the same error message, "Object reference" one, when trying to add achievement for a new game on version 3.1.7. 
I downgraded the plugin down to 3.1.5 version and it seems to work.
