### ISSUE TITLE
Error after downloading steam achievements

### ISSUE THREAD

**Issue by robo300** [Lacro59/playnite-successstory-plugin#46]
Hi

Every time after downloading steam achievements I get this error window:
![image](https://user-images.githubusercontent.com/6491821/88097384-592fe500-cb98-11ea-9414-c9d4d548cdba.png)

Also none of steam achievements is seen even that it seems they are fetched:
![image](https://user-images.githubusercontent.com/6491821/88097628-ba57b880-cb98-11ea-9c53-6e3272edc6e8.png)

![image](https://user-images.githubusercontent.com/6491821/88097685-d65b5a00-cb98-11ea-8f8f-f96236e8581e.png)

I've tried refreshing all/recent achievements, every time same situation: error popup, 888 achievements downloaded, no achievements seen

**Comment by Lacro59** [comment]
The response for this problem [here](https://playnite.link/forum/thread-275-post-955.html#pid955).
But I keep your issue for improve the error message and the indicator.

**Comment by robo300** [comment]
@Lacro59 thanks for your response.
It helped now works fine :) Better error message is needed IMO and also information about that steam configuration in instruction
