### ISSUE TITLE
Sync Genshin Impact achievements via tracker

### ISSUE THREAD

**Issue by lxly9** [Lacro59/playnite-successstory-plugin#460]
Hiya, there are a couple of websites that you can track your achievements with, notably paimon.moe and seelie.me. Itd be amazing if there was an option to sync successstory with these sites.

**Comment by elpideus** [comment]
+1

**Comment by Exonymos** [comment]
Hey, can you tell me how to import the achievements. I saw the Genshin Impact Achievement setting in extension setting but no info there.

**Comment by Exonymos** [comment]
> Validation of achievements is manual. - #319

https://github.com/Lacro59/playnite-successstory-plugin/commit/7ace2ed02179f47e8e063bc9e1fbf6f3a05969c6

What about this? From the looks of it, it seem to be possible to add a json file. Is this supposed to come in future update?

**Comment by Lacro59** [comment]
A new game menu for Genshin Impact since last release.

**Comment by Exonymos** [comment]
Hey, there is still no visible option to import the achievement. If I'm missing something, please tell me.

**Comment by lxly9** [comment]
You need to first disable and enable Genshin Impact Achievements in the SuccessStory settings and then there will be a little prompt when clicking on a game\more\successstory\import

**Comment by Exonymos** [comment]
@lxly9 Thanks a lot. 😀
