### ISSUE TITLE
Persistent 419 error

### ISSUE THREAD

**Issue by baluku11** [Lacro59/playnite-successstory-plugin#462]
Hi,

My Success Story is repeatedly showing an authentication error (see image below). I have tried re-authenticating as well as re-installing the extension. New achievements are not being tracked and the extension seems overall unresponsive. I've also attached a log package in case that is of use, but any help or guidance would be appreciated, thanks!

[SuccessStory_2024-02-29.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/14449285/SuccessStory_2024-02-29.zip)

<img width="202" alt="Playnite Error" src="https://github.com/Lacro59/playnite-successstory-plugin/assets/119898281/004d9f6e-b25e-4c33-b6c0-67ff1ba6497f">

**Comment by GreenM4sterPT** [comment]
Well, I also had this problem and I swear I tried to find a solution everywhere, and apparently some people say that the Plugin works for them, not all of them say it works but for example, in my case, it doesn't work either.

And I didn't see anyone talking about a solution or anything like that, nothing at all. But the fact that I heard people saying that the plugin works and I did everything they said and the official guide sites said to do and still got this error, made me think that maybe the new version (3.1.7) was everything was bugged, and I got it right.

If you install version (3.1.5) of SuccesStory, it works minimally better. So for now I recommend you and everyone who has this problem to install this version (3.1.5), version (3.1.6) also has some bugs. For me it worked better (3.1.5) and I literally spent a whole day figuring it out and so far it's working well, the only thing that doesn't work well is the update but at least it shows the achievements and manually you can edit it.

Now we have to wait until the version (3.1.8) comes out.

Link - https://github.com/Lacro59/playnite-successstory-plugin/releases/tag/v3.1.5

**Comment by Lacro59** [comment]
Can you try this?
https://github.com/Lacro59/playnite-successstory-plugin/issues/479#issuecomment-2191342743
