### ISSUE TITLE
Failed to Parse - "Unauthenticated." - "status":419,"code":"unauthorized","title":"Unauthenticated"

### ISSUE THREAD

**Issue by szwenger** [Lacro59/playnite-successstory-plugin#463]
I tried to do almost everything, but it just won't function. The achievements are not getting imported and I always get the following error message:
> SuccessStory
> Failed to Parse
> {"message": "Unauthenticated.", "errors":
> [{"status":419,"code":"unauthorized","title":"Unauthenticated"}]}

Logfile is attached

[SuccessStory_2024-03-01.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/14455027/SuccessStory_2024-03-01.zip)

**Comment by GreenM4sterPT** [comment]
Well, I also had this problem and I swear I tried to find a solution everywhere, and apparently some people say that the Plugin works for them, not all of them say it works but for example, in my case, it doesn't work either.

And I didn't see anyone talking about a solution or anything like that, nothing at all. But the fact that I heard people saying that the plugin works and I did everything they said and the official guide sites said to do and still got this error, made me think that maybe the new version (3.1.7) was everything was bugged, and I got it right.

If you install version (3.1.5) of SuccesStory, it works minimally better. So for now I recommend you and everyone who has this problem to install this version (3.1.5), version (3.1.6) also has some bugs. For me it worked better (3.1.5) and I literally spent a whole day figuring it out and so far it's working well, the only thing that doesn't work well is the update but at least it shows the achievements and manually you can edit it.

Now we have to wait until the version (3.1.8) comes out.

Link - https://github.com/Lacro59/playnite-successstory-plugin/releases/tag/v3.1.5

**Comment by szwenger** [comment]
@GreenM4sterPT Okay, I think it worked now with 3.1.5! Thanks a lot!
Will be waiting for 3.1.8 :)

**Comment by AminSinval** [comment]
Hi. I have the same problem. I updated but it didn't work. What should I do?

**Comment by Lacro59** [comment]
@AminSinval 
Can you try this version?
[playnite-successstory-plugin_3_4_1.zip](https://github.com/user-attachments/files/19712656/playnite-successstory-plugin_3_4_1.zip)
