### ISSUE TITLE
RetroAchievements for SNES are pulling game list from Panasonic 3DO

### ISSUE THREAD

**Issue by unfw** [Lacro59/playnite-successstory-plugin#465]
When trying to update RetroAchievements for Super Mario World, I am finding that the only game list that is being pulled is the Panasonic 3DO game list. This is causing the plugin to not find the game unless it's actually a 3DO game.

`04-03 14:42:17.887|INFO |SuccessStory#PluginDatabaseObject`4:RefreshNoLoader(Super Mario World - b46a04aa-c6cb-4285-92a1-450397c50ff2)
04-03 14:42:17.887|INFO |SuccessStory#PluginDatabaseObject`4:Used SuccessStory.Clients.RetroAchievements for Super Mario World - b46a04aa-c6cb-4285-92a1-450397c50ff2
04-03 14:42:17.916|WARN |SuccessStory#RetroAchievements:No game find for Super Mario World with cdd3c8c37322978ca8669b34bc89c804 in PlatformType.All
04-03 14:42:17.916|WARN |SuccessStory#RetroAchievements:No game find for Super Mario World with ec7eb7e3f2d4e1a8290491d629ed7456 in PlatformType.SNES
04-03 14:42:17.929|WARN |SuccessStory#RetroAchievements:No game find for Super Mario World with cdd3c8c37322978ca8669b34bc89c804 in PlatformType.SNES
04-03 14:42:17.929|WARN |SuccessStory#RetroAchievements:No game find for Super Mario World with cb57c0e998748f3b542e9e0d5faacd7d in PlatformType.Sega_CD_Saturn
04-03 14:42:17.929|WARN |SuccessStory#RetroAchievements:No game find for Super Mario World with cdd3c8c37322978ca8669b34bc89c804 in PlatformType.SNES
04-03 14:42:17.929|WARN |SuccessStory#RetroAchievements:No game find for Super Mario World with 329727b2aacb725025934fd79e72af97 in PlatformType.Sega_CD_Saturn
04-03 14:42:17.942|WARN |SuccessStory#RetroAchievements:No game find for Super Mario World with Nintendo SNES in 43
04-03 14:42:17.942|INFO |SuccessStory#PluginDatabaseObject`4:No achievements find for Super Mario World - b46a04aa-c6cb-4285-92a1-450397c50ff2`

Console Id 43 is the Panasonic 3DO

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-successstory-plugin/commit/f123fd63714c16774a74e4bd0c7d1ab9e7b167d4
