### ISSUE TITLE
Baldur's Gate 3 Achievements not appearing

### ISSUE THREAD

**Issue by xCeeTee** [Lacro59/playnite-successstory-plugin#466]
This only happens with BG3. Even when I try to do it manually, it just closes the prompt instantly. BG3 had some weird things going on when it came to the Steam library extension, like it refused to start the game. That got fixed but achievements still aren't appearing. They are appearing for other games, however.

**Comment by tarakbumba** [comment]
I had similar issue. Success Story shows 54 achievements for BG3 and altough I had 23 of them it shows zero. I don't have any other games played from steam right now so I can't check if it's a problem with retrieving steam achievements or not. I use open account method and don't use api key.

**Comment by chukrum47** [comment]
I have the same issue. I use the open account method without an API key, an none of my achievements will sync at all.

**Comment by PereChapi** [comment]
I've the same problem (public profil but no API key defined)
I finally add API key with my public profil and syncing now work (if that can help you)

**Comment by tarakbumba** [comment]
> I've the same problem (public profil but no API key defined) I finally add API key with my public profil and syncing now work (if that can help you)

Thank you for your contribution. On fact, I don't want to use API key. I've read from some sources that enabling API key on steam may led to security issues. I don't want to put my steam account in danger. Also, extension developer clearly states that this would work without API key. So, this is a bug and needs to be addressed.

**Comment by chukrum47** [comment]
> > I've the same problem (public profil but no API key defined) I finally add API key with my public profil and syncing now work (if that can help you)
> 
> Thank you for your contribution. In fact, I don't want to use API key. I've read from some sources that enabling API key on steam may led to security issues. I don't want to put my steam account in danger. Also, extension developer clearly states that this would work without API key. So, this is a bug and needs to be addressed.

I second this too. I don't want to use an API key for this.

**Comment by TheDarkSpock** [comment]
This API issue with Steam not syncing achievements has been going on for a least a year+ now. I keep holding out hope it will be fixed, cause otherwise this extension is pretty useless for me.

**Comment by Lacro59** [comment]
Can you try this?
https://github.com/Lacro59/playnite-successstory-plugin/issues/479#issuecomment-2191342743
