### ISSUE TITLE
Hidden achivements still show a title and icon

### ISSUE THREAD

**Issue by cromefire** [Lacro59/playnite-successstory-plugin#468]
Hidden achievements still seem to show their title and icon, which can spoil important story elements for many games (example is less severe, but of course I didn't want to spoil myself, so I screenshotted to one I fully read anyway, but I got a quick glimpse of some that looked like they basically spoiled most of the story):
![image](https://github.com/Lacro59/playnite-successstory-plugin/assets/26320625/80655734-8089-4c0a-bf20-39e8f05e4db6)
It doesn't seem like there's any way to hide that as well, but it would be good if there was an option (icon might not be as severe, but title definitely is, maybe 2 options would make sense there and replace the icon just with some generic icon that shows it's hidden, like a strucken through eye)

**Comment by azuravian** [comment]
While the solution you're looking for doesn't currently exist, there is a semi-workaround that will set all locked achievements (hidden or not) to a single custom icon.  Find an icon you like, and add it on the Misc. tab under "Locked Icon Configuration".  Obviously, this has the downside of showing that icon for all achievements that aren't unlocked, but I'd prefer that over spoilers.

**Comment by cromefire** [comment]
Yeah but I think the title is definitely more severe and hiding the icon isn't doing that much. My workaround currently is just to look on steam directly instead as long as I'm not finished with the Story of a game.

**Comment by cromefire** [comment]
Way better with the latest release, thanks
