### ISSUE TITLE
Error When Importing Games Marked Private

### ISSUE THREAD

**Issue by burnpsy** [Lacro59/playnite-successstory-plugin#469]
This add-on sends an error if a game is added to Playnite that is marked as private on Steam using [the recent Steam feature that allows me to do so](https://help.steampowered.com/en/faqs/view/1150-C06F-4D62-4966).

Here is part of the relevant bit of extensions.log, for hopefully obvious reasons I am intentionally leaving out the lines directly before them that list the privated games by name:
> 01-04 17:19:27.097|INFO |SuccessStory#SteamAchievements:GetAchievements() - IsLocal : False, IsManual : False, HasApiKey: True, SteamIsPrivate: False
> 01-04 17:19:27.301|INFO |SuccessStory#SteamAchievements:Old
> 01-04 17:19:27.439|WARN |SuccessStory#SteamAchievements:Steam profil is private
> 01-04 17:19:27.439|ERROR|SuccessStory#Common:Error on GetPlayerAchievements()|G:\GitHub\Lacro59\playnite-successstory-plugin\source\Clients\SteamAchievements.cs|680
> System.Net.WebException: The remote server returned an error: (403) Forbidden.

I'm not sure if anything can be done to get the achievement data in this situation, but at the very least there needs to be a rewording of the error message; my Steam account is not private, but the warning is saying that it is. No, the specific games are private, which is intentional.

**Comment by epeternally** [comment]
Are you using an API key? If you can't access the achievement list even with a key, I feel like that's a bug on Steam's end.

**Comment by burnpsy** [comment]
Yes, I am using an API key.

**Comment by Lacro59** [comment]
Can you try this?
https://github.com/Lacro59/playnite-successstory-plugin/issues/479#issuecomment-2191342743

**Comment by burnpsy** [comment]
> Can you try this? [#479 (comment)](https://github.com/Lacro59/playnite-successstory-plugin/issues/479#issuecomment-2191342743)

Installed this. Behaviour is as follows when used on games marked private:

- If it's a game that has achievements already imported, it will keep the achievement list and then set the achievements to none unlocked (I tested this on a few game where I had achievements previously imported before the games were marked as private).
- If it's a game that does have achievements, but they were never imported into Playnite before the game was marked Private, it will not import the list of achievements; the game is simply treated as if there are no achievements for that game.
- If I try to view achievements, an "object reference not set to an instance of an object" error is thrown.

The error noted in my OP does not show itself when using the test version.

If you go with this as the solution, I'd like to request a button to clear the SuccessStory data for selected games (so I simply have no achievement list for them, rather than it saying my progress is 0).

**Comment by Lacro59** [comment]
@burnpsy, can you post your extension.log?

**Comment by burnpsy** [comment]
Attached.
[extensions.log](https://github.com/user-attachments/files/16447429/extensions.log)

When I tried reproducing the object reference error I saw in my last message, I noticed it did not result in any note in the log, and also refreshing the data on an affected game fixed the issue.
