### ISSUE TITLE
SuccessStory Not Updating Achievements Automatically

### ISSUE THREAD

**Issue by BiggSlime** [Lacro59/playnite-successstory-plugin#471]
As of now I have the "import all of my achievements whenever my library is updated" setting turned on. So far, SuccessStory has never imported any achievements on its own. The only way for me to get SuccessStory to update my achievement list is to manually refresh data.

**Comment by miguelccoelho** [comment]
Just wanted to add that I have the same issue. Maybe even getting a "update all" would be a good workaround for now.

**Comment by Lacro59** [comment]
This option imports only the achievements for the new game added in library.
But you have more manual import options in Playnite menu > Extensions > SuccessStory > Download plugin data...
![image](https://github.com/user-attachments/assets/227900ce-c2e8-4942-affa-a44037e0267d)
