### ISSUE TITLE
Xbox 360 achievements 

### ISSUE THREAD

**Issue by Koriebonx98** [Lacro59/playnite-successstory-plugin#473]
I just need some help with my script. 

Script struggles to write from txt to json and then should replace original json

so script should in order;
Copy json, write achievement names from json to txt, read Xenia log for “unlocked achievements” & add time stamp to txt file next to achievement name, then update the copied json with DateUnlocked data from txt file, replace original json. 

This should then in theory on a library update, it should update the achievements with the data from Xenia log? To get around how to obtain the json files I would add achievement to the game first via success story, and then script wouldn’t have the issue. Would any json file with link to achievement pictures and achievement names work? Or does it have to be compressed and the same structure?

I did have a script before but Xenia updated the log to show achievements in a table, the script before worked and updated the achievements.

I know with your help we could avoid using a txt file,  and write straight to the original json? Making script less complex.

I have script run when Xenia closes but I think it should work if ram while emu runs, this could be more accurate for achievement unlocked time.

if script works we could then possibly push for the playnite devs to add to the Xenia profile?

**Comment by Lacro59** [comment]
Manually updating via json #453
