### ISSUE TITLE
[Feature Request] Manually Set RetroAchievements Game ID

### ISSUE THREAD

**Issue by epeternally** [Lacro59/playnite-successstory-plugin#475]
Games lookup through the RetroAchievements API in SuccessStory has been unreliable for a long time, with maddening "no game find" errors even with perfectly matching names and hashes. At the moment, only arcade games are working for me. Everything else fails.

It seems like the problem could be circumvented by giving the user an option to enter a RetroAchievements ID number, and then import achievements from that entry regardless of the hash/search check. Each game on RetroAchievements is identified with a unique number (11331 = Tony Hawk's Pro Skater), so there should be no chance of picking up the wrong game.

**Comment by Lacro59** [comment]
#487
