### ISSUE TITLE
RetroAchievments not showing Associated Platforms

### ISSUE THREAD

**Issue by Plexxl** [Lacro59/playnite-successstory-plugin#476]
It just isn't showing up, I have reinstalled, this is version 3.1.7
![image](https://github.com/Lacro59/playnite-successstory-plugin/assets/38474413/5ac833c9-81da-434d-a4c4-b206a6c36b50)

**Comment by xCeeTee** [comment]
Can I ask have you done a full Playnite reinstall or just SuccessStory? Also quickly try another theme. It'll just help eliminate some issues that might be caused by something else, as I know the dev for this plugin is stretched quite thin.

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-successstory-plugin/commit/f123fd63714c16774a74e4bd0c7d1ab9e7b167d4
