### ISSUE TITLE
[Feature Request] EmuLibrary Integration

### ISSUE THREAD

**Issue by martindezotti** [Lacro59/playnite-successstory-plugin#477]
Right now when scanning games from the EmuLibrary extension to pull Retroachivements sets creates an empty json, you also don't have the option to manually scan it because it counts as a store.

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-successstory-plugin/commit/8c26353ceab3fa8bd99730fc4a031bd92c36bd3a
