### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Staz0r** [Lacro59/playnite-successstory-plugin#478]
I got this warning notification everytime I open playnite, and it also doesnt show the achievements for games
![image](https://github.com/Lacro59/playnite-successstory-plugin/assets/51358327/2c14f691-9f6c-43ee-b014-5c66a48984fe)

It seems to be attempting to get file through

Here is the extensions.log
場所 SuccessStory.SuccessStory.WindowBase_LoadedEvent(Object sender, EventArgs e) 場所 G:\GitHub\Lacro59\playnite-successstory-plugin\source\SuccessStory.cs:行 221
24-05 02:29:40.425|ERROR|SuccessStory#Common:Error on WindowBase_LoadedEvent()|G:\GitHub\Lacro59\playnite-successstory-plugin\source\SuccessStory.cs|221
System.NullReferenceException: オブジェクト参照がオブジェクト インスタンスに設定されていません (Object reference not set to an instance of an object)。
   場所 SuccessStory.Clients.SteamAchievements..ctor() 場所 G:\GitHub\Lacro59\playnite-successstory-plugin\source\Clients\SteamAchievements.cs:行 63
   場所 SuccessStory.Services.SuccessStoryDatabase.get_AchievementProviders() 場所 G:\GitHub\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryDatabase.cs:行 43
   場所 SuccessStory.SuccessStory.WindowBase_LoadedEvent(Object sender, EventArgs e) 場所 G:\GitHub\Lacro59\playnite-successstory-plugin\source\SuccessStory.cs:行 221
24-05 02:31:26.783|ERROR|SuccessStory#Common:Error on WindowBase_LoadedEvent()|G:\GitHub\Lacro59\playnite-successstory-plugin\source\SuccessStory.cs|221
System.NullReferenceException: オブジェクト参照がオブジェクト インスタンスに設定されていません (Object reference not set to an instance of an object)。
   場所 SuccessStory.Clients.SteamAchievements..ctor() 場所 G:\GitHub\Lacro59\playnite-successstory-plugin\source\Clients\SteamAchievements.cs:行 63
   場所 SuccessStory.Services.SuccessStoryDatabase.get_AchievementProviders() 場所 G:\GitHub\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryDatabase.cs:行 43
   場所 SuccessStory.SuccessStory.WindowBase_LoadedEvent(Object sender, EventArgs e) 場所 G:\GitHub\Lacro59\playnite-successstory-plugin\source\SuccessStory.cs:行 221

**Comment by Rizhikk** [comment]
The same thing.. How to solve it?  
![Снимок экрана 2024-05-24 1123526](https://github.com/Lacro59/playnite-successstory-plugin/assets/150350281/9bb42c91-3aa6-4678-aede-c822f45d49c3)


![Снимок экрана 2024-05-25 22013012](https://github.com/Lacro59/playnite-successstory-plugin/assets/150350281/5acec1e5-ec7d-406b-bba6-3a1d125a1b6c)
The api key is not saved when you enter it. It disappears when you exit the window*

**Comment by sunsetHue** [comment]
Same error notification related to Steam API key but with different logs. 

I don't even use Steam achievements. I used manual ones until this error starting showing a while ago that seems to stop you from adding any new Exophase achievements too. Pre-existing achievements added before the error still show and work fine.

Section from **extentions.log**
```
31-05 02:19:32.368|WARN |SuccessStory#SteamApi:No SteamLibrary configuration found
31-05 02:19:32.368|ERROR|SuccessStory#Common:Error on GetManual()|G:\GitHub\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryDatabase.cs|109
System.NullReferenceException: Object reference not set to an instance of an object.
   at SuccessStory.Clients.SteamAchievements..ctor() in G:\GitHub\Lacro59\playnite-successstory-plugin\source\Clients\SteamAchievements.cs:line 63
   at SuccessStory.Views.SuccessStoreGameSelection..ctor(Game game) in G:\GitHub\Lacro59\playnite-successstory-plugin\source\Views\SuccessStoreGameSelection.xaml.cs:line 40
   at SuccessStory.Services.SuccessStoryDatabase.GetManual(Game game) in G:\GitHub\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryDatabase.cs:line 109
```

**Comment by Lacro59** [comment]
Can you try this?
https://github.com/Lacro59/playnite-successstory-plugin/issues/479#issuecomment-2191342743

**Comment by Staz0r** [comment]
> Can you try this? [#479 (comment)](https://github.com/Lacro59/playnite-successstory-plugin/issues/479#issuecomment-2191342743)
I forgot to mention it but I've tried it and it is working properly now
