### ISSUE TITLE
Extension is dead

### ISSUE THREAD

**Issue by AleKing31** [Lacro59/playnite-successstory-plugin#479]
Is this extension dead?

**Comment by ElTioRata** [comment]
Thought the same, I installed it today and I can't get it to work with RAcheevos and RPCS3...

**Comment by PatrykJWisniewski** [comment]
Not dead. Pretty sure there just isn't enough time between the people who contribute to this project to be 100% on top of things all the time.

**Comment by Lacro59** [comment]
It's not just a question of time.
At the moment, I only have my professional PC and it blocks a lot of things.
This prevents me from working on some of my extensions.

**Comment by Jeshibu** [comment]
Is this likely to be a long-term thing? There's a few serious bugs now. What's the best way forward? Pull requests? Forks?

**Comment by AleKing31** [comment]
> It's not just a question of time. At the moment, I only have my professional PC and it blocks a lot of things. This prevents me from working on some of my extensions.

How sad, I hope everything gets better

**Comment by Lacro59** [comment]
This is a test version for Steam achievements.
Can you test if you have a problem with Steam?
Be careful if you post a log file because it is a debug version with potential personal information.
[playnite-successstory-plugin_3_1_7_dev.zip](https://github.com/user-attachments/files/15986418/playnite-successstory-plugin_3_1_7_dev.zip)

**Comment by xXThiagoReisXx** [comment]
> Owner

Thanks, this one worked for my retroachievements!!

**Comment by xXThiagoReisXx** [comment]
> This is a test version for Steam achievements. Can you test if you have a problem with Steam? Be careful if you post a log file because it is a debug version with potential personal information. [playnite-successstory-plugin_3_1_7_dev.zip](https://github.com/user-attachments/files/15986418/playnite-successstory-plugin_3_1_7_dev.zip)

Thanks, this one worked for my retroachievements!!

**Comment by polygonnedpotato** [comment]
> This is a test version for Steam achievements.
> 
> Can you test if you have a problem with Steam?
> 
> Be careful if you post a log file because it is a debug version with potential personal information.
> 
> [playnite-successstory-plugin_3_1_7_dev.zip](https://github.com/user-attachments/files/15986418/playnite-successstory-plugin_3_1_7_dev.zip)

i use it and it does not show my unlocked steam achievements.

**Comment by Lacro59** [comment]
@polygonnedpotato 
What is the Steam configuration in the plugin?

**Comment by OdinIsLord** [comment]
> > This is a test version for Steam achievements.
> > Can you test if you have a problem with Steam?
> > Be careful if you post a log file because it is a debug version with potential personal information.
> > [playnite-successstory-plugin_3_1_7_dev.zip](https://github.com/user-attachments/files/15986418/playnite-successstory-plugin_3_1_7_dev.zip)
> 
> i use it and it does not show my unlocked steam achievements.

You'd have to set your game details to public and total uncheck the option to disable playtime visibility. You also have to use your API key too, then restart Playnite and the progress should update.

I stopped using SuccesStory with Steam. Why am I giving away my API if I still have to show the games I own and my playtime/achievement? I don't know if this is a bug but sacrificing my privacy like this is just not worth it for displaying trophies locally in a game browser.
