### ISSUE TITLE
Steam profile set to public but being told its set to private

### ISSUE THREAD

**Issue by MapleEmbers** [Lacro59/playnite-successstory-plugin#484]
I have set my profile to public and it was working fine for a long time but for the last week or so, I have not been able to connect to my steam profile with SucessStory? it returns a 403 error and tells me that its not set to public, see screenshot

![image](https://github.com/Lacro59/playnite-successstory-plugin/assets/138142803/7594121a-51e5-4d20-b109-fb4156aece29)

**Extensions log**
[extensions.log](https://github.com/user-attachments/files/16138632/extensions.log)

**Comment by Lacro59** [comment]
Can you try this?
https://github.com/Lacro59/playnite-successstory-plugin/issues/479#issuecomment-2191342743

**Comment by MapleEmbers** [comment]
That has removed the error but now shows me as having 0 achievements?

**Comment by Lacro59** [comment]
@MapleEmbers, can you post your extensions.log?

**Comment by MapleEmbers** [comment]
Ticking profile private then unticking it gave me an authenticate button, I went through that and it seems to have updated to be working for now. here is my extension log to see if you can work out the cause from before.

[extensions.log](https://github.com/user-attachments/files/16511910/extensions.log)
