### ISSUE TITLE
RetroAchievements have stopped populating, all achievements disappeared when I made it download all data again

### ISSUE THREAD

**Issue by xCeeTee** [Lacro59/playnite-successstory-plugin#485]
Is this plugin no longer being updated? Because I still have the bug affecting Baldur's Gate 3 achievements. It seems like something new is breaking with the plugin every week. I previously found a fix to this issue but it's clearly stopped working too.

**Comment by xCeeTee** [comment]
|ERROR|SuccessStory#Common:Error on GetGameInfoAndUserProgress()|G:\GitHub\Lacro59\playnite-successstory-plugin\source\Clients\RetroAchievements.cs|819
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

**Comment by DrAnonym666** [comment]
same here

**Comment by xCeeTee** [comment]
> same here

I've now discovered it's RetroAchievements' API isn't working properly. Their servers are getting overloaded and when that happens the API stops functioning. They're looking into fixing it ASAP. I guess the popularity of the community has peaked.
