### ISSUE TITLE
Success Story not working with RPCS3

### ISSUE THREAD

**Issue by Cyclone1995** [Lacro59/playnite-successstory-plugin#486]
I downloaded Success Story and it's worked fine with every other apps with achievement but Rpcs3 achievements are not loading at all... Even after put the right path location "Rpcs3/dev_hdd0/home/00000001" Does it even work? Or what am i doing wrong?

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-successstory-plugin/commit/9782cceed703e5ad10ebbf54308ca88ca1bb60d5
