### ISSUE TITLE
RetroAchievements associated platforms messed up.

### ISSUE THREAD

**Issue by NoShotz** [Lacro59/playnite-successstory-plugin#488]
For whatever reason a bunch of platforms in the RetroAchievements associated platforms section have every platform checked for them, which prevents searching for achievements on all platforms, can be fixed manually, but quite annoying.

**Comment by xXThiagoReisXx** [comment]
Besides that, were you able to get the extension running? 

I did the manual association but when i try to download data it says "Object reference not set to an instance of an object".

**Comment by NoShotz** [comment]
Yes, other than needing to fix the associated platforms, the extension is working fine.

**Comment by NoShotz** [comment]
I already had the latest version at the time, I guess the fix you pushed a month ago didn't fix associated platforms that were already messed up by the original bug.
