### ISSUE TITLE
expose total achievements score across all platforms for fullscreen themes.

### ISSUE THREAD

**Issue by name1esshero** [Lacro59/playnite-successstory-plugin#489]
I was speaking with SaVant the other day and asked about displaying a gamerscore next to profile pictures in fullscreen themes. when discussing it he said "You can access these data only with plugin, successtory does not access total count, it has these data only in desktop mode by counting all of them, not exposed for fullscreen".
So Im formally requesting this for fullscreen theme usage so we can have gamerscores shown in fullscreen mode.

**Comment by Lacro59** [comment]
Actually, there isn't "gamerscore" from achievements (#249).
If I understand your request, you want the total unlock achievements expoxed.

**Comment by name1esshero** [comment]
> Actually, there isn't "gamerscore" from achievements (#249). If I understand your request, you want the total unlock achievements expoxed.

yes.  just the number of total achievements from all games exposed. if multipled by a number like 5 it could allow for a gamerscore where each achievement is worth 5 points and could be a really nice touch on themes to have.

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-successstory-plugin/wiki/Addition-in-a-custom-theme#plugin-data-for-game-selected
