### ISSUE TITLE
Can't load any achievements RPCS3

### ISSUE THREAD

**Issue by mickaelxd** [Lacro59/playnite-successstory-plugin#491]
**Describe the bug**
I'm having trouble integrating RPCS3 with SuccessStory. I've checked the RPCS3 box and filled in the path to my folder, but it doesn't show any trophies. The logs indicate that the plugin loads but doesn't find any trophies.

**To Reproduce**
1. Open Playnite.
2. Go to SuccessStory settings.
3. Check the RPCS3 integration box.
4. Fill in the path to the RPCS3 directory: C:\Games\rpcs3\dev_hdd0\home\00000001
5. Try to view trophies for a game (e.g., LittleBigPlanet or Deadpool).

**Expected behavior**
Trophies and achievements for RPCS3 games should be displayed in Playnite through the SuccessStory extension.

**Screenshots**
N/A

**Extensions log**
[extensions.log](https://github.com/user-attachments/files/16536357/extensions.log)

**Comment by Lacro59** [comment]
Not loading RPCS3 achievements again #347
