### ISSUE TITLE
Disable api usage gone?

### ISSUE THREAD

**Issue by CinnamonShaey** [Lacro59/playnite-successstory-plugin#492]
As the title says, is this feature gone? I have looked for an hour or so and can't figure it out, i dont have the means to get a website just to get an api key i just want it to pull my steam achievements

**Comment by Lacro59** [comment]
Can you try this?
https://github.com/Lacro59/playnite-successstory-plugin/issues/479#issuecomment-2191342743

**Comment by CinnamonShaey** [comment]
The achievements work, it's the widget in Star page that don't show anything
