### ISSUE TITLE
Playnite memory usage keeps increasing with each launch of the extension

### ISSUE THREAD

**Issue by darklinkpower** [Lacro59/playnite-successstory-plugin#5]
Tested with version 0.4a

Before launching
![imagen](https://user-images.githubusercontent.com/1389286/82914352-07226880-9f35-11ea-90e1-148a1168936c.png)

After 1st launch
![imagen](https://user-images.githubusercontent.com/1389286/82914442-202b1980-9f35-11ea-8b68-72e311e7cde1.png)

After 2nd launch
![imagen](https://user-images.githubusercontent.com/1389286/82914505-35a04380-9f35-11ea-922b-61c33f9b8d0f.png)

After 3rd launch
![imagen](https://user-images.githubusercontent.com/1389286/82914560-4a7cd700-9f35-11ea-8074-f4a679c709ad.png)

**Comment by Lacro59** [comment]
Try with the new version 0.6a.

**Comment by darklinkpower** [comment]
Test with version 0.6a. All screenshots taken after Success Story window has been closed. Memory increase seems to be slightly less each time it's launched again but it's still there

Before launching
![imagen](https://user-images.githubusercontent.com/1389286/84227715-b8cfa680-aaaa-11ea-9193-11e75ee66e4c.png)

After 1st launch
![imagen](https://user-images.githubusercontent.com/1389286/84227762-d4d34800-aaaa-11ea-8a64-049dea0d1832.png)

After 2nd launch
![imagen](https://user-images.githubusercontent.com/1389286/84227778-e0267380-aaaa-11ea-9c48-706e9e66bfeb.png)

After 3rd launch
![imagen](https://user-images.githubusercontent.com/1389286/84227799-ed436280-aaaa-11ea-9bff-5d691b17c228.png)
