### ISSUE TITLE
Death Stranding Director's Cut must be (incorrectly) named in order for it to work

### ISSUE THREAD

**Issue by Arstidir** [Lacro59/playnite-successstory-plugin#502]
Hey :)

Success Story can not find Death Stranding Director's Cut under its right name from the Epic Games Store. 
The apostrophe in Director's is the problem. 
If you remove the apostrophe, it works. However, it must stay removed permanently.

It's not a big problem, but I just wanted to point it out in case others are wondering why it doesn't work for them. Maybe the issue can be easily fixed. 

And by the way: Are you still planning to add support for Ubisoft Connect?

Thank you for your work on SuccessStory! :)

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-successstory-plugin/pull/494
