### ISSUE TITLE
SuccessStory Value Can't be Null bug

### ISSUE THREAD

**Issue by arm0ureddev1l** [Lacro59/playnite-successstory-plugin#503]
Got this bug when running the new version of SuccessStory for the first time.

<img width="190" alt="SuccessStory Null bug" src="https://github.com/user-attachments/assets/f5c334cf-5440-4fe6-a6ea-dc298cbd7089">

I have also attached the extension.log file for you.

[extensions.log](https://github.com/user-attachments/files/16607857/extensions.log)

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/47d444c7beee619b85c03845d8eb346d6e2a6625
