### ISSUE TITLE
Steam has not been correctly configured. options are blank.

### ISSUE THREAD

**Issue by triadne** [Lacro59/playnite-successstory-plugin#508]
"Steam has not been correctly configured in settings" error message. click on error message, success story settings open. expand "Enable Steam achievements" and there is just a tickbox and nothing else.  There are no options to configure. This error happens every time Playnite opens.

**Screenshots**
![image](https://github.com/user-attachments/assets/930c3298-71be-45dd-83db-b8b50cd367d6)

**Extensions log**
[extensions.log](https://github.com/user-attachments/files/16636957/extensions.log)

**Comment by meltdown0382** [comment]
I'm experiencing the same behaviour (Playnite 10.34, SuccessStory 3.2). Steam Achievements don't seem to be the only issue though, as others posted. I disabled those, still can't complete a Playnite library update (EPIC for example) because SuccessStory is getting stuck processing.

**Comment by oscilloscopa** [comment]
for steam and epic you have to click on  the last tab (libraries) in the settings. they got reset with the update but i filled them back in and everything works fine again for me

**Comment by meltdown0382** [comment]
Thx, that did it for me, too. Still get a "SuccessStory - Value cannot be NULL - parameter name Source" message and the box as the OP stated is blank, but I can live with that.

**Comment by Lacro59** [comment]
fixed with last release
