### ISSUE TITLE
New data import

### ISSUE THREAD

**Issue by mulano1977** [Lacro59/playnite-successstory-plugin#510]
[SuccessStory_2024-08-17.zip](https://github.com/user-attachments/files/16642337/SuccessStory_2024-08-17.zip)
I have the problem that this add-on re-reads all the data every time I start Playnite. I now have over 1500 games in the library. This means that reading the data sometimes takes 15 minutes. During this time I cannot use Playnite. I have had this problem since the last update of Playnite a few days ago. I have already uninstalled and reinstalled the plug-in, with the same result.

**Comment by Carighan** [comment]
I also have this problem. As a workaround, I disabled SuccessStory importing data after every library update, though this merely moves the problem to whenever I do **those**.

**Comment by Lacro59** [comment]
Can you post your extension.log?

**Comment by Kryeker** [comment]
I think the error is here https://github.com/Lacro59/playnite-successstory-plugin/blob/db58665e263abd52270c5119daf648b225ff9aff/source/SuccessStory.cs#L1124 

disabling “Automatically import for installed games” in the settings fixed it

**Comment by ccrowles** [comment]
> disabling “Automatically import for installed games” in the settings fixed it

Can confirm that this fixed it for me too, as a temporary workaround.

**Comment by mulano1977** [comment]
> Can you post your extension.log?

is attached to my post

**Comment by ethansshaw** [comment]
I have the same issue.

**Comment by stevietv** [comment]
same issue here, attached are my extension.log if you need it
[extensions.log](https://github.com/user-attachments/files/16697937/extensions.log)
