### ISSUE TITLE
How to stop achievements from appearing all bronze

### ISSUE THREAD

**Issue by FoxyCantCode** [Lacro59/playnite-successstory-plugin#511]
Hey, all achievements show as bronze in themes like PS5reborn and PS5ish where it shows trophies

![image](https://github.com/user-attachments/assets/5ff496af-1363-49e2-813c-bc5a84abbe6d)

on Desktop, going into the successstory tag, all achievements as common, uncommon or rare like they should. How do I show that in fullscreen themes

![image](https://github.com/user-attachments/assets/48a9274a-4402-44aa-9b64-2a5cb5ff1ac8)

I do not if it is a bug

**Comment by Lacro59** [comment]
New elements for theme in [https://github.com/Lacro59/playnite-successstory-plugin/wiki/Addition-in-a-custom-theme](url)
