### ISSUE TITLE
SuccessStory dosen't automatically add earned acheviements after game is closed

### ISSUE THREAD

**Issue by arm0ureddev1l** [Lacro59/playnite-successstory-plugin#512]
SuccessStory is no longer able to sync unlocked acheivements from the game automatically upon exiting. I looked into the extension.log file and found this:

> 18-08 20:06:16.912|INFO |SuccessStory#SuccessStoryDatabase:RefreshNoLoader(Yakuza 0 - 91c0f0bf-720a-44ec-8741-91367fc417a9 - GOG)
> 18-08 20:06:16.912|INFO |SuccessStory#SuccessStoryDatabase:Used SuccessStory.Clients.GogAchievements for Yakuza 0 - GOG - GOG - PC (Windows)
> 18-08 20:06:17.210|ERROR|SuccessStory#Common:Error on GetAchievements()|C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\Gog\GogApi.cs|308
> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at CommonPluginsShared.Web.<DownloadStringData>d__15.MoveNext() in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsShared\Web.cs:line 648

When manually refreshing everything works fine.
[extensions.log](https://github.com/user-attachments/files/16651427/extensions.log)

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/8b03c2f11fe9f76566197b831418d39457b1c177
