### ISSUE TITLE
SuccessStory downloads data from installed games on every startup

### ISSUE THREAD

**Issue by Judassem** [Lacro59/playnite-successstory-plugin#527]
**Describe the bug**
This started about a week ago. There was an update that was supposed to fix it but the problem is still there. I have 71 installed games so it takes a long time during each start up.

**To Reproduce**
Steps to reproduce the behavior: It happens when Playnite is run for the first time.

**Expected behavior**
It shouldn't do this every time I turn on my computer.

**Screenshots**
Attached

**Extensions log**
[extensions.log](https://github.com/user-attachments/files/16910254/extensions.log)
![playnite](https://github.com/user-attachments/assets/d38d6a1a-df45-485d-989a-603ebf75a7b5)

**Comment by Dagirhuin** [comment]
I follow also gives me the same problem!

**Comment by Judassem** [comment]
> Same, I am pretty sure it's not intended and started happening after the last update.

Mine started before the update. I thought the update would fix it but it didn't do anything.

**Comment by Gweg83** [comment]
> I also had this issue before update, but it was more sporadic and random, now it's every time I open playnite (auto startup) it will start downloading success story data. So you are correct.

Hello, same for me

**Comment by WingedAsarath** [comment]
I just came here to add that I am also having the exact same issue; it's now happening every single day when Playnite automatically launches at my PC startup.

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-successstory-plugin/commit/d040e624715a265dd034e4d97ae03730589c6673
