### ISSUE TITLE
Some achivements dont load well and are blurred

### ISSUE THREAD

**Issue by electro97** [Lacro59/playnite-successstory-plugin#528]
**Describe the bug**
Some achivements added manually with steam dont load properly, but adding them with exophase load perfectly

**To Reproduce**
Steps to reproduce the behavior: Add manually a game achivements with steam

**Expected behavior**
All achivements added manually with steam should load fine

**Screenshots**
In Alba: A Wildlife Adventure none of the achivements load ![image](https://github.com/user-attachments/assets/f37e6b7b-4a8c-4893-9868-4bbc79032478) 
In 20 Minutes Till Dawn all the achievements load fine even with steam ![image](https://github.com/user-attachments/assets/f35d5998-2088-4d49-a6fd-e35e667338c5)

**Extensions log**
[extensions.log](https://github.com/user-attachments/files/16917164/extensions.log)

**Comment by electro97** [comment]
Nevermind, i just realised they were hidden achievements

**Comment by Lacro59** [comment]
You can configure how hidden achievements are displayed:
![image](https://github.com/user-attachments/assets/0ae58591-9f9f-4428-b3ed-39a3d1cd5095)
