### ISSUE TITLE
Is it normal that success story downloads data for all installed games at startup and it takes a few minutes?

### ISSUE THREAD

**Issue by Kinc4id** [Lacro59/playnite-successstory-plugin#530]
Since like two weeks I noticed that success story downloads data for all installed games which takes some time with 134 installed games. While it does I can't use playnite unless I cancel the download. Is this a change or did I just not notice it before?

**Comment by ellkay85** [comment]
Came here because I have this same issue since about two weeks back! It seems to be downloading metadata for all steam games, every time I start up Playnite, but not other services.

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-successstory-plugin/commit/d040e624715a265dd034e4d97ae03730589c6673
