### ISSUE TITLE
Epic Games Achievements are not updated and reset to 0

### ISSUE THREAD

**Issue by LiranDan** [Lacro59/playnite-successstory-plugin#532]
**Describe the bug**
Epic Games achievements will return the list of locked achievements, but will not show unlocked achievements.
If the game previously had unlocked achievements in playnite, after refresh it will show all achievements as locked.

**To Reproduce**
Refresh achievements on a game from Epic Games.
Profile is public but I've tried also private option with login

*I have the issue since previous versions (don't remember which) but hoped it will be solved in the latest (3.3.2)

**Expected behavior**
After refresh is complete the game will show unlocked achievements.

**Extensions log**
[extensions.log](https://github.com/user-attachments/files/17104055/extensions.log)

**Comment by LiranDan** [comment]
Forgot to add:
Games with achievements that I tested: Rage 2 and Dungeons 3.
The issue in the log shows: No TrueAchievements url for <game>

**Comment by Lacro59** [comment]
#470
