### ISSUE TITLE
About not being able to get the PSN trophy

### ISSUE THREAD

**Issue by miros3240** [Lacro59/playnite-successstory-plugin#533]
#431 

I understand the above questions and answers about the PSN trophy

Do I still need to personally modify the code to get the PSN trophy?
Or am I the problem now that it's fixed?

Thank you

[playnite.log](https://github.com/user-attachments/files/17106686/playnite.log)

**Comment by Lacro59** [comment]
Data for PSN is linked to the PSN library plugin.
If the PSN Library plugin is working, the trophies should be obtained.

**Comment by miros3240** [comment]
It was linked to the PSN library and I checked the PSN in successStory, but it didn't work

Did I set it up wrong?

I don't know since the program is supposed to work

Thank you for your answer
