### ISSUE TITLE
Authentication does not work in exophase

### ISSUE THREAD

**Issue by miros3240** [Lacro59/playnite-successstory-plugin#535]
Even if I try to log in to the expophase, only the verify human comes out infinitely, but it's impossible to log in

https://github.com/user-attachments/assets/90af057d-4c47-4821-bbbc-dc6169705bd6

[extensions.log](https://github.com/user-attachments/files/17177600/extensions.log)
[playnite.log](https://github.com/user-attachments/files/17177603/playnite.log)

**Comment by Koriebonx98** [comment]
same prob here

**Comment by Pradeoo** [comment]
For me, I can actually log in. But as soon as I close the add ons tab, I am no longer authenticated. Like it forgets my account each time I close out.
[extensions.log](https://github.com/user-attachments/files/17269509/extensions.log)
[playnite.log](https://github.com/user-attachments/files/17269510/playnite.log)

**Comment by Lacro59** [comment]
Can you try this version?
[playnite-successstory-plugin_3_3_2.zip](https://github.com/user-attachments/files/17634599/playnite-successstory-plugin_3_3_2.zip)

**Comment by miros3240** [comment]
> Can you try this version? [playnite-successstory-plugin_3_3_2.zip](https://github.com/user-attachments/files/17634599/playnite-successstory-plugin_3_3_2.zip)

It's working. Thank you

Some of the game pass games didn't work with the Achievement, so I was doing it manually

If I manually choose the date and time to achieve the Achievement, there is a bug that appears differently to the date two days ago or a day before

It seems like there's no end to each minor complaint, so I'm satisfied even now

Thanks again.
