### ISSUE TITLE
Achievements are shown as all unlocked

### ISSUE THREAD

**Issue by yomisimie** [Lacro59/playnite-successstory-plugin#536]
**Describe the bug**
All achievements appear unlocked

**To Reproduce**
Install plugin, update game data

**Expected behavior**
Show what achievements/trophies are unlocked and locked

**Screenshots**
Took a look in the cached data and it has a date of: `0001-01-01T00:00:00`
![image](https://github.com/user-attachments/assets/691dd212-8130-4b57-9e78-11d411ab15f7)

Error when refreshing uncached game data:
![image](https://github.com/user-attachments/assets/0bb1075b-f2e3-4888-b735-596ec28dd1e5)

**Extensions log**
```
30-09 19:16:54.970|INFO |SuccessStory#SuccessStoryDatabase:91/91 achievements found for Warframe
30-09 19:16:55.033|WARN |SuccessStory#SuccessStoryDatabase:No TrueAchievements url for Warframe
30-09 19:16:55.093|WARN |SuccessStory#SuccessStoryDatabase:No TrueAchievements url for Warframe
30-09 19:16:56.480|ERROR|SuccessStory#Common:Error on GetCount(): Error in GetCount(Day, 14acddcf-61bd-42bd-9446-57db266ba6b7, 10, False, False, False)|C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryStats.cs|83
System.ArgumentOutOfRangeException: The added or subtracted value results in an un-representable DateTime.
Parameter name: value
   at System.DateTime.AddTicks(Int64 value)
   at System.DateTime.Add(Double value, Int32 scale)
   at System.DateTime.AddDays(Double value)
   at SuccessStory.Services.SuccessStoryStats.GetCount(StatsType statsType, Nullable`1 id, Int32 limit, Boolean cutPeriod, Boolean onlyRA, Boolean excludeRA) in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryStats.cs:line 83
30-09 19:16:57.672|ERROR|SuccessStory#Common:Error on GetCount(): Error in GetCount(Day, 14acddcf-61bd-42bd-9446-57db266ba6b7, 15, False, False, False)|C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryStats.cs|83
System.ArgumentOutOfRangeException: The added or subtracted value results in an un-representable DateTime.
Parameter name: value
   at System.DateTime.AddTicks(Int64 value)
   at System.DateTime.Add(Double value, Int32 scale)
   at System.DateTime.AddDays(Double value)
   at SuccessStory.Services.SuccessStoryStats.GetCount(StatsType statsType, Nullable`1 id, Int32 limit, Boolean cutPeriod, Boolean onlyRA, Boolean excludeRA) in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\Services\SuccessStoryStats.cs:line 83
```

**Comment by yomisimie** [comment]
This seems to be the broken code, Considering the date is `0001-01-01T00:00:00` subtracting one day makes the date unreadable from what I understand.
```
                    for (int i = limit; i >= 0; i--)
                    {
                        chartLabels[limit - i] = (statsType == StatsType.Day)
                            ? (string)localDateConverter.Convert(startDateTime.AddDays(-i), null, null, null)
                            : (string)localDateYMConverter.Convert(startDateTime.AddMonths(-i), null, null, null);
                    }

```

**Comment by yomisimie** [comment]
The issue is the date, if I set in JSON the UnlockedDate to NULL it works great! But I don't think I can fix it, I don't really work with C# and I have to look through the code to see where it writes the dates wrong.

**Comment by yomisimie** [comment]
#537 added some code here that fixed my issue

**Comment by Lacro59** [comment]
Can you try this version ?
[playnite-successstory-plugin_3_3_2.zip](https://github.com/user-attachments/files/17647231/playnite-successstory-plugin_3_3_2.zip)

**Comment by yomisimie** [comment]
> Can you try this version ? [playnite-successstory-plugin_3_3_2.zip](https://github.com/user-attachments/files/17647231/playnite-successstory-plugin_3_3_2.zip)

This archive seems to work.

Before installing this I had the 3.3.2 updated from the Playnite plugin repository and it had the same date issue.
