### ISSUE TITLE
0.8 won't work

### ISSUE THREAD

**Issue by Inari-Whitebear** [Lacro59/playnite-successstory-plugin#54]
Hey,

I'm using Playnite 7.7. SuccessStory 0.7 works fine for me, but when I install 0.8 instead, I see the plugin not listed anywhere.

The log says:
`2020-08-08 22:23:32.8909|ERROR:Failed to load plugin: Success StorySystem.TypeLoadException: Could not load type 'PluginCommon.IntegrationUI' from assembly 'PluginCommon, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at SuccessStory.SuccessStory..ctor(IPlayniteAPI api)`

Any ideas what may be causing that?

**Comment by Lacro59** [comment]
Do you have another of my plugins? (like game activity, statistics, HowLongToBeat, ...)
If so, you need to update them also.

**Comment by Inari-Whitebear** [comment]
Ah, yeah, that was it, had HowLongToBeat and didn't update it in a bit. Thanks!
