### ISSUE TITLE
Retroachievements achievements are displayed at wrong place

### ISSUE THREAD

**Issue by Roschach96** [Lacro59/playnite-successstory-plugin#540]
**Describe the bug**
Retroachievements achievements are displayed under manual (a lot of zeros) and not under Retroachievements separate tab
(If the separate tab is not enabled these games still don't "go under" Retroachievements source)

**To Reproduce**
Menu -> Library > Setup Emulators -> (Add a game that has achievements on RA website)

**Expected behavior**
Game's achievements should display under Retroachievements tab (or Retroachievements as source if not used as separate tab)

**Screenshots**
![image](https://github.com/user-attachments/assets/fdb33272-061b-4762-8c21-8edbe1bb2a83)
![image](https://github.com/user-attachments/assets/cfa0c57d-12f6-44aa-a89c-ff378bfd7578)

Third image is just a proof that after adding the game to my Library as an emuloated game, SuccessStory adds its correct Retroachievements ID to it and syncs my achievements from my profile to here but it doesn't get added to RA tab. (or RA source if tab is not enabled.)
![image](https://github.com/user-attachments/assets/0e593975-8439-49de-a6e0-4db064a4d5a1)

**Extensions log**
[extensions.log](https://github.com/user-attachments/files/17269807/extensions.log)

**Comment by Lacro59** [comment]
#542
