### ISSUE TITLE
RetroAchievements not populating correctly

### ISSUE THREAD

**Issue by alexmkidd01** [Lacro59/playnite-successstory-plugin#542]
![image](https://github.com/user-attachments/assets/c33a1967-f7f4-4fe9-8269-d9ce9d158e42)

Hello,

I did a search and I could not find anything. Does anyone know why my retro games are not populating as RetroAchievements? My achievements are being tracked automatically, as you can see with donkey kong country. But the source is showing as 0000. 

(The full source when I extend the column width is: "00000000-0000-0000-0000-000000000000")

Does anyone know how to fix this?

**Comment by ch13696** [comment]
I get this same problem with both RetroAchievements and RPCS3. Top game is RPCS3 and bottom is RA.
![Screenshot 2024-10-20 090606](https://github.com/user-attachments/assets/0bc42e1f-f962-4a0a-9fc5-5df2709d78c9)

**Comment by Lacro59** [comment]
Can you try this version ?
[playnite-successstory-plugin_3_3_2.zip](https://github.com/user-attachments/files/17461076/playnite-successstory-plugin_3_3_2.zip)

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/89515ca636b57f189ec5982d174b6c6a78b83c69

**Comment by ch13696** [comment]
> Can you try this version ? [playnite-successstory-plugin_3_3_2.zip](https://github.com/user-attachments/files/17461076/playnite-successstory-plugin_3_3_2.zip)

Looks like re-applying the update works,

**Comment by alexmkidd01** [comment]
I couldn't get it to work, but I can keep trying.
