### ISSUE TITLE
"Achievements database has been reset."

### ISSUE THREAD

**Issue by Inari-Whitebear** [Lacro59/playnite-successstory-plugin#55]
If I try to download any of the achievements, it just has a progress bar that works for a while. Then it goes "Achievements database has been reset" and the numbers are still 0/something.

I gave it my Steam API key. And the log doesn't say anything either, so I'm unsure how to even give more info on this :x 
Tried Get missing, as well as Refresh data. Even tried deleting what I think is the folder of it in ExtensionsData to see if there was some corrupted storage somehow.

**Comment by Lacro59** [comment]
Are this manipulations did in settings menu?
Are not there any achievements on game selected and/or the main plugin screen?
Can you show the Playnite.log after try this manipulations?

**Comment by Inari-Whitebear** [comment]
Nevermind I'm dumb... working on a custom theme and didn't style the checkbox background yet, so they have the same colour as the background, and thus didn't realize there was a checkbox to turn on ¬_¬

Sorry :x
