### ISSUE TITLE
SuccessStory - Reference to object not established as an instance of an object

### ISSUE THREAD

**Issue by Despuesin** [Lacro59/playnite-successstory-plugin#552]
The bug in question occurs when I try to download the plugin data through the option in extensions; the data download goes relatively normally until it finishes, it doesn't download or do anything and the error pops up.

![image](https://github.com/user-attachments/assets/136ae0fd-3fca-4f35-bc28-f3070713fc29)
 
These are the log files:

[extensions.log](https://github.com/user-attachments/files/17882674/extensions.log)
[playnite.log](https://github.com/user-attachments/files/17882675/playnite.log)

**Comment by SparrowBrain** [comment]
Happens here too. In my case it's occurs after I play an Epic game that does not have any achievements.

**Comment by Xs3roN** [comment]
Experiencing that issue too, I checked the GOG account sync as the notif was about the GOG and I noticed it is duped the same from Epic

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/ba97ae162ca29200a25a8e83fa7b5ae32e8c6c69

**Comment by Kyzoku** [comment]
Getting this problem with Epic achievements. Tried setting it to both private and public and I made sure my epic account achievements privacy is public.
