### ISSUE TITLE
Re-authenticating Steam account crashes Playnite

### ISSUE THREAD

**Issue by chocolatechipcats** [Lacro59/playnite-successstory-plugin#555]
**Describe the bug**
In 3.4, reauthenticating a private Steam account causes an unrecoverable error in Playnite. Does not occur on previous version.

**To Reproduce**
Replicated this twice.

1. Open the plugin settings and go to Libraries > Steam.
2. With 'is private' checked, click the Authenticate button.
3. Login. 
4. After inputting the two-factor code from email, Playnite crashes.

**Expected behavior**
Not a crash!

**Extensions log**

Also contains playnite.log. Zipped for size.
[extensions.log.zip](https://github.com/user-attachments/files/17895303/extensions.log.zip)

**Comment by Lacro59** [comment]
Can you try this version?
[playnite-successstory-plugin_3_4.zip](https://github.com/user-attachments/files/18081780/playnite-successstory-plugin_3_4.zip)

**Comment by JSGit19** [comment]
That fixed the issue. I checked the version before and it said that it already was 3.4.

**Comment by chocolatechipcats** [comment]
It's not working for me. No crash, but after inputting the two-factor code, I get "authenticating..." and then it goes back to Requires authentication.

**Comment by Alamei** [comment]
Did you restart the application after installing the test version Lacro59 provided (even if you were "upgrading" from 3.4 to 3.4)? I was experiencing the exact behavior you were describing, and the fix worked immediately for me upon installing the offered version and rebooting Playnite.

**Comment by chocolatechipcats** [comment]
Yes, I restarted. Then I restarted again after the first failure just to check.
