### ISSUE TITLE
"Value Cannot be Null" Error

### ISSUE THREAD

**Issue by burnpsy** [Lacro59/playnite-successstory-plugin#557]
**Describe the bug**
I get a "value cannot be null" error when I exit a Steam game.

**To Reproduce**
Launch a video game on Steam that has Steam achievements, then close it.

**Extensions log**
> 25-11 18:07:05.584|INFO |SuccessStory#SuccessStoryDatabase:RefreshNoLoader(Yu-Gi-Oh! Master Duel - e0002fd7-0b9b-4eaf-890e-04fc59124843)
> 25-11 18:07:05.584|INFO |SuccessStory#SuccessStoryDatabase:Used SuccessStory.Clients.SteamAchievements for Yu-Gi-Oh! Master Duel - Steam/Steam/PC
> 25-11 18:07:05.584|INFO |SuccessStory#SteamAchievements:SteamApi.GetAchievements(Yu-Gi-Oh! Master Duel, 1449850)
> 25-11 18:07:05.806|INFO |SuccessStory#SteamApi:GetAchievementsByWeb()
> 25-11 18:07:05.831|WARN |SuccessStory#StoreApi:Expired cookies
> 25-11 18:07:41.976|ERROR|SuccessStory#Common:Error on GetAchievements()|C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\Steam\SteamApi.cs|369
> System.ArgumentNullException: Value cannot be null.
> Parameter name: value
>    at System.String.IndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
>    at CommonPluginsStores.StoreApi.<>c__DisplayClass60_0.<GetWebCookies>b__2(String y) in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\StoreApi.cs:line 208
>    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
>    at CommonPluginsStores.StoreApi.<GetWebCookies>b__60_0(HttpCookie x) in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\StoreApi.cs:line 208
>    at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at CommonPluginsStores.StoreApi.GetWebCookies() in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\StoreApi.cs:line 207
>    at CommonPluginsStores.StoreApi.GetStoredCookies() in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\StoreApi.cs:line 165
>    at CommonPluginsStores.Steam.SteamApi.GetAchievementsByWeb(UInt32 appId, AccountInfos accountInfos, ObservableCollection`1 gameAchievements) in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\Steam\SteamApi.cs:line 1083
>    at CommonPluginsStores.Steam.SteamApi.GetAchievements(String id, AccountInfos accountInfos) in C:\Projects\C#\Lacro59\playnite-successstory-plugin\source\playnite-plugincommon\CommonPluginsStores\Steam\SteamApi.cs:line 369
> 25-11 18:07:41.983|WARN |SuccessStory#SuccessStoryDatabase:No achievements found for Yu-Gi-Oh! Master Duel

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-successstory-plugin/commit/b17218dea14e066472ed5ed8576dbd4e72037a4d
