### ISSUE TITLE
SuccessStory 3.4

### ISSUE THREAD

**Issue by Mike-Aniki** [Lacro59/playnite-successstory-plugin#558]
Hi! I just discovered your fork of SuccessStory, and I love it ! Thanks for your amazing work. 😊 However, the latest version of SuccessStory includes a really handy feature: sorting trophies by unlock date (ascending or descending) in fullscreen mode. Do you think it would be possible to update your fork to include this option ?

**Comment by eFMann** [comment]
> Hi! I just discovered your fork of SuccessStory, and I love it ! Thanks for your amazing work. 😊 However, the latest version of SuccessStory includes a really handy feature: sorting trophies by unlock date (ascending or descending) in fullscreen mode. Do you think it would be possible to update your fork to include this option ?

Hi, not sure but believe you’re talking about my fork? 

I have merged all the changes already but there’s a slight problem with Xbox360 achievements atm. I will get this sorted this week and will release the new update.

The new update will also include ShadPS4 achievements
