### ISSUE TITLE
"Get account ID" for GOG links to the Epic ID website. 

### ISSUE THREAD

**Issue by SomeKittyCat** [Lacro59/playnite-successstory-plugin#563]
**Describe the bug**
In the extensions settings if you go to libraries and click in the "get account ID" button for GOG it links you to the webpage to get the ID for a Epic account, 

**To Reproduce**
Steps to reproduce the behavior: Go to the extension settings > libraries > go to GOG > click the "get account ID" link.

**Expected behavior**
Open a website to get a GOG ID.

**Screenshots**
Not needed (I think)

**Extensions log**
Not needed (I think)

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/66c13d2dc4018cc57973420a3b5567d054e911ef
