### ISSUE TITLE
A Coupe of Download Plugin Data Errors

### ISSUE THREAD

**Issue by Chaoxufurwa** [Lacro59/playnite-successstory-plugin#570]
### "Value Cannot Be Null - Parameter Name:key" Error

**Describe the bug**
Occurred whilst trying to update plugin data.

**To Reproduce**
1. Go to Extensions/SuccessStory/Download Plugin Data
2. Select any parameters and click OK.
3. Error notification.

**Expected behavior**
Plugin data should download for selected games in the library.

**Screenshots**

![screencap](https://github.com/user-attachments/assets/639c40e3-61c0-497c-8ce4-d5f98efe1414)

**Extensions log**

[SuccessStory_2024-12-19.zip](https://github.com/user-attachments/files/18203890/SuccessStory_2024-12-19.zip)

### Object Reference set to an instance of an object

**Describe the bug**
Occurred whilst trying to update plugin data.

**To Reproduce**
1. Go to Extensions/SuccessStory/Download Plugin Data
2. Select "old data" option and click OK.
3. Error notification.

**Expected behavior**
Plugin data should download for old games in the library.

**Screenshots**

![screencap2](https://github.com/user-attachments/assets/c595628b-c18b-498e-b6d4-872f3d08a275)

**Extensions log**

[SuccessStory_2024-12-19.zip](https://github.com/user-attachments/files/18203925/SuccessStory_2024-12-19.zip)

**Comment by Lacro59** [comment]
#552
#557
