### ISSUE TITLE
no achievements from RetroAchievements

### ISSUE THREAD

**Issue by Lacro59** [Lacro59/playnite-successstory-plugin#58]
from Discord (Destinyblade #0894)
I can't see the achievements for Castlevania SOTN
[playnite.log](https://github.com/Lacro59/playnite-successstory-plugin/files/5083128/playnite.log)

**Comment by Lacro59** [comment]
In Discord from @Deide#6005

@Lacro59 I think a it might be nicer to work with md5 hashes with retroachievements in Success Story, since that is what it goes by in the service.
What you could do is generate the hashes for all games under the supported platforms, then use something like http://retroachievements.org/dorequest.php?r=hashlibrary&c=18 (where c=18 is console ID 18 - Nintendo DS) and get all supported hashes and their associated RA game ids.

@Lacro59 It's what they themselves use https://github.com/RetroAchievements/RASuite/blob/3c68b8ae891aec4341dcf5a033355e00125ca546/RA_Integration/RA_httpthread.cpp#L70
There is a problem, however. You'd have to use a proper rom checksum algorithm rather than getting a hash of the file, since that's what  the emulators (and RA itself) use. I think it's mostly a case of hashing a rom while taking into account the relevant zero-padding for headers and stuff.

**Comment by Deide** [comment]
With regards to the rom checksums, I think you can see how [rcheevos](https://github.com/RetroAchievements/rcheevos) does it in `rhash/hash.c`; the [`rc_hash_nintendo_ds`](https://github.com/RetroAchievements/rcheevos/blob/0e94018eb858b716b92cda93617a16c3cbcb2fa0/src/rhash/hash.c#L583) being an example for NDS.

**Comment by Lacro59** [comment]
From EustaceCS on forum (https://playnite.link/forum/thread-275-post-2695.html#pid2695)

How, by any chance, can I make the plugin fetch different achievement lists for
Battletoads (GameBoy) https://retroachievements.org/game/2211
Battletoads (NES) https://retroachievements.org/game/1509
?
That's two completely different games.
PlayNite recognizes them as separate entries with different release dates, covers, etc. SuccessStory does not (achievements from the latter are being displayed for both).

Also, are Arcade games supported?
Metal Slug series does have achievements at RetroAchievements (MS5, as example: https://retroachievements.org/game/12027 ) but SuccessStory doesn't show any.
