### ISSUE TITLE
add rpcs3 trophies

### ISSUE THREAD

**Issue by Lacro59** [Lacro59/playnite-successstory-plugin#59]
On forum from xrayspex (https://playnite.link/forum/thread-275-post-1530.html#pid1530)

Is there a way to read the trophies unlocked via the rpcs3 emulator? The client clearly is keeping a local profile that tracks trophies as you can bring up an interface within rpcs3 to see them. It would be great to have this plugin read that and display the progress.

**Comment by Lacro59** [comment]
https://www.truetrophies.com/

**Comment by greggameplayer** [comment]
@Lacro59 
trophies are stored within the same dev_hdd0 folder as games the path to get them is : dev_hdd0/home/00000001/trophy.
Inside there are folders which games you have which contains all the trophies images and also a TROPCONF.SFM which contains the name and details of all the trophies within the game and also there is a TROPUSR.DAT.
TROPUSR.DAT doesn't seems to be readable but it might contains the trophies obtain by the user.

To understand the general ways they've made the system you can check these two PRs from RPCS3 Github : 
[Trophy notification PR](https://github.com/RPCS3/rpcs3/pull/3204)
[Trophy Manager PR](https://github.com/RPCS3/rpcs3/pull/3665)
