### ISSUE TITLE
Updated to 10.1, Now No Achievements

### ISSUE THREAD

**Issue by LeeThompson** [Lacro59/playnite-successstory-plugin#63]
Updated extension to 10.1 (from 0.9) and now SuccessStory is essentially no longer working.  Achievements no longer show up in fact it just says " / "

Playnite 7.9

(Reverted back to 0.9)

**Comment by Lacro59** [comment]
Are you using eMixedNite theme?

**Comment by LeeThompson** [comment]
I just checked and I am using that theme.
