### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by LeeThompson** [Lacro59/playnite-successstory-plugin#64]
With Success Story  0.10.1 (and eMixedNIte 0.36 with your Views modification) it says "SUCESS STORY" (spelled incorrectly) instead of "ACHIEVEMENTS".

**Comment by LeeThompson** [comment]
UPDATE: Success Story 0.10.2 (eMixedNite 0.53)

Error still present.

![success_story_text_bug](https://user-images.githubusercontent.com/1982261/92972801-bd07b900-f437-11ea-863b-343090253155.jpg)

**Comment by Lacro59** [comment]
The issue is on the theme not from plugin.

**Comment by LeeThompson** [comment]
I see, no problem.  I posted on the forum in the theme's thread.  (I also actually just fixed it on my local copy.)
