### ISSUE TITLE
show current version in the extension dialog

### ISSUE THREAD

**Issue by slippycheeze** [Lacro59/playnite-successstory-plugin#66]
G'day.  I've been getting notifications that an update to SuccessStory 0.11 is available, but I was pretty certain I'd installed that.  I wanted to check what version the in-game extension thought this was, but I couldn't find it anywhere.

The place I'd have expected to see that was the extension dialog popped up when I go to menu > extensions > SuccessStory.  That'd make the currently running version much more visible.

PS: the root cause was that I ended up with two installed versions of the extension, but that isn't relevant to the specific feature request. :)

**Comment by Lacro59** [comment]
The version of plugins is here in settings menu:
![image](https://user-images.githubusercontent.com/124054/93368625-84f4e180-f84e-11ea-83bf-d8abe39b02f4.png)
