### ISSUE TITLE
Achievement list does not shows complete when using custom heigth

### ISSUE THREAD

**Issue by eminaguil** [Lacro59/playnite-successstory-plugin#68]
When using custom height in the achievement list, only a part of it, is used, the space left, is blank.

Here is an example:
[https://playnite.link/forum/thread-275-post-1759.html#pid1759](https://playnite.link/forum/thread-275-post-1759.html#pid1759)

The code is

`<StackPanel Name="PART_Achievements_List" Height="200" Margin="8,0,12,8" />`

**Comment by Lacro59** [comment]
The issue will resolve with the next version.
But, There are some problems with your theme.
I modified the problematic elements:
[DetailsViewGameOverview.zip](https://github.com/Lacro59/playnite-successstory-plugin/files/5286510/DetailsViewGameOverview.zip)
