### ISSUE TITLE
Request: Option For Horizontal Achievement List

### ISSUE THREAD

**Issue by xyifer12** [Lacro59/playnite-successstory-plugin#72]
I'm not sure if you're willing to take requests but I'm giving it a shot.

Adding an option to make the achievement list scroll horizontally instead of vertically would be a great addition for theme creators.

I've made a basic example of the request.
https://hg1.funnyjunk.com/comments/+_a10d8b3e1f5218d64955b4163aee2c8d.png

**Comment by SaltySamurai** [comment]
I suppose this would be an extension of the compact achivements list? I'd like to add that in compact mode, the achivments requierment should be included in the tooltip that shows the name of an achivements and the date you unlocked it.
