### ISSUE TITLE
Xbox user is not authenticated

### ISSUE THREAD

**Issue by Jordan-Ch** [Lacro59/playnite-successstory-plugin#75]
Hello,

My achievements from GamePass are not syncing. I get two notifications.

SuccessStory - <!LOCSucessStoryNotificationsXboxNotAuthenticate!!>
SuccessStory - Xbox user is not authenticated

How can I solve this?

**Comment by Lacro59** [comment]
Hi,
This message appraer when your xbox account is not logged.
Have you check that your xbox account is logged with Xbox Library and try again?

**Comment by BloodShed-Oni** [comment]
I'm having the same problem.

I tried re-authenticating again made no difference with achievements.

**Comment by Lacro59** [comment]
@BloodShed-Oni Can you post your Playnite.log?

**Comment by BloodShed-Oni** [comment]
Clean install of 1.1.2 fixed it.
