### ISSUE TITLE
"Steam profile is not public" but it definitely is

### ISSUE THREAD

**Issue by ethansshaw** [Lacro59/playnite-successstory-plugin#76]
I recently built a new computer, and am in the process of setting up Playnite on it. I downloaded 1.0 and then 1.1 this morning, and both times I got the error message above. However, my profile is definitely public. I even tried setting it to private and then back to public, no dice. I also tried deleting success story from the appdata folder, and reinstalled it, still no dice. Any ideas on what I could do? Thanks!

**Comment by Lacro59** [comment]
Have you "My profile" and "Game details" on "public"?

**Comment by ethansshaw** [comment]
Yes, attached is a screenshot of my settings
https://imgur.com/a/QDyRamx

**Comment by Lacro59** [comment]
I published a new release with more debug information.
Can you try again and post your Playnite.log?

**Comment by ethansshaw** [comment]
[playnite.log](https://github.com/Lacro59/playnite-successstory-plugin/files/5514266/playnite.log)

**Comment by Lacro59** [comment]
You log indicates that you have a forbidden access.

Have you check that your Steam ID and API key is correct in Steam Library plugin?
![image](https://user-images.githubusercontent.com/124054/98715093-f69e6700-2389-11eb-87e0-a33780d6e885.png)

**Comment by ethansshaw** [comment]
Somehow, despite my profile being Public not Private, entering the API Key fixed the problem. Thank you!
