### ISSUE TITLE
Don't show different elements if no data is available by default

### ISSUE THREAD

**Issue by darklinkpower** [Lacro59/playnite-successstory-plugin#77]
Example: This game doesn't have unlocked achievements.

![imagen](https://user-images.githubusercontent.com/1389286/98443836-b0b87900-20d3-11eb-8cc7-a5f71c8d5143.png)

If this is the case, the element should be collapsed (not talking space) without needing to check manually via a `DynamicResource`. The same should happen for:

- `PART_Achievements_ListCompactLocked` Don't show it if there are no unlocked achievements
- `PART_Achievements_List` Don't show it if there are no achievements.
- etc

**Comment by Lacro59** [comment]
I started to improve the system.

For hide a element when there is not unlocked achievement, you can do it:
```
<StackPanel x:Name="PART_Achievements_ListCompactUnlocked" Background="{DynamicResource ButtonBackgroundBrush}" 
			Tag="{DynamicResource Sc_Unlocked}" Margin="0,10,0,0">
   <StackPanel.Style>
		<Style>
			<Setter Property="Control.Visibility" Value="Visible" />
			<Style.Triggers>
				<DataTrigger Binding="{Binding RelativeSource={RelativeSource Self}, Path=Tag}" Value="0">
					<Setter Property="Control.Visibility" Value="Collapsed" />
				</DataTrigger>
			</Style.Triggers>
		</Style>
	</StackPanel.Style>
</StackPanel>
```

**Comment by Lacro59** [comment]
Rework with 2.0 and Playnite 9 UI integration.

**Comment by darklinkpower** [comment]
I'm still having this issue with `SuccessStory_PluginCompactLocked`.

I've not checked if it still hapesn with the other ones

![image](https://user-images.githubusercontent.com/1389286/132655925-b4640096-a40b-40f1-9c23-42474a2fec5b.png)

![image](https://user-images.githubusercontent.com/1389286/132656002-63c3d528-0209-4b7f-ba70-f5db82a4e86c.png)

**Comment by Lacro59** [comment]
fixed
