### ISSUE TITLE
plugin keeps crashing after update to latest version

### ISSUE THREAD

**Issue by woutercools** [Lacro59/playnite-successstory-plugin#80]
[playnite.log](https://github.com/Lacro59/playnite-successstory-plugin/files/5505576/playnite.log)

edit: after playing with the option in the appearance tab, the crashing ended, but it won't show the button in the game details.

![2020-11-08 15_12_21-Window](https://user-images.githubusercontent.com/16439116/98467376-33752d00-21d5-11eb-8f36-19b1dc700b63.jpg)

Can this be solved by resetting the achievements database?

**Comment by Lacro59** [comment]
I published a new release with more debug information.
Can you try again and post your Playnite.log?

**Comment by woutercools** [comment]
Keeps crashing with v1.1.1
[playnite.log](https://github.com/Lacro59/playnite-successstory-plugin/files/5511004/playnite.log)

**Comment by kristheb** [comment]
plugin crashes also when clicking on _Download missing achievements_, either steam, gog or the others. 
[issue_80.log](https://github.com/Lacro59/playnite-successstory-plugin/files/5515851/issue_80.log)
