### ISSUE TITLE
Playnite crashes when clicking the achievements button in game details

### ISSUE THREAD

**Issue by woutercools** [Lacro59/playnite-successstory-plugin#85]
v.1.2.1

![image](https://user-images.githubusercontent.com/16439116/102068975-71312b00-3dfd-11eb-9766-ee2f148d39c9.png)

![image](https://user-images.githubusercontent.com/16439116/102069176-b190a900-3dfd-11eb-8c9a-90a5a2b64038.png)

![image](https://user-images.githubusercontent.com/16439116/102069076-932aad80-3dfd-11eb-8215-27b9c18f5a36.png)

**Comment by Lacro59** [comment]
I can't reproduce this issue.
Can you post your Playnite.log?
Thanks.

**Comment by woutercools** [comment]
[playnite.log](https://github.com/Lacro59/playnite-successstory-plugin/files/5694611/playnite.log)

**Comment by Lacro59** [comment]
Do you use DescriptionEditor plugin?

**Comment by woutercools** [comment]
yes

**Comment by Lacro59** [comment]
Can you test with the last version of DescriptionEditor and SuccessStory?

**Comment by woutercools** [comment]
No, still crashing.

I uninstalled and re-installed both extrensions before trying to click the button.

**Comment by Lacro59** [comment]
Can you post your a new Playniote.log?
Thanks.

**Comment by woutercools** [comment]
[playnite.log](https://github.com/Lacro59/playnite-successstory-plugin/files/5736005/playnite.log)

**Comment by woutercools** [comment]
Still crashing with v.1.3.2

**Comment by woutercools** [comment]
v1.3.3 Doesn't crash anymore, but nothing happens when clicking the button.

[playnite.log](https://github.com/Lacro59/playnite-successstory-plugin/files/5758408/playnite.log)

**Comment by woutercools** [comment]
v1.3.4 Still nothing happens when clicking the plugin button in game details

[playnite.log](https://github.com/Lacro59/playnite-successstory-plugin/files/5867700/playnite.log)

**Comment by woutercools** [comment]
v1.4.2 issue persists. Nothing happens when clicking the button.

[playnite.log](https://github.com/Lacro59/playnite-successstory-plugin/files/5939791/playnite.log)

**Comment by Lacro59** [comment]
Rework with v2.0 and Playnite 9 UI integration.
