### ISSUE TITLE
 arrangement of the list of achievements

### ISSUE THREAD

**Issue by Lacro59** [Lacro59/playnite-successstory-plugin#86]
from Goose on forum (https://playnite.link/forum/thread-275-post-2893.html#pid2893)

Is there a way to responsively resize the achievement list across the screen similar to how the library grid works?
Instead of a vertical list like this
![](https://i.imgur.com/OgNRwLI.jpg)

Have it in a responsive grid so it fills the space like this
![](https://i.imgur.com/TTO3CuR.jpg)

The extension is great so I would like to give it a dedicated full section in the grid view banner theme & have it respond to different aspect ratios along with the rest of the theme, currently it leaves a large amount of dead space.

**Comment by azuravian** [comment]
I see that this was resolved.  What do I need to do to take advantage of the change.  My list still shows a single column.

**Comment by Lacro59** [comment]
In plugin settings, in Appearance tabs, there àn option to defined the columns count.
