### ISSUE TITLE
Not getting Steam achievements

### ISSUE THREAD

**Issue by NopeTheKid** [Lacro59/playnite-successstory-plugin#96]
It scans the library
![image](https://user-images.githubusercontent.com/26711167/106313875-d2537780-6260-11eb-996b-9e8430379cea.png)
but it doesn't retireve any achievement
![image](https://user-images.githubusercontent.com/26711167/106314183-44c45780-6261-11eb-8a47-b3eebca82803.png)

In playnite.log it shows this error for all games:
>29-01 18:22:52.811|ERROR|Common:SuccessStory [H:\GitHub\Lacro59\playnite-successstory-plugin\Views\SuccessStorySettingsView.xaml.cs 424] - Error on RefreshData(Steam, True) for Aperture Tag: The Paint Gun Testing Initiative
>System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
>   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
>   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
>   at SuccessStory.Clients.SteamAchievements.CheckIsPublic(Int32 AppId) in H:\GitHub\Lacro59\playnite-successstory-plugin\Clients\SteamAchievements.cs:line 222
>   at SuccessStory.Views.SuccessStorySettingsView.<>c__DisplayClass45_0.<RefreshData>b__0() in H:\GitHub\Lacro59\playnite-successstory-plugin\Views\SuccessStorySettingsView.xaml.cs:line 424

**Comment by Lacro59** [comment]
duplicate #97
