### ISSUE TITLE
Steam achievements dont work with or without the api key in 1.4.1 or 1.4

### ISSUE THREAD

**Issue by MrArdillo** [Lacro59/playnite-successstory-plugin#97]
Steam achievements dont work with or without the api key in 1.4.1 or 1.4

**Comment by Lacro59** [comment]
Can you post your playnite.log?

**Comment by jaguima** [comment]
Here's a snippet of my playnite.log. I tried to refresh achievement data from 3 Steam games in my library. None of them showed up. Achievement data from other platforms seems to be working fine.


`30-01 15:54:27.119|WARN|ImageSourceManager:Image not found in database: C:\Games\Playnite\ExtraMetadata\games\b8924188-fa8b-4ed1-bfa6-fe27dbd65941\logo.png
30-01 15:54:27.128|DEBUG|HttpFileCache:Returning https://steamcdn-a.akamaihd.net/steam/apps/225140/page.bg.jpg from file cache C:\Games\Playnite\cache\images\5f8b245d2092754c9b895c54bf3c7301.jpg.
30-01 15:54:27.128|DEBUG|HttpFileCache:Returning https://steamcdn-a.akamaihd.net/steam/apps/225140/page.bg.jpg from file cache C:\Games\Playnite\cache\images\5f8b245d2092754c9b895c54bf3c7301.jpg.
30-01 15:54:27.207|WARN|PluginDatabaseObject`3:SuccessStory - VerifToAddOrShow() find no action for Steam
30-01 15:54:31.310|WARN|PluginDatabaseObject`3:SuccessStory - VerifToAddOrShow() find no action for Steam
30-01 15:54:35.227|WARN|ImageSourceManager:Image not found in database: C:\Games\Playnite\ExtraMetadata\games\590f16a7-2264-4879-be0b-4b3b4a30b78a\logo.png
30-01 15:54:35.236|DEBUG|HttpFileCache:Returning https://steamcdn-a.akamaihd.net/steam/apps/489830/page.bg.jpg from file cache C:\Games\Playnite\cache\images\27b191754d09539888a28a20cdd1cca4.jpg.
30-01 15:54:35.236|DEBUG|HttpFileCache:Returning https://steamcdn-a.akamaihd.net/steam/apps/489830/page.bg.jpg from file cache C:\Games\Playnite\cache\images\27b191754d09539888a28a20cdd1cca4.jpg.
30-01 15:54:38.159|WARN|PluginDatabaseObject`3:SuccessStory - VerifToAddOrShow() find no action for Steam
30-01 15:54:41.721|WARN|ImageSourceManager:Image not found in database: C:\Games\Playnite\ExtraMetadata\games\6cb7ed25-852f-4238-8b4b-b414aa053947\logo.png
30-01 15:54:41.770|WARN|PluginDatabaseObject`3:SuccessStory - VerifToAddOrShow() find no action for Steam
30-01 15:54:44.572|WARN|PluginDatabaseObject`3:SuccessStory - VerifToAddOrShow() find no action for Steam`


I took a quick look at the code. This warning message seems to be written here:

https://github.com/Lacro59/playnite-successstory-plugin/blob/4f30d9e2b95f67309e9ed1737111c4eba06e802b/Services/SuccessStoryDatabase.cs#L770

The warning message in the log mentions "Steam" with uppercase but the code in this method seems to check for GameSourceName as "steam" with lowercase:

https://github.com/Lacro59/playnite-successstory-plugin/blob/4f30d9e2b95f67309e9ed1737111c4eba06e802b/Services/SuccessStoryDatabase.cs#L583

Perhaps "Steam" is being passed as a parameter to this method with uppercase incorrectly? Or maybe it's not being transformed to lowercase in the method? A recent change in the line 583 above removed .ToLower() from the comparison, but it seems to be present for other game sources.

**Comment by shakeyourbunny** [comment]
I can confirm that Steam achievements are broken as of 1.4(.1).

Did a fresh install (alongside magpie 0.8.4 theme) and GOG achievements seem to show up, but not any Steam ones.
````
31-01 12:21:35.899|WARN|PluginDatabaseObject`3:SuccessStory - VerifToAddOrShow() find no action for Steam
31-01 12:21:35.908|ERROR|Common:CommonPluginsShared [H:\GitHub\Lacro59\playnite-successstory-plugin\playnite-plugincommon\CommonPluginsShared\IntegrationUI.cs 521] - Error in AddResources(Sc_HasData)
System.ArgumentException: Item has already been added. Key in dictionary: 'Sc_HasData'  Key being added: 'Sc_HasData'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Hashtable.Add(Object key, Object value)
   at System.Windows.ResourceDictionary.AddWithoutLock(Object key, Object value)
   at System.Windows.ResourceDictionary.Add(Object key, Object value)
   at CommonPluginsShared.IntegrationUI.AddResources(List`1 ResourcesList) in H:\GitHub\Lacro59\playnite-successstory-plugin\playnite-plugincommon\CommonPluginsShared\IntegrationUI.cs:line 521
31-01 12:21:35.908|WARN|PluginDatabaseObject`3:SuccessStory - VerifToAddOrShow() find no action for Steam
31-01 12:22:12.285|WARN|PluginDatabaseObject`3:SuccessStory - VerifToAddOrShow() find no action for Steam
31-01 12:22:20.885|WARN|PluginDatabaseObject`3:SuccessStory - VerifToAddOrShow() find no action for Steam
31-01 12:22:21.814|WARN|PluginDatabaseObject`3:SuccessStory - VerifToAddOrShow() find no action for Steam
````

![6GXJG0LR68](https://user-images.githubusercontent.com/5352403/106382392-a69ad380-63bf-11eb-8ee4-d25722653930.png)
